/**
 * Seed Data — Dados Iniciais da Base Jurídica
 *
 * ~50 súmulas mais estáveis (TST/STJ/STF)
 * ~50 artigos de lei mais citados (CF/CLT/CPC/CDC)
 * ~20 teses jurídicas universais
 *
 * Fonte: 'seed' — dados instalados no primeiro uso.
 * A base cresce organicamente com uso (fonte: 'usuario') e sync (fonte: 'sync').
 */

import { StoredSumula, StoredArticle, StoredThesis } from './legal-store';

const hoje = new Date().toISOString().split('T')[0]!;

// ═══════════════════════════════════════════════════════════════════════
// SÚMULAS — TST (~20) + STJ (~15) + STF (~15)
// ═══════════════════════════════════════════════════════════════════════

export const SEED_SUMULAS: StoredSumula[] = [
    // ── TST ──────────────────────────────────────────────────────────
    {
        id: 'TST-6',
        tribunal: 'TST',
        numero: 6,
        texto: 'Não se distingue entre empregados e avulsos para efeito de legislação social.',
        area: ['trabalhista'],
        keywords: ['avulso', 'empregado', 'igualdade', 'legislação social'],
        aplicacao: 'Equiparação de direitos entre empregados e trabalhadores avulsos.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-85',
        tribunal: 'TST',
        numero: 85,
        texto: 'A compensação de jornada de trabalho deve ser ajustada por acordo individual escrito, acordo coletivo ou convenção coletiva. O não-atendimento das exigências legais para a compensação de jornada, inclusive quando encetada mediante acordo tácito, não implica a repetição do pagamento das horas excedentes à jornada normal diária, se não dilatada a jornada máxima semanal, sendo devido apenas o respectivo adicional.',
        area: ['trabalhista'],
        keywords: ['compensação', 'jornada', 'banco de horas', 'acordo individual', 'horas extras'],
        aplicacao: 'Regras para compensação de jornada e banco de horas.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-102',
        tribunal: 'TST',
        numero: 102,
        texto: 'A cláusula contratual de garantia de emprego é válida desde que decorrente de negociação coletiva. A garantia de emprego decorrente de norma coletiva não impede a dispensa por justa causa.',
        area: ['trabalhista'],
        keywords: ['garantia de emprego', 'estabilidade', 'negociação coletiva', 'justa causa'],
        aplicacao: 'Validade de cláusula de garantia de emprego em norma coletiva.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-212',
        tribunal: 'TST',
        numero: 212,
        texto: 'O ônus de provar o término do contrato de trabalho, quando negados a prestação de serviço e o despedimento, é do empregador, pois o princípio da continuidade da relação de emprego constitui presunção favorável ao empregado.',
        area: ['trabalhista'],
        keywords: ['ônus da prova', 'contrato de trabalho', 'despedimento', 'continuidade'],
        aplicacao: 'Ônus da prova do término do contrato recai sobre o empregador.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-264',
        tribunal: 'TST',
        numero: 264,
        texto: 'A hora suplementar noturna será computada como de 52 minutos e 30 segundos.',
        area: ['trabalhista'],
        keywords: ['hora noturna', 'adicional noturno', 'hora suplementar', '52 minutos'],
        aplicacao: 'Cálculo da hora extra noturna com redução ficta.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-291',
        tribunal: 'TST',
        numero: 291,
        texto: 'A supressão total ou parcial, pelo empregador, de serviço suplementar prestado com habitualidade, durante pelo menos 1 ano, assegura ao empregado o direito à indenização correspondente ao valor de 1 mês das horas suprimidas, total ou parcialmente, para cada ano ou fração igual ou superior a seis meses de prestação de serviço acima da jornada normal.',
        area: ['trabalhista'],
        keywords: ['horas extras', 'supressão', 'habitualidade', 'indenização'],
        aplicacao: 'Indenização por supressão de horas extras habituais.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-331',
        tribunal: 'TST',
        numero: 331,
        texto: 'A contratação de trabalhadores por empresa interposta é ilegal, formando-se o vínculo diretamente com o tomador dos serviços, salvo no caso de trabalho temporário. A contratação irregular de trabalhador, mediante empresa interposta, não gera vínculo de emprego com os órgãos da Administração Pública direta, indireta ou fundacional.',
        area: ['trabalhista'],
        keywords: ['terceirização', 'empresa interposta', 'vínculo empregatício', 'tomador de serviços', 'administração pública'],
        aplicacao: 'Regras sobre terceirização lícita e ilícita.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-338',
        tribunal: 'TST',
        numero: 338,
        texto: 'É ônus do empregador que conta com mais de 10 empregados o registro da jornada de trabalho na forma do art. 74, § 2º, da CLT. A não-apresentação injustificada dos controles de frequência gera presunção relativa de veracidade da jornada de trabalho, a qual pode ser elidida por prova em contrário.',
        area: ['trabalhista'],
        keywords: ['jornada', 'controle de ponto', 'ônus da prova', 'registro', 'presunção'],
        aplicacao: 'Presunção de veracidade da jornada quando empregador não apresenta controles.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-340',
        tribunal: 'TST',
        numero: 340,
        texto: 'O empregado, sujeito a controle de horário, remunerado à base de comissões, tem direito ao adicional de, no mínimo, 50% pelo trabalho em horas extras, calculado sobre o valor-hora das comissões recebidas no mês, considerando-se como divisor o número de horas efetivamente trabalhadas.',
        area: ['trabalhista'],
        keywords: ['comissão', 'horas extras', 'adicional', 'comissionista'],
        aplicacao: 'Cálculo de horas extras para empregado comissionista.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-366',
        tribunal: 'TST',
        numero: 366,
        texto: 'O cartão de ponto que apresenta horários de entrada e saída uniformes é inválido como meio de prova, invertendo-se o ônus da prova, relativo às horas extras, que passa a ser do empregador, prevalecendo a jornada da inicial se dele não se desincumbir.',
        area: ['trabalhista'],
        keywords: ['cartão de ponto', 'britânico', 'horários uniformes', 'prova', 'horas extras'],
        aplicacao: 'Cartão de ponto britânico (horários uniformes) é inválido.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-428',
        tribunal: 'TST',
        numero: 428,
        texto: 'O uso de aparelho de intercomunicação, a exemplo de BIP, pager ou aparelho celular, pelo empregado, por si só, não caracteriza o regime de sobreaviso.',
        area: ['trabalhista'],
        keywords: ['sobreaviso', 'celular', 'BIP', 'pager', 'intercomunicação'],
        aplicacao: 'Uso de celular não configura sobreaviso automaticamente.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-437',
        tribunal: 'TST',
        numero: 437,
        texto: 'É válido o intervalo de 30 minutos para repouso e alimentação, previsto em acordo ou convenção coletiva de trabalho, para empregados submetidos a jornada de seis horas contínuas.',
        area: ['trabalhista'],
        keywords: ['intervalo', 'repouso', 'alimentação', 'jornada 6 horas', 'acordo coletivo'],
        aplicacao: 'Redução do intervalo para jornada de 6h via norma coletiva.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-443',
        tribunal: 'TST',
        numero: 443,
        texto: 'O fato de o empregado ter sido despedido por justa causa ou ter pedido demissão não exclui o seu direito ao recebimento dos direitos adquiridos durante o contrato de trabalho.',
        area: ['trabalhista'],
        keywords: ['justa causa', 'demissão', 'direitos adquiridos', 'verbas rescisórias'],
        aplicacao: 'Direitos adquiridos são devidos mesmo em justa causa.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-444',
        tribunal: 'TST',
        numero: 444,
        texto: 'É aplicável a presunção de discriminação do art. 1º da Lei 9.029/95 ao empregado portador de doença grave que gere estigma ou preconceito. Inválida a despedida do empregado portador de doença grave.',
        area: ['trabalhista'],
        keywords: ['discriminação', 'doença grave', 'estigma', 'despedida', 'reintegração'],
        aplicacao: 'Presunção de discriminação na dispensa de portador de doença grave.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-459',
        tribunal: 'TST',
        numero: 459,
        texto: 'No regime de revezamento, as horas trabalhadas em seguida ao repouso semanal de 24 horas, com prejuízo do intervalo mínimo de 11 horas consecutivas para descanso entre jornadas, devem ser remuneradas como extraordinárias, inclusive com o respectivo adicional.',
        area: ['trabalhista'],
        keywords: ['revezamento', 'repouso semanal', 'intervalo interjornada', '11 horas', 'horas extras'],
        aplicacao: 'Horas extras por violação do intervalo interjornada em regime de revezamento.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'TST-461',
        tribunal: 'TST',
        numero: 461,
        texto: 'Para a equiparação salarial, as funções exercidas pelos empregados devem ser idênticas, com diferença de tempo na função não superior a dois anos e na mesma localidade.',
        area: ['trabalhista'],
        keywords: ['equiparação salarial', 'função idêntica', 'isonomia', 'paradigma'],
        aplicacao: 'Requisitos para equiparação salarial entre empregados.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },

    // ── STJ ──────────────────────────────────────────────────────────
    {
        id: 'STJ-7',
        tribunal: 'STJ',
        numero: 7,
        texto: 'A pretensão de simples reexame de prova não enseja recurso especial.',
        area: ['processual'],
        keywords: ['recurso especial', 'reexame de prova', 'matéria fática', 'admissibilidade'],
        aplicacao: 'Impossibilidade de reexame de provas em recurso especial.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-54',
        tribunal: 'STJ',
        numero: 54,
        texto: 'Os juros moratórios fluem a partir do evento danoso, em caso de responsabilidade extracontratual.',
        area: ['civil'],
        keywords: ['juros moratórios', 'evento danoso', 'responsabilidade extracontratual', 'termo inicial'],
        aplicacao: 'Termo inicial dos juros moratórios na responsabilidade civil extracontratual.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-227',
        tribunal: 'STJ',
        numero: 227,
        texto: 'A pessoa jurídica pode sofrer dano moral.',
        area: ['civil'],
        keywords: ['dano moral', 'pessoa jurídica', 'honra objetiva', 'indenização'],
        aplicacao: 'Reconhecimento de dano moral a pessoa jurídica.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-297',
        tribunal: 'STJ',
        numero: 297,
        texto: 'O Código de Defesa do Consumidor é aplicável às instituições financeiras.',
        area: ['consumidor', 'civil'],
        keywords: ['CDC', 'instituição financeira', 'banco', 'consumidor', 'aplicabilidade'],
        aplicacao: 'Aplicação do CDC às relações bancárias.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-326',
        tribunal: 'STJ',
        numero: 326,
        texto: 'Na ação de indenização por dano moral, a condenação em montante inferior ao postulado na inicial não implica sucumbência recíproca.',
        area: ['civil', 'processual'],
        keywords: ['dano moral', 'valor inferior', 'sucumbência recíproca', 'honorários'],
        aplicacao: 'Dano moral — não há sucumbência recíproca por valor menor que o pedido.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-362',
        tribunal: 'STJ',
        numero: 362,
        texto: 'A correção monetária do valor da indenização do dano moral incide desde a data do arbitramento.',
        area: ['civil'],
        keywords: ['correção monetária', 'dano moral', 'arbitramento', 'termo inicial'],
        aplicacao: 'Correção monetária do dano moral — a partir do arbitramento.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-379',
        tribunal: 'STJ',
        numero: 379,
        texto: 'Nos contratos bancários não regidos por legislação específica, os juros moratórios poderão ser fixados em até 1% ao mês.',
        area: ['civil', 'consumidor'],
        keywords: ['juros moratórios', 'contrato bancário', 'um por cento', 'banco'],
        aplicacao: 'Limitação dos juros moratórios em contratos bancários.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-381',
        tribunal: 'STJ',
        numero: 381,
        texto: 'Nos contratos bancários, é vedado ao julgador conhecer, de ofício, da abusividade das cláusulas.',
        area: ['consumidor', 'civil'],
        keywords: ['cláusula abusiva', 'contrato bancário', 'ofício', 'vedação'],
        aplicacao: 'Juiz não pode declarar abusividade de cláusula bancária de ofício.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-385',
        tribunal: 'STJ',
        numero: 385,
        texto: 'Da anotação irregular em cadastro de proteção ao crédito, não cabe indenização por dano moral, quando preexistente legítima inscrição, ressalvado o direito ao cancelamento.',
        area: ['consumidor', 'civil'],
        keywords: ['cadastro', 'proteção ao crédito', 'inscrição', 'dano moral', 'SPC', 'Serasa'],
        aplicacao: 'Dano moral por negativação indevida — exige inexistência de inscrição prévia legítima.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-387',
        tribunal: 'STJ',
        numero: 387,
        texto: 'É lícita a cumulação das indenizações de dano estético e dano moral.',
        area: ['civil'],
        keywords: ['dano estético', 'dano moral', 'cumulação', 'indenização'],
        aplicacao: 'Possibilidade de cumular dano moral e dano estético.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-479',
        tribunal: 'STJ',
        numero: 479,
        texto: 'As instituições financeiras respondem objetivamente pelos danos gerados por fortuito interno relativo a fraudes e delitos praticados por terceiros no âmbito de operações bancárias.',
        area: ['consumidor', 'civil'],
        keywords: ['banco', 'responsabilidade objetiva', 'fraude', 'fortuito interno', 'operação bancária'],
        aplicacao: 'Responsabilidade objetiva do banco por fraudes de terceiros.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-548',
        tribunal: 'STJ',
        numero: 548,
        texto: 'Incumbe ao credor a exclusão do registro da dívida junto aos órgãos restritivos de crédito após o pagamento.',
        area: ['consumidor', 'civil'],
        keywords: ['exclusão', 'registro', 'dívida', 'crédito', 'pagamento', 'negativação'],
        aplicacao: 'Obrigação do credor de dar baixa na negativação após pagamento.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STJ-596',
        tribunal: 'STJ',
        numero: 596,
        texto: 'A incidência do imposto de renda sobre os juros de mora decorrentes de atraso no pagamento de remuneração salarial está condicionada à verificação da natureza jurídica dos juros.',
        area: ['tributario', 'trabalhista'],
        keywords: ['imposto de renda', 'juros de mora', 'remuneração', 'natureza jurídica'],
        aplicacao: 'IR sobre juros de mora em verbas salariais.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },

    // ── STF ──────────────────────────────────────────────────────────
    {
        id: 'STF-266',
        tribunal: 'STF',
        numero: 266,
        texto: 'Não cabe mandado de segurança contra lei em tese.',
        area: ['processual', 'administrativo'],
        keywords: ['mandado de segurança', 'lei em tese', 'ato normativo', 'cabimento'],
        aplicacao: 'Impossibilidade de MS contra lei em tese (somente ato concreto).',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-279',
        tribunal: 'STF',
        numero: 279,
        texto: 'Para simples reexame de prova não cabe recurso extraordinário.',
        area: ['processual'],
        keywords: ['recurso extraordinário', 'reexame de prova', 'matéria fática', 'admissibilidade'],
        aplicacao: 'Impossibilidade de reexame de provas em RE.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-283',
        tribunal: 'STF',
        numero: 283,
        texto: 'É inadmissível o recurso extraordinário, quando a decisão recorrida assenta em mais de um fundamento suficiente e o recurso não abrange todos eles.',
        area: ['processual'],
        keywords: ['recurso extraordinário', 'fundamento suficiente', 'inadmissibilidade'],
        aplicacao: 'RE deve impugnar todos os fundamentos suficientes da decisão.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-473',
        tribunal: 'STF',
        numero: 473,
        texto: 'A administração pode anular seus próprios atos, quando eivados de vícios que os tornam ilegais, porque deles não se originam direitos; ou revogá-los, por motivo de conveniência ou oportunidade, respeitados os direitos adquiridos, e ressalvada, em todos os casos, a apreciação judicial.',
        area: ['administrativo'],
        keywords: ['anulação', 'revogação', 'autotutela', 'ato administrativo', 'administração pública'],
        aplicacao: 'Poder de autotutela da Administração Pública.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-10',
        tribunal: 'STF',
        numero: 10,
        texto: 'Viola a cláusula de reserva de plenário (CF, artigo 97) a decisão de órgão fracionário de tribunal que, embora não declare expressamente a inconstitucionalidade de lei ou ato normativo do poder público, afasta sua incidência, no todo ou em parte.',
        area: ['processual', 'constitucional'],
        keywords: ['reserva de plenário', 'inconstitucionalidade', 'órgão fracionário', 'cláusula', 'art. 97'],
        aplicacao: 'Súmula Vinculante — reserva de plenário para declarar inconstitucionalidade.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-11',
        tribunal: 'STF',
        numero: 11,
        texto: 'Só é lícito o uso de algemas em casos de resistência e de fundado receio de fuga ou de perigo à integridade física própria ou alheia, por parte do preso ou de terceiros, justificada a excepcionalidade por escrito, sob pena de responsabilidade disciplinar, civil e penal do agente ou da autoridade e de nulidade da prisão ou do ato processual a que se refere, sem prejuízo da responsabilidade civil do Estado.',
        area: ['penal', 'constitucional'],
        keywords: ['algemas', 'preso', 'dignidade', 'excepcionalidade', 'nulidade'],
        aplicacao: 'Súmula Vinculante — uso excepcional de algemas.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-13',
        tribunal: 'STF',
        numero: 13,
        texto: 'A nomeação de cônjuge, companheiro ou parente em linha reta, colateral ou por afinidade, até o terceiro grau, inclusive, da autoridade nomeante ou de servidor da mesma pessoa jurídica investido em cargo de direção, chefia ou assessoramento, para o exercício de cargo em comissão ou de confiança ou, ainda, de função gratificada na administração pública direta e indireta em qualquer dos poderes da União, dos Estados, do Distrito Federal e dos Municípios, compreendido o ajuste mediante designações recíprocas, viola a Constituição Federal.',
        area: ['administrativo', 'constitucional'],
        keywords: ['nepotismo', 'nomeação', 'parente', 'cargo em comissão', 'administração pública'],
        aplicacao: 'Súmula Vinculante — vedação ao nepotismo.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-14',
        tribunal: 'STF',
        numero: 14,
        texto: 'É direito do defensor, no interesse do representado, ter acesso amplo aos elementos de prova que, já documentados em procedimento investigatório realizado por órgão com competência de polícia judiciária, digam respeito ao exercício do direito de defesa.',
        area: ['penal', 'constitucional'],
        keywords: ['defensor', 'acesso', 'prova', 'inquérito', 'direito de defesa', 'investigação'],
        aplicacao: 'Súmula Vinculante — acesso do advogado aos autos de inquérito.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-25',
        tribunal: 'STF',
        numero: 25,
        texto: 'É ilícita a prisão civil de depositário infiel, qualquer que seja a modalidade do depósito.',
        area: ['civil', 'constitucional'],
        keywords: ['prisão civil', 'depositário infiel', 'depósito', 'ilicitude'],
        aplicacao: 'Súmula Vinculante — vedação à prisão civil do depositário infiel.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-37',
        tribunal: 'STF',
        numero: 37,
        texto: 'Não cabe ao Poder Judiciário, que não tem função legislativa, aumentar vencimentos de servidores públicos sob o fundamento de isonomia.',
        area: ['administrativo', 'constitucional'],
        keywords: ['vencimentos', 'servidor público', 'isonomia', 'poder judiciário', 'legislativo'],
        aplicacao: 'Súmula Vinculante — Judiciário não pode conceder aumento por isonomia.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'STF-SV-56',
        tribunal: 'STF',
        numero: 56,
        texto: 'A falta de estabelecimento penal adequado não autoriza a manutenção do condenado em regime prisional mais gravoso, devendo-se observar, nessa hipótese, os parâmetros fixados no RE 641.320/RS.',
        area: ['penal'],
        keywords: ['regime prisional', 'estabelecimento penal', 'regime mais gravoso', 'progressão'],
        aplicacao: 'Súmula Vinculante — preso não pode ficar em regime mais gravoso por falta de vaga.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
];

// ═══════════════════════════════════════════════════════════════════════
// ARTIGOS DE LEI — CF (~10) + CLT (~15) + CPC (~15) + CDC (~10)
// ═══════════════════════════════════════════════════════════════════════

export const SEED_ARTICLES: StoredArticle[] = [
    // ── CF ───────────────────────────────────────────────────────────
    {
        id: 'CF-1',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 1º',
        texto: 'A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos: I - a soberania; II - a cidadania; III - a dignidade da pessoa humana; IV - os valores sociais do trabalho e da livre iniciativa; V - o pluralismo político.',
        area: ['constitucional'],
        keywords: ['fundamentos', 'república', 'dignidade', 'cidadania', 'soberania'],
        uso: 'Fundamentos da República — base para argumentação de direitos fundamentais.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-5-caput',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 5º, caput',
        texto: 'Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.',
        area: ['constitucional'],
        keywords: ['igualdade', 'direitos fundamentais', 'vida', 'liberdade', 'segurança', 'propriedade'],
        uso: 'Cláusula geral de igualdade e direitos fundamentais.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-5-XXXV',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 5º, XXXV',
        texto: 'A lei não excluirá da apreciação do Poder Judiciário lesão ou ameaça a direito.',
        area: ['constitucional', 'processual'],
        keywords: ['acesso à justiça', 'inafastabilidade', 'jurisdição', 'direito de ação'],
        uso: 'Princípio da inafastabilidade da jurisdição.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-5-LIV',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 5º, LIV',
        texto: 'Ninguém será privado da liberdade ou de seus bens sem o devido processo legal.',
        area: ['constitucional', 'processual'],
        keywords: ['devido processo legal', 'liberdade', 'bens', 'garantia processual'],
        uso: 'Princípio do devido processo legal.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-5-LV',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 5º, LV',
        texto: 'Aos litigantes, em processo judicial ou administrativo, e aos acusados em geral são assegurados o contraditório e ampla defesa, com os meios e recursos a ela inerentes.',
        area: ['constitucional', 'processual'],
        keywords: ['contraditório', 'ampla defesa', 'litigante', 'recurso', 'garantia'],
        uso: 'Princípios do contraditório e da ampla defesa.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-6',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 6º',
        texto: 'São direitos sociais a educação, a saúde, a alimentação, o trabalho, a moradia, o transporte, o lazer, a segurança, a previdência social, a proteção à maternidade e à infância, a assistência aos desamparados.',
        area: ['constitucional', 'trabalhista'],
        keywords: ['direitos sociais', 'educação', 'saúde', 'trabalho', 'moradia', 'previdência'],
        uso: 'Rol de direitos sociais — base para ações sobre políticas públicas.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-7',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 7º',
        texto: 'São direitos dos trabalhadores urbanos e rurais, além de outros que visem à melhoria de sua condição social: I - relação de emprego protegida contra despedida arbitrária ou sem justa causa; (...) XIII - duração do trabalho normal não superior a oito horas diárias e quarenta e quatro semanais; (...) XVI - remuneração do serviço extraordinário superior, no mínimo, em cinquenta por cento à do normal.',
        area: ['trabalhista', 'constitucional'],
        keywords: ['direitos trabalhadores', 'jornada', 'horas extras', 'FGTS', 'férias', '13º', 'salário mínimo'],
        uso: 'Direitos dos trabalhadores — fundamento constitucional de ações trabalhistas.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-37',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 37, caput',
        texto: 'A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.',
        area: ['administrativo', 'constitucional'],
        keywords: ['administração pública', 'legalidade', 'impessoalidade', 'moralidade', 'publicidade', 'eficiência', 'LIMPE'],
        uso: 'Princípios da Administração Pública (LIMPE).',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-93-IX',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 93, IX',
        texto: 'Todos os julgamentos dos órgãos do Poder Judiciário serão públicos, e fundamentadas todas as decisões, sob pena de nulidade.',
        area: ['processual', 'constitucional'],
        keywords: ['fundamentação', 'decisão', 'nulidade', 'publicidade', 'julgamento'],
        uso: 'Dever de fundamentação das decisões judiciais.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CF-114',
        lei: 'CF',
        leiCompleta: 'Constituição Federal de 1988',
        artigo: 'Art. 114',
        texto: 'Compete à Justiça do Trabalho processar e julgar: I - as ações oriundas da relação de trabalho, abrangidos os entes de direito público externo e da administração pública direta e indireta da União, dos Estados, do Distrito Federal e dos Municípios.',
        area: ['trabalhista', 'processual'],
        keywords: ['competência', 'justiça do trabalho', 'relação de trabalho', 'jurisdição'],
        uso: 'Competência material da Justiça do Trabalho.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },

    // ── CLT ──────────────────────────────────────────────────────────
    {
        id: 'CLT-2',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 2º',
        texto: 'Considera-se empregador a empresa, individual ou coletiva, que, assumindo os riscos da atividade econômica, admite, assalaria e dirige a prestação pessoal de serviço.',
        area: ['trabalhista'],
        keywords: ['empregador', 'empresa', 'risco', 'atividade econômica', 'alteridade'],
        uso: 'Definição de empregador e princípio da alteridade.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-3',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 3º',
        texto: 'Considera-se empregado toda pessoa física que prestar serviços de natureza não eventual a empregador, sob a dependência deste e mediante salário.',
        area: ['trabalhista'],
        keywords: ['empregado', 'vínculo', 'pessoa física', 'subordinação', 'não eventual', 'salário', 'pessoalidade'],
        uso: 'Requisitos do vínculo empregatício — pessoalidade, habitualidade, subordinação, onerosidade.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-59',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 59',
        texto: 'A duração diária do trabalho poderá ser acrescida de horas extras, em número não excedente de duas, por acordo individual, convenção coletiva ou acordo coletivo de trabalho.',
        area: ['trabalhista'],
        keywords: ['horas extras', 'jornada', 'limite', 'duas horas', 'acordo'],
        uso: 'Limite de 2 horas extras diárias e formas de pactuação.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-71',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 71',
        texto: 'Em qualquer trabalho contínuo, cuja duração exceda de 6 horas, é obrigatória a concessão de um intervalo para repouso ou alimentação, o qual será, no mínimo, de 1 hora e, salvo acordo escrito ou contrato coletivo em contrário, não poderá exceder de 2 horas.',
        area: ['trabalhista'],
        keywords: ['intervalo', 'intrajornada', 'repouso', 'alimentação', '1 hora', '6 horas'],
        uso: 'Intervalo intrajornada obrigatório — mínimo 1h para jornada acima de 6h.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-457',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 457',
        texto: 'Compreendem-se na remuneração do empregado, para todos os efeitos legais, além do salário devido e pago diretamente pelo empregador, como contraprestação do serviço, as gorjetas que receber.',
        area: ['trabalhista'],
        keywords: ['remuneração', 'salário', 'gorjeta', 'contraprestação', 'composição salarial'],
        uso: 'Composição da remuneração — salário + gorjetas.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-461',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 461',
        texto: 'Sendo idêntica a função, a todo trabalho de igual valor, prestado ao mesmo empregador, no mesmo estabelecimento empresarial, corresponderá igual salário, sem distinção de sexo, etnia, nacionalidade ou idade.',
        area: ['trabalhista'],
        keywords: ['equiparação salarial', 'igual valor', 'isonomia', 'salário', 'paradigma'],
        uso: 'Equiparação salarial — requisitos de função idêntica e igual valor.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-477',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 477',
        texto: 'Na extinção do contrato de trabalho, o empregador deverá proceder à anotação na Carteira de Trabalho e Previdência Social, comunicar a dispensa aos órgãos competentes e realizar o pagamento das verbas rescisórias no prazo de dez dias contados a partir do término do contrato.',
        area: ['trabalhista'],
        keywords: ['rescisão', 'verbas rescisórias', 'prazo', 'dez dias', 'CTPS', 'multa'],
        uso: 'Prazo e obrigações na rescisão do contrato de trabalho.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-482',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 482',
        texto: 'Constituem justa causa para rescisão do contrato de trabalho pelo empregador: a) ato de improbidade; b) incontinência de conduta ou mau procedimento; c) negociação habitual; d) condenação criminal; e) desídia; f) embriaguez habitual ou em serviço; g) violação de segredo; h) ato de indisciplina ou de insubordinação; i) abandono de emprego; j) ato lesivo da honra; k) prática de jogos de azar; l) perda da habilitação profissional.',
        area: ['trabalhista'],
        keywords: ['justa causa', 'rescisão', 'improbidade', 'desídia', 'abandono', 'insubordinação'],
        uso: 'Hipóteses de justa causa para dispensa pelo empregador.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-483',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 483',
        texto: 'O empregado poderá considerar rescindido o contrato e pleitear a devida indenização quando: a) forem exigidos serviços superiores às suas forças; b) for tratado pelo empregador ou superiores com rigor excessivo; c) correr perigo manifesto de mal considerável; d) não cumprir o empregador as obrigações do contrato; e) praticar o empregador ato lesivo da honra contra o empregado ou sua família; f) o empregador reduzir o trabalho, sendo este por peça ou tarefa.',
        area: ['trabalhista'],
        keywords: ['rescisão indireta', 'justa causa empregador', 'indenização', 'rigor excessivo', 'obrigações'],
        uso: 'Hipóteses de rescisão indireta (justa causa do empregador).',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CLT-789',
        lei: 'CLT',
        leiCompleta: 'Consolidação das Leis do Trabalho',
        artigo: 'Art. 11',
        texto: 'A pretensão quanto a créditos resultantes das relações de trabalho prescreve em cinco anos para os trabalhadores urbanos e rurais, até o limite de dois anos após a extinção do contrato de trabalho.',
        area: ['trabalhista'],
        keywords: ['prescrição', 'cinco anos', 'dois anos', 'créditos', 'extinção do contrato'],
        uso: 'Prazos prescricionais trabalhistas — 5 anos (durante contrato) e 2 anos (após extinção).',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },

    // ── CPC ──────────────────────────────────────────────────────────
    {
        id: 'CPC-300',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 300',
        texto: 'A tutela de urgência será concedida quando houver elementos que evidenciem a probabilidade do direito e o perigo de dano ou o risco ao resultado útil do processo.',
        area: ['processual'],
        keywords: ['tutela de urgência', 'liminar', 'probabilidade do direito', 'perigo de dano', 'antecipação'],
        uso: 'Requisitos para concessão de tutela de urgência (liminar).',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-335',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 335',
        texto: 'O réu poderá oferecer contestação, por petição, no prazo de 15 dias, cujo termo inicial será a data: I - da audiência de conciliação ou de mediação; II - do protocolo do pedido de cancelamento da audiência de conciliação ou de mediação; III - da última citação, quando houver litisconsórcio passivo.',
        area: ['processual'],
        keywords: ['contestação', 'prazo', '15 dias', 'réu', 'citação', 'audiência'],
        uso: 'Prazo para contestação — 15 dias a partir da audiência ou citação.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-373',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 373',
        texto: 'O ônus da prova incumbe: I - ao autor, quanto ao fato constitutivo de seu direito; II - ao réu, quanto à existência de fato impeditivo, modificativo ou extintivo do direito do autor.',
        area: ['processual'],
        keywords: ['ônus da prova', 'autor', 'réu', 'fato constitutivo', 'fato impeditivo'],
        uso: 'Distribuição do ônus da prova entre autor e réu.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-497',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 497',
        texto: 'Na ação que tenha por objeto a prestação de fazer ou de não fazer, o juiz, se procedente o pedido, concederá a tutela específica ou determinará providências que assegurem a obtenção de tutela pelo resultado prático equivalente.',
        area: ['processual'],
        keywords: ['tutela específica', 'obrigação de fazer', 'obrigação de não fazer', 'resultado prático'],
        uso: 'Tutela específica para obrigações de fazer/não fazer.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-523',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 523',
        texto: 'No caso de condenação em quantia certa, ou já fixada em liquidação, e no caso de decisão sobre parcela incontroversa, o executado será intimado para pagar o débito, no prazo de 15 dias, acrescido de custas, se houver. § 1º Não ocorrendo pagamento voluntário no prazo do caput, o débito será acrescido de multa de dez por cento e, também, de honorários de advogado de dez por cento.',
        area: ['processual'],
        keywords: ['cumprimento de sentença', 'pagamento', '15 dias', 'multa 10%', 'honorários'],
        uso: 'Cumprimento de sentença — prazo de 15 dias + multa de 10% + honorários.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-805',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 805',
        texto: 'Quando por vários meios o exequente puder promover a execução, o juiz mandará que se faça pelo modo menos gravoso para o executado.',
        area: ['processual'],
        keywords: ['execução', 'menor onerosidade', 'executado', 'meio menos gravoso'],
        uso: 'Princípio da menor onerosidade na execução.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-833',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 833',
        texto: 'São impenhoráveis: IV - os vencimentos, os subsídios, os soldos, os salários, as remunerações, os proventos de aposentadoria, as pensões, os pecúlios e os montepios, bem como as quantias recebidas por liberalidade de terceiro e destinadas ao sustento do devedor e de sua família.',
        area: ['processual', 'trabalhista'],
        keywords: ['impenhorabilidade', 'salário', 'vencimentos', 'aposentadoria', 'pensão'],
        uso: 'Impenhorabilidade de salários e vencimentos.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-966',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 966',
        texto: 'A decisão de mérito, transitada em julgado, pode ser rescindida quando: I - se verificar que foi proferida por força de prevaricação, concussão ou corrupção do juiz; II - for proferida por juiz impedido ou por juízo absolutamente incompetente; III - resultar de dolo ou coação da parte vencedora em detrimento da parte vencida; VII - obtiver o autor, posteriormente ao trânsito em julgado, prova nova.',
        area: ['processual'],
        keywords: ['ação rescisória', 'trânsito em julgado', 'rescisão', 'coisa julgada', 'prova nova'],
        uso: 'Hipóteses de cabimento da ação rescisória.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-1009',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 1.009',
        texto: 'Da sentença cabe apelação. § 1º As questões resolvidas na fase de conhecimento, se a decisão a seu respeito não comportar agravo de instrumento, não são cobertas pela preclusão e devem ser suscitadas em preliminar de apelação, eventualmente interposta contra a decisão final, ou nas contrarrazões.',
        area: ['processual'],
        keywords: ['apelação', 'sentença', 'recurso', 'preliminar', 'preclusão'],
        uso: 'Cabimento da apelação e questões a serem suscitadas em preliminar.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-1015',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 1.015',
        texto: 'Cabe agravo de instrumento contra as decisões interlocutórias que versarem sobre: I - tutelas provisórias; II - mérito do processo; III - rejeição da alegação de convenção de arbitragem; (...) XIII - outros casos expressamente referidos em lei.',
        area: ['processual'],
        keywords: ['agravo de instrumento', 'decisão interlocutória', 'tutela provisória', 'cabimento'],
        uso: 'Hipóteses de cabimento do agravo de instrumento.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CPC-1022',
        lei: 'CPC',
        leiCompleta: 'Código de Processo Civil',
        artigo: 'Art. 1.022',
        texto: 'Cabem embargos de declaração contra qualquer decisão judicial para: I - esclarecer obscuridade ou eliminar contradição; II - suprir omissão de ponto ou questão sobre o qual devia se pronunciar o juiz de ofício ou a requerimento; III - corrigir erro material.',
        area: ['processual'],
        keywords: ['embargos de declaração', 'obscuridade', 'contradição', 'omissão', 'erro material'],
        uso: 'Cabimento dos embargos de declaração.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },

    // ── CDC ──────────────────────────────────────────────────────────
    {
        id: 'CDC-2',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 2º',
        texto: 'Consumidor é toda pessoa física ou jurídica que adquire ou utiliza produto ou serviço como destinatário final.',
        area: ['consumidor'],
        keywords: ['consumidor', 'destinatário final', 'pessoa física', 'pessoa jurídica'],
        uso: 'Definição legal de consumidor.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-6',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 6º',
        texto: 'São direitos básicos do consumidor: I - proteção da vida, saúde e segurança; III - informação adequada; IV - proteção contra publicidade enganosa; V - modificação de cláusulas contratuais que estabeleçam prestações desproporcionais; VI - efetiva prevenção e reparação de danos; VIII - facilitação da defesa de seus direitos, inclusive com a inversão do ônus da prova.',
        area: ['consumidor'],
        keywords: ['direitos do consumidor', 'inversão ônus', 'informação', 'publicidade enganosa', 'cláusula abusiva'],
        uso: 'Direitos básicos do consumidor — inclui inversão do ônus da prova.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-12',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 12',
        texto: 'O fabricante, o produtor, o construtor, nacional ou estrangeiro, e o importador respondem, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos decorrentes de projeto, fabricação, construção, montagem, fórmulas, manipulação, apresentação ou acondicionamento de seus produtos, bem como por informações insuficientes ou inadequadas sobre sua utilização e riscos.',
        area: ['consumidor'],
        keywords: ['responsabilidade objetiva', 'fabricante', 'defeito', 'produto', 'culpa'],
        uso: 'Responsabilidade objetiva do fabricante por defeito do produto.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-14',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 14',
        texto: 'O fornecedor de serviços responde, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos relativos à prestação dos serviços, bem como por informações insuficientes ou inadequadas sobre sua fruição e riscos.',
        area: ['consumidor'],
        keywords: ['responsabilidade objetiva', 'fornecedor', 'serviço', 'defeito', 'reparação'],
        uso: 'Responsabilidade objetiva do fornecedor por defeito do serviço.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-18',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 18',
        texto: 'Os fornecedores de produtos de consumo duráveis ou não duráveis respondem solidariamente pelos vícios de qualidade ou quantidade que os tornem impróprios ou inadequados ao consumo a que se destinam ou lhes diminuam o valor. Não sendo o vício sanado no prazo máximo de trinta dias, pode o consumidor exigir, alternativamente e à sua escolha: I - a substituição do produto; II - a restituição da quantia paga; III - o abatimento proporcional do preço.',
        area: ['consumidor'],
        keywords: ['vício', 'produto', 'trinta dias', 'substituição', 'restituição', 'abatimento'],
        uso: 'Responsabilidade solidária por vícios do produto — prazo de 30 dias para sanar.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-26',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 26',
        texto: 'O direito de reclamar pelos vícios aparentes ou de fácil constatação caduca em: I - trinta dias, tratando-se de fornecimento de serviço e de produtos não duráveis; II - noventa dias, tratando-se de fornecimento de serviço e de produtos duráveis.',
        area: ['consumidor'],
        keywords: ['decadência', 'vício', '30 dias', '90 dias', 'prazo', 'reclamação'],
        uso: 'Prazos decadenciais para reclamar vícios — 30 dias (não durável) e 90 dias (durável).',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-39',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 39',
        texto: 'É vedado ao fornecedor de produtos ou serviços, dentre outras práticas abusivas: I - condicionar o fornecimento de produto ou de serviço ao fornecimento de outro produto ou serviço (venda casada); V - exigir do consumidor vantagem manifestamente excessiva; X - elevar sem justa causa o preço de produtos ou serviços.',
        area: ['consumidor'],
        keywords: ['prática abusiva', 'venda casada', 'vantagem excessiva', 'preço abusivo'],
        uso: 'Rol de práticas abusivas vedadas ao fornecedor.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'CDC-49',
        lei: 'CDC',
        leiCompleta: 'Código de Defesa do Consumidor',
        artigo: 'Art. 49',
        texto: 'O consumidor pode desistir do contrato, no prazo de 7 dias a contar de sua assinatura ou do ato de recebimento do produto ou serviço, sempre que a contratação de fornecimento de produtos e serviços ocorrer fora do estabelecimento comercial, especialmente por telefone ou a domicílio.',
        area: ['consumidor'],
        keywords: ['arrependimento', '7 dias', 'desistência', 'compra online', 'fora do estabelecimento'],
        uso: 'Direito de arrependimento — 7 dias para compras fora do estabelecimento.',
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
];

// ═══════════════════════════════════════════════════════════════════════
// TESES JURÍDICAS — as mais universais (~20)
// ═══════════════════════════════════════════════════════════════════════

export const SEED_THESES: StoredThesis[] = [
    {
        id: 'trab-horas-extras-habituais',
        nome: 'Horas extras habituais',
        area: 'trabalhista',
        descricao: 'Empregado que prestava horas extras com habitualidade e teve as horas suprimidas pelo empregador tem direito a indenização pela supressão, nos termos da Súmula 291 do TST.',
        fundamentoLegal: ['Art. 59 CLT', 'Art. 7º XVI CF', 'Súmula 291 TST', 'Súmula 85 TST'],
        argumentacao: 'O empregado prestou horas extras habituais durante o período contratual, conforme demonstram os cartões de ponto. A habitualidade das horas extras incorporou-se ao patrimônio jurídico do trabalhador, gerando expectativa legítima de manutenção. A supressão total ou parcial das horas extras habituais, nos termos da Súmula 291 do TST, gera direito à indenização correspondente ao valor de 1 mês das horas suprimidas para cada ano ou fração igual ou superior a 6 meses.',
        quantumUsual: '1 mês de horas suprimidas por ano de serviço',
        keywords: ['horas extras', 'habitualidade', 'supressão', 'indenização', 'jornada extraordinária'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-vinculo-empregaticio',
        nome: 'Reconhecimento de vínculo empregatício',
        area: 'trabalhista',
        descricao: 'Pedido de reconhecimento de vínculo empregatício quando presentes os requisitos do art. 3º da CLT: pessoalidade, habitualidade, subordinação e onerosidade.',
        fundamentoLegal: ['Art. 2º CLT', 'Art. 3º CLT', 'Art. 9º CLT', 'Súmula 212 TST'],
        argumentacao: 'O reclamante prestou serviços ao reclamado com todos os requisitos caracterizadores da relação de emprego: pessoalidade (trabalho executado pessoalmente), habitualidade (prestação de serviço contínua e não eventual), subordinação jurídica (ordens e controle do empregador) e onerosidade (contraprestação pecuniária). A ausência de registro em CTPS não afasta o vínculo, configurando fraude aos direitos trabalhistas nos termos do art. 9º da CLT.',
        keywords: ['vínculo', 'emprego', 'CLT', 'subordinação', 'pessoalidade', 'habitualidade', 'PJ', 'pejotização'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-rescisao-indireta',
        nome: 'Rescisão indireta do contrato de trabalho',
        area: 'trabalhista',
        descricao: 'O empregado pode considerar rescindido o contrato quando o empregador descumpre obrigações contratuais ou legais, nos termos do art. 483 da CLT.',
        fundamentoLegal: ['Art. 483 CLT', 'Art. 477 CLT', 'Art. 484 CLT'],
        argumentacao: 'O empregador descumpriu gravemente suas obrigações contratuais, configurando as hipóteses do art. 483 da CLT. O descumprimento reiterado do contrato de trabalho (atraso reiterado de salários, não recolhimento de FGTS, condições de trabalho inadequadas) constitui falta grave do empregador que autoriza a rescisão indireta, com pagamento de todas as verbas rescisórias como se dispensa sem justa causa fosse.',
        quantumUsual: 'Todas as verbas de dispensa sem justa causa + multa de 40% FGTS',
        keywords: ['rescisão indireta', 'justa causa empregador', 'falta grave', 'descumprimento', 'atraso salário'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-dano-moral-trabalhista',
        nome: 'Dano moral na relação de trabalho',
        area: 'trabalhista',
        descricao: 'Indenização por dano moral decorrente de condutas abusivas do empregador que violam a dignidade, honra ou integridade psicológica do empregado.',
        fundamentoLegal: ['Art. 5º V e X CF', 'Art. 186 CC', 'Art. 927 CC', 'Art. 223-A a 223-G CLT'],
        argumentacao: 'O empregador praticou conduta ilícita que causou lesão à dignidade, honra e integridade psicológica do empregado, configurando dano moral passível de reparação. A conduta patronal excedeu os limites do poder diretivo, caracterizando abuso de direito. Os arts. 223-A a 223-G da CLT estabelecem os parâmetros para fixação da indenização, devendo ser observada a natureza do bem jurídico tutelado, a extensão do dano e a capacidade econômica das partes.',
        quantumUsual: '5 a 50 salários do ofendido (parâmetro CLT art. 223-G)',
        keywords: ['dano moral', 'assédio', 'dignidade', 'honra', 'indenização', 'abuso', 'humilhação'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-adicional-insalubridade',
        nome: 'Adicional de insalubridade',
        area: 'trabalhista',
        descricao: 'Empregado exposto a agentes nocivos acima dos limites de tolerância faz jus ao adicional de insalubridade.',
        fundamentoLegal: ['Art. 189 CLT', 'Art. 190 CLT', 'Art. 192 CLT', 'NR-15'],
        argumentacao: 'O empregado esteve exposto a agentes nocivos à saúde acima dos limites de tolerância fixados pelo Ministério do Trabalho (NR-15), sem fornecimento de EPIs adequados ou eficazes para neutralizar a insalubridade. Nos termos do art. 192 da CLT, faz jus ao adicional de insalubridade no grau correspondente à exposição (10%, 20% ou 40% do salário mínimo).',
        quantumUsual: '10%, 20% ou 40% do salário mínimo (conforme grau)',
        keywords: ['insalubridade', 'adicional', 'agente nocivo', 'EPI', 'NR-15', 'saúde'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-intervalo-intrajornada',
        nome: 'Supressão do intervalo intrajornada',
        area: 'trabalhista',
        descricao: 'A não concessão ou concessão parcial do intervalo intrajornada gera o dever de pagar o período suprimido com acréscimo de 50% sobre o valor da hora normal.',
        fundamentoLegal: ['Art. 71 CLT', 'Art. 71 §4º CLT', 'Súmula 437 TST'],
        argumentacao: 'O empregador não concedeu integralmente o intervalo intrajornada mínimo de 1 hora previsto no art. 71 da CLT para jornadas superiores a 6 horas. A supressão total ou parcial do intervalo obriga ao pagamento do período suprimido com acréscimo de 50% sobre o valor da remuneração da hora normal de trabalho, com natureza indenizatória (§4º do art. 71 CLT, com redação dada pela Reforma Trabalhista).',
        quantumUsual: 'Hora cheia + 50% de adicional por dia de supressão',
        keywords: ['intervalo', 'intrajornada', 'hora de almoço', 'supressão', 'repouso'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'civil-dano-moral-consumidor',
        nome: 'Dano moral nas relações de consumo',
        area: 'consumidor',
        descricao: 'Indenização por dano moral decorrente de falha na prestação de serviço ou vício de produto que cause abalo moral ao consumidor.',
        fundamentoLegal: ['Art. 6º VI CDC', 'Art. 12 CDC', 'Art. 14 CDC', 'Art. 186 CC', 'Súmula 227 STJ'],
        argumentacao: 'O fornecedor causou dano moral ao consumidor em razão de falha na prestação de serviço/vício do produto. A responsabilidade é objetiva, nos termos dos arts. 12 e 14 do CDC, dispensando prova de culpa. O dano moral in re ipsa dispensa comprovação de prejuízo, bastando a demonstração do fato lesivo. A indenização deve observar o caráter compensatório e pedagógico, levando em conta a extensão do dano e a capacidade econômica do ofensor.',
        quantumUsual: 'R$ 5.000 a R$ 30.000 (parâmetro jurisprudencial para consumidor PF)',
        keywords: ['dano moral', 'consumidor', 'falha', 'serviço', 'produto', 'responsabilidade objetiva'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'civil-negativacao-indevida',
        nome: 'Negativação indevida em cadastro de crédito',
        area: 'consumidor',
        descricao: 'Inscrição indevida em cadastro de restrição ao crédito (SPC/Serasa) gera dano moral presumido, passível de indenização.',
        fundamentoLegal: ['Art. 43 CDC', 'Art. 186 CC', 'Art. 927 CC', 'Súmula 385 STJ', 'Súmula 548 STJ'],
        argumentacao: 'O réu inscreveu indevidamente o nome do autor em cadastro de proteção ao crédito, sem que houvesse dívida legítima ou após seu pagamento. A negativação indevida causa dano moral in re ipsa, presumido pela simples inscrição irregular, conforme jurisprudência consolidada. Após o pagamento, incumbe ao credor a exclusão do registro (Súmula 548 STJ).',
        quantumUsual: 'R$ 5.000 a R$ 20.000',
        keywords: ['negativação', 'SPC', 'Serasa', 'cadastro', 'crédito', 'inscrição indevida', 'dano moral'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'civil-revisao-contratual',
        nome: 'Revisão de cláusulas contratuais abusivas',
        area: 'consumidor',
        descricao: 'Revisão judicial de cláusulas contratuais abusivas em contratos de adesão, especialmente bancários e financeiros.',
        fundamentoLegal: ['Art. 6º V CDC', 'Art. 39 CDC', 'Art. 51 CDC', 'Súmula 297 STJ', 'Súmula 379 STJ'],
        argumentacao: 'O contrato celebrado entre as partes contém cláusulas que estabelecem prestações desproporcionais e abusivas, em afronta ao art. 51 do CDC. O consumidor tem direito à modificação das cláusulas que estabeleçam obrigações excessivamente onerosas (art. 6º V CDC). Os juros remuneratórios devem observar a taxa média de mercado divulgada pelo BACEN, e os moratórios limitam-se a 1% ao mês (Súmula 379 STJ).',
        keywords: ['revisão contratual', 'cláusula abusiva', 'juros', 'banco', 'contrato adesão', 'onerosidade'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'civil-responsabilidade-objetiva-banco',
        nome: 'Responsabilidade objetiva de instituição financeira',
        area: 'consumidor',
        descricao: 'Banco responde objetivamente por danos causados por fraudes e falhas de segurança em operações bancárias.',
        fundamentoLegal: ['Art. 14 CDC', 'Súmula 297 STJ', 'Súmula 479 STJ'],
        argumentacao: 'A instituição financeira responde objetivamente pelos danos gerados por fortuito interno relativo a fraudes e delitos praticados por terceiros no âmbito de operações bancárias (Súmula 479 STJ). O CDC é plenamente aplicável às instituições financeiras (Súmula 297 STJ). A falha de segurança nos sistemas bancários constitui defeito do serviço (art. 14 CDC), independendo de culpa para gerar dever de reparação.',
        quantumUsual: 'Dano material integral + dano moral R$ 5.000 a R$ 15.000',
        keywords: ['banco', 'fraude', 'PIX', 'golpe', 'responsabilidade objetiva', 'segurança', 'fortuito interno'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'proc-tutela-urgencia',
        nome: 'Tutela de urgência antecipada',
        area: 'processual',
        descricao: 'Requerimento de tutela de urgência antecipada quando presentes probabilidade do direito e perigo de dano.',
        fundamentoLegal: ['Art. 300 CPC', 'Art. 303 CPC', 'Art. 304 CPC'],
        argumentacao: 'Estão presentes os requisitos para concessão da tutela de urgência antecipada: (i) probabilidade do direito, demonstrada pela documentação acostada que evidencia a verossimilhança das alegações; (ii) perigo de dano ou risco ao resultado útil do processo, haja vista que a demora na prestação jurisdicional causará prejuízo irreparável ou de difícil reparação ao autor.',
        keywords: ['tutela', 'urgência', 'liminar', 'antecipação', 'perigo de dano', 'probabilidade do direito'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'proc-honorarios-sucumbencia',
        nome: 'Honorários advocatícios sucumbenciais',
        area: 'processual',
        descricao: 'Fixação de honorários advocatícios de sucumbência nos termos do art. 85 do CPC.',
        fundamentoLegal: ['Art. 85 CPC', 'Art. 86 CPC', 'Súmula 326 STJ'],
        argumentacao: 'Os honorários advocatícios de sucumbência devem ser fixados entre 10% e 20% sobre o valor da condenação, do proveito econômico ou, não sendo possível mensurá-lo, sobre o valor atualizado da causa (art. 85 §2º CPC). Na fixação, devem ser observados o grau de zelo do profissional, o lugar da prestação do serviço, a natureza e importância da causa, o trabalho realizado pelo advogado e o tempo exigido para o serviço.',
        keywords: ['honorários', 'sucumbência', 'advogado', 'condenação', 'percentual'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'proc-justica-gratuita',
        nome: 'Concessão de justiça gratuita',
        area: 'processual',
        descricao: 'Pedido de concessão do benefício da justiça gratuita para parte que não pode arcar com custas processuais sem prejuízo do sustento próprio ou familiar.',
        fundamentoLegal: ['Art. 5º LXXIV CF', 'Art. 98 CPC', 'Art. 99 CPC'],
        argumentacao: 'A parte requerente não possui condições financeiras de arcar com as despesas processuais sem prejuízo do sustento próprio ou de sua família. Nos termos do art. 99 §3º do CPC, presume-se verdadeira a alegação de insuficiência de recursos quando deduzida por pessoa natural. O benefício compreende custas, despesas processuais, honorários periciais e demais taxas judiciárias.',
        keywords: ['justiça gratuita', 'gratuidade', 'custas', 'hipossuficiência', 'AJG'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-assedio-moral',
        nome: 'Assédio moral no trabalho',
        area: 'trabalhista',
        descricao: 'Indenização por assédio moral no ambiente de trabalho, caracterizado pela exposição reiterada a situações humilhantes e constrangedoras.',
        fundamentoLegal: ['Art. 1º III CF', 'Art. 5º V e X CF', 'Art. 186 CC', 'Art. 927 CC', 'Art. 223-B CLT'],
        argumentacao: 'O empregado foi submetido a condutas reiteradas e prolongadas do empregador ou seus prepostos que atentaram contra sua dignidade, integridade psíquica e moral. O assédio moral se caracteriza pela exposição repetitiva a situações humilhantes, constrangedoras e vexatórias durante a jornada de trabalho, causando grave abalo emocional e psicológico. A conduta constitui ato ilícito gerador de dano moral passível de reparação.',
        quantumUsual: '10 a 50 salários (conforme gravidade e duração)',
        keywords: ['assédio moral', 'humilhação', 'constrangimento', 'dignidade', 'ambiente de trabalho', 'mobbing'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-acidente-trabalho',
        nome: 'Indenização por acidente de trabalho',
        area: 'trabalhista',
        descricao: 'Reparação por danos materiais e morais decorrentes de acidente de trabalho ou doença ocupacional.',
        fundamentoLegal: ['Art. 7º XXVIII CF', 'Art. 927 CC', 'Art. 186 CC', 'Súmula 229 STF'],
        argumentacao: 'O empregado sofreu acidente de trabalho/doença ocupacional decorrente das condições de trabalho, resultando em lesão à sua integridade física. O empregador é responsável pela reparação dos danos, eis que concorreu com culpa (negligência na fiscalização de normas de segurança, não fornecimento de EPIs adequados ou treinamento). São devidos: danos materiais (despesas médicas, lucros cessantes, pensionamento) e danos morais pela violação à integridade física.',
        quantumUsual: 'Dano material integral + pensionamento vitalício + dano moral R$ 20.000 a R$ 200.000',
        keywords: ['acidente de trabalho', 'doença ocupacional', 'indenização', 'EPI', 'segurança', 'lesão'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'trab-desvio-funcao',
        nome: 'Desvio de função e diferenças salariais',
        area: 'trabalhista',
        descricao: 'Empregado que exerce função diversa da contratada faz jus às diferenças salariais correspondentes.',
        fundamentoLegal: ['Art. 456 CLT', 'Art. 461 CLT', 'Art. 468 CLT'],
        argumentacao: 'O empregado foi contratado para exercer determinada função, mas passou a desempenhar atividades de maior complexidade e responsabilidade sem a correspondente alteração salarial. O desvio funcional configura alteração unilateral lesiva do contrato de trabalho, vedada pelo art. 468 da CLT. São devidas as diferenças salariais entre a remuneração percebida e a que corresponderia à função efetivamente exercida.',
        quantumUsual: 'Diferenças salariais + reflexos em verbas trabalhistas',
        keywords: ['desvio de função', 'diferenças salariais', 'equiparação', 'função', 'cargo'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'civil-prescricao',
        nome: 'Prescrição e decadência',
        area: 'civil',
        descricao: 'Arguição de prescrição ou decadência como matéria de defesa, podendo ser reconhecida de ofício pelo juiz.',
        fundamentoLegal: ['Art. 189 CC', 'Art. 206 CC', 'Art. 332 CPC', 'Art. 487 II CPC'],
        argumentacao: 'O direito de ação do autor encontra-se fulminado pela prescrição, nos termos do art. 206 do Código Civil. O prazo prescricional aplicável é de [3/5/10] anos, contados da data em que o titular tomou conhecimento da violação de seu direito. A prescrição atinge a pretensão (ação) e pode ser reconhecida de ofício pelo juiz (art. 332 §1º CPC), ensejando resolução do mérito (art. 487 II CPC).',
        keywords: ['prescrição', 'decadência', 'prazo', 'defesa', 'extinção', 'matéria de ordem pública'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'admin-improbidade',
        nome: 'Ato de improbidade administrativa',
        area: 'administrativo',
        descricao: 'Ação de improbidade administrativa por atos que importem enriquecimento ilícito, prejuízo ao erário ou violação dos princípios da administração.',
        fundamentoLegal: ['Art. 37 §4º CF', 'Lei 8.429/92', 'Lei 14.230/2021'],
        argumentacao: 'O agente público praticou ato de improbidade administrativa que se enquadra nas hipóteses da Lei 8.429/92. Com a reforma promovida pela Lei 14.230/2021, exige-se dolo específico para configuração do ato ímprobo. As sanções aplicáveis incluem perda da função pública, suspensão dos direitos políticos, multa civil e ressarcimento integral do dano.',
        keywords: ['improbidade', 'administração pública', 'enriquecimento ilícito', 'erário', 'agente público'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'civil-obrigacao-fazer',
        nome: 'Obrigação de fazer/não fazer com astreintes',
        area: 'processual',
        descricao: 'Pedido de tutela específica para obrigação de fazer ou não fazer com fixação de multa diária (astreintes).',
        fundamentoLegal: ['Art. 497 CPC', 'Art. 536 CPC', 'Art. 537 CPC'],
        argumentacao: 'Requer-se a concessão de tutela específica para que o réu cumpra a obrigação de fazer/não fazer, com fixação de multa diária (astreintes) em caso de descumprimento, nos termos do art. 537 do CPC. A multa deve ser fixada em valor suficiente para compelir o devedor ao cumprimento, observando-se a proporcionalidade e razoabilidade.',
        quantumUsual: 'Multa diária de R$ 500 a R$ 5.000 (conforme complexidade)',
        keywords: ['obrigação de fazer', 'astreintes', 'multa diária', 'tutela específica', 'cumprimento'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
    {
        id: 'prev-aposentadoria',
        nome: 'Concessão/revisão de benefício previdenciário',
        area: 'previdenciario',
        descricao: 'Ação para concessão ou revisão de benefício previdenciário negado ou concedido com valor inferior ao devido pelo INSS.',
        fundamentoLegal: ['Art. 201 CF', 'Lei 8.213/91', 'Art. 29 Lei 8.213/91'],
        argumentacao: 'O INSS indeferiu/concedeu em valor inferior o benefício previdenciário ao qual o autor faz jus, em desconformidade com a legislação previdenciária. O tempo de contribuição e/ou a qualidade de segurado estão devidamente comprovados pela documentação acostada. A revisão do benefício deve observar os salários de contribuição corretos e o período básico de cálculo, com pagamento das diferenças retroativas desde a data do requerimento administrativo.',
        keywords: ['aposentadoria', 'INSS', 'benefício', 'previdência', 'revisão', 'concessão', 'tempo de contribuição'],
        fonte: 'seed',
        dataAtualizacao: hoje,
    },
];
