import type { LegalTerm } from './types';

/**
 * Glossário — Direito Administrativo.
 */
export const ADMINISTRATIVO: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'ato vinculado', significado: 'Ato administrativo sem margem de discricionariedade.', uso: 'A lei define todos os elementos — administrador não tem escolha.', area: ['administrativo'], exemplo: 'A concessão de aposentadoria é ato vinculado.' },
    { termo: 'ato discricionário', significado: 'Ato administrativo com margem de conveniência e oportunidade.', uso: 'Administrador escolhe dentro dos limites legais.', area: ['administrativo'], exemplo: 'A nomeação para cargo em comissão é ato discricionário.' },
    { termo: 'desvio de finalidade', significado: 'Uso do poder administrativo para fim diverso do previsto em lei.', uso: 'Vício que torna o ato administrativo nulo.', area: ['administrativo'], exemplo: 'A remoção do servidor configurou desvio de finalidade.' },
    { termo: 'processo administrativo disciplinar', significado: 'Procedimento para apurar infração funcional de servidor.', uso: 'Garantidos contraditório e ampla defesa (Lei 8.112/90).', area: ['administrativo'], sinonimos: ['PAD'], exemplo: 'O PAD foi instaurado sem observância do contraditório.' },
    { termo: 'improbidade administrativa', significado: 'Ato de agente público que viola deveres de honestidade e legalidade.', uso: 'Lei 8.429/92 — enriquecimento ilícito, prejuízo ao erário, violação de princípios.', area: ['administrativo'], exemplo: 'A conduta configura improbidade administrativa por dano ao erário.' },
    { termo: 'licitação', significado: 'Procedimento para seleção da proposta mais vantajosa à Administração.', uso: 'Obrigatória para contratos públicos (Lei 14.133/2021).', area: ['administrativo'], exemplo: 'A contratação sem licitação só é admitida nas hipóteses de dispensa ou inexigibilidade.' },
    { termo: 'mandado de segurança', significado: 'Remédio constitucional contra ato ilegal de autoridade pública.', uso: 'Exige direito líquido e certo comprovado de plano.', area: ['administrativo', 'constitucional'], exemplo: 'Impetra-se mandado de segurança com pedido de liminar.' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'poder de polícia', significado: 'Faculdade de a Administração limitar direitos individuais em prol do interesse público.', uso: 'Fundamento para fiscalização, multas e interdição (art. 78, CTN).', area: ['administrativo'], exemplo: 'O poder de polícia sanitária fundamenta a interdição do estabelecimento.' },
    { termo: 'autotutela', significado: 'Poder da Administração de anular ou revogar seus próprios atos.', uso: 'Súmula 473 do STF — independe de provocação judicial.', area: ['administrativo'], exemplo: 'A Administração exerceu a autotutela ao anular o ato viciado.' },
    { termo: 'concurso público', significado: 'Processo seletivo para provimento de cargos públicos efetivos.', uso: 'Obrigatório para a investidura em cargo ou emprego público (art. 37, II, CF).', area: ['administrativo'], exemplo: 'A nomeação sem concurso público é nula (Súmula Vinculante 13).' },
    { termo: 'estabilidade', significado: 'Garantia contra demissão imotivada do servidor público efetivo.', uso: 'Adquirida após 3 anos de efetivo exercício (art. 41, CF).', area: ['administrativo'], exemplo: 'O servidor estável só pode ser demitido após PAD com ampla defesa.' },
    { termo: 'dispensa de licitação', significado: 'Hipóteses legais em que a licitação é facultativa.', uso: 'Rol taxativo do art. 75 da Lei 14.133/2021.', area: ['administrativo'], exemplo: 'A contratação enquadra-se na dispensa de licitação por valor (art. 75, II).' },
    { termo: 'inexigibilidade de licitação', significado: 'Inviabilidade de competição que torna a licitação impossível.', uso: 'Fornecedor exclusivo, serviços técnicos singulares, artistas (art. 74, Lei 14.133).', area: ['administrativo'], exemplo: 'A inexigibilidade foi justificada pela singularidade do serviço técnico.' },
    { termo: 'contrato administrativo', significado: 'Acordo entre Administração e particular com cláusulas exorbitantes.', uso: 'Regime jurídico próprio — Administração tem prerrogativas especiais.', area: ['administrativo'], exemplo: 'O contrato administrativo prevê cláusula de rescisão unilateral.' },
    { termo: 'concessão de serviço público', significado: 'Delegação da prestação de serviço público ao particular.', uso: 'Mediante licitação e contrato administrativo (Lei 8.987/95).', area: ['administrativo'], exemplo: 'A concessão de transporte coletivo foi objeto de licitação.' },
    { termo: 'permissão de uso', significado: 'Ato unilateral e precário que autoriza uso de bem público.', uso: 'Revogável a qualquer tempo, sem direito a indenização.', area: ['administrativo'], exemplo: 'A permissão de uso do espaço público foi revogada por interesse da Administração.' },
    { termo: 'tombamento', significado: 'Restrição ao direito de propriedade para preservação do patrimônio cultural.', uso: 'Decreto-Lei 25/1937 — pode ser provisório ou definitivo.', area: ['administrativo'], exemplo: 'O tombamento do prédio histórico impede sua demolição.' },
    { termo: 'desapropriação', significado: 'Transferência compulsória da propriedade particular ao poder público.', uso: 'Mediante prévia e justa indenização em dinheiro (art. 5º, XXIV, CF).', area: ['administrativo'], exemplo: 'A desapropriação por utilidade pública foi decretada para construção de rodovia.' },
    { termo: 'servidor público', significado: 'Pessoa que mantém vínculo funcional com a Administração Pública.', uso: 'Em sentido amplo: estatutários, celetistas e temporários.', area: ['administrativo'], exemplo: 'O servidor público federal rege-se pela Lei 8.112/90.' },
    { termo: 'pregão', significado: 'Modalidade de licitação para aquisição de bens e serviços comuns.', uso: 'Pode ser eletrônico ou presencial — inversão de fases.', area: ['administrativo'], exemplo: 'O pregão eletrônico foi realizado para aquisição de material de escritório.' },
    { termo: 'ato normativo', significado: 'Ato administrativo de caráter geral e abstrato.', uso: 'Decretos regulamentares, resoluções, portarias normativas.', area: ['administrativo'], exemplo: 'O ato normativo extrapolou o poder regulamentar ao inovar na ordem jurídica.' },
    { termo: 'responsabilidade civil do Estado', significado: 'Obrigação do Estado de indenizar danos causados por seus agentes.', uso: 'Responsabilidade objetiva (art. 37, §6º, CF) — teoria do risco administrativo.', area: ['administrativo'], exemplo: 'O Estado responde objetivamente pelos danos causados pela viatura policial.' },
    { termo: 'sindicância', significado: 'Procedimento sumário para apurar irregularidades funcionais.', uso: 'Pode resultar em arquivamento, advertência, suspensão ou instauração de PAD.', area: ['administrativo'], exemplo: 'Foi instaurada sindicância para apurar a falta funcional.' },
    { termo: 'recurso administrativo', significado: 'Impugnação de decisão administrativa na via extrajudicial.', uso: 'Não exige esgotamento para acesso ao Judiciário (Súmula Vinculante 21).', area: ['administrativo'], exemplo: 'O recurso administrativo foi interposto no prazo de 10 dias.' },
];
