import type { LegalTerm } from './types';

/**
 * Glossário — Direito Ambiental.
 */
export const AMBIENTAL: LegalTerm[] = [
    { termo: 'licenciamento ambiental', significado: 'Procedimento administrativo para autorizar atividades potencialmente poluidoras.', uso: 'Fases: licença prévia, licença de instalação, licença de operação.', area: ['ambiental'], exemplo: 'O empreendimento iniciou obras sem licenciamento ambiental.' },
    { termo: 'EIA/RIMA', significado: 'Estudo de Impacto Ambiental e Relatório de Impacto sobre o Meio Ambiente.', uso: 'Exigido para atividades de significativo impacto ambiental (art. 225, §1º, IV, CF).', area: ['ambiental'], exemplo: 'O EIA/RIMA concluiu pela viabilidade ambiental do projeto.' },
    { termo: 'princípio do poluidor-pagador', significado: 'Quem polui deve arcar com os custos da prevenção e reparação do dano.', uso: 'Fundamento da responsabilidade civil ambiental.', area: ['ambiental'], exemplo: 'Em aplicação do princípio do poluidor-pagador, a empresa deve custear a descontaminação.' },
    { termo: 'princípio da precaução', significado: 'Diante de incerteza científica, adotar medidas para evitar danos ambientais.', uso: 'Justifica restrições mesmo sem prova científica conclusiva do risco.', area: ['ambiental'], exemplo: 'O princípio da precaução impõe a suspensão da atividade até avaliação completa.' },
    { termo: 'dano ambiental', significado: 'Degradação do meio ambiente natural, cultural, artificial ou do trabalho.', uso: 'Responsabilidade objetiva — independe de culpa (art. 14, §1º, Lei 6.938/81).', area: ['ambiental'], exemplo: 'O dano ambiental decorrente do vazamento exige reparação integral.' },
    { termo: 'reparação integral', significado: 'Obrigação de restaurar integralmente o meio ambiente degradado.', uso: 'In natura (recuperação) e, subsidiariamente, indenização pecuniária.', area: ['ambiental'], exemplo: 'A reparação integral exige a recomposição da vegetação nativa.' },
    { termo: 'área de preservação permanente', significado: 'Área protegida com função ambiental de preservar recursos hídricos e biodiversidade.', uso: 'Margens de rios, topos de morros, encostas (art. 3º, II, Código Florestal).', area: ['ambiental'], sinonimos: ['APP'], exemplo: 'A construção em APP é vedada, salvo exceções do art. 8º do Código Florestal.' },
    { termo: 'reserva legal', significado: 'Área do imóvel rural que deve manter cobertura vegetal nativa.', uso: '20% na regra geral, 80% na Amazônia Legal (art. 12, Código Florestal).', area: ['ambiental'], exemplo: 'A propriedade não mantém a reserva legal mínima de 20%.' },
    { termo: 'TAC', significado: 'Termo de Ajustamento de Conduta — acordo entre MP e poluidor.', uso: 'Compromisso de adequação ambiental com prazos e multas.', area: ['ambiental'], sinonimos: ['termo de ajustamento de conduta'], exemplo: 'A empresa firmou TAC com o Ministério Público para recuperação da área degradada.' },
    { termo: 'crime ambiental', significado: 'Infração penal contra o meio ambiente.', uso: 'Tipificado na Lei 9.605/98 — pessoa física e jurídica.', area: ['ambiental', 'penal'], exemplo: 'A poluição do rio configura crime ambiental (art. 54, Lei 9.605/98).' },
    { termo: 'responsabilidade ambiental solidária', significado: 'Todos os causadores do dano ambiental respondem solidariamente.', uso: 'Qualquer dos responsáveis pode ser demandado pela totalidade do dano.', area: ['ambiental'], exemplo: 'A responsabilidade ambiental é solidária entre o empreendedor e o proprietário.' },
    { termo: 'unidade de conservação', significado: 'Espaço territorial protegido por lei para conservação da biodiversidade.', uso: 'Parques, reservas, estações ecológicas (Lei 9.985/2000 — SNUC).', area: ['ambiental'], sinonimos: ['UC'], exemplo: 'A exploração dentro da unidade de conservação depende de autorização do órgão gestor.' },
    { termo: 'compensação ambiental', significado: 'Mecanismo para compensar impactos ambientais não elimináveis.', uso: 'Pode ser in natura ou pecuniária, definida no licenciamento.', area: ['ambiental'], exemplo: 'A compensação ambiental foi fixada em 0,5% do valor do empreendimento.' },
    { termo: 'IBAMA', significado: 'Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis.', uso: 'Órgão federal de execução da política ambiental.', area: ['ambiental'], exemplo: 'O IBAMA lavrou auto de infração por desmatamento ilegal.' },
    { termo: 'desenvolvimento sustentável', significado: 'Desenvolvimento que satisfaz necessidades presentes sem comprometer gerações futuras.', uso: 'Princípio constitucional do art. 225, caput, CF.', area: ['ambiental'], exemplo: 'O projeto deve atender ao princípio do desenvolvimento sustentável.' },
];
