import type { LegalTerm } from './types';

/**
 * Glossário — Direito Civil.
 */
export const CIVIL: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'usucapião', significado: 'Aquisição da propriedade pela posse prolongada.', uso: 'Modalidades: ordinária, extraordinária, especial urbana/rural.', area: ['civil'], exemplo: 'Requer-se a declaração de usucapião extraordinária (art. 1.238, CC).' },
    { termo: 'inadimplemento', significado: 'Descumprimento de obrigação contratual.', uso: 'Quando a parte não cumpre o que foi pactuado.', area: ['civil'], sinonimos: ['descumprimento', 'inadimplência'], exemplo: 'O inadimplemento contratual autoriza a resolução do contrato.' },
    { termo: 'enriquecimento sem causa', significado: 'Aumento patrimonial injustificado à custa de outrem.', uso: 'Vedado pelo art. 884 do Código Civil.', area: ['civil'], sinonimos: ['enriquecimento ilícito'], exemplo: 'A cobrança configura enriquecimento sem causa da ré.' },
    { termo: 'responsabilidade objetiva', significado: 'Responsabilidade independente de culpa.', uso: 'Basta demonstrar dano e nexo causal (teoria do risco).', area: ['civil', 'consumidor'], exemplo: 'Aplica-se a responsabilidade objetiva nos termos do art. 14 do CDC.' },
    { termo: 'responsabilidade subjetiva', significado: 'Responsabilidade que exige comprovação de culpa.', uso: 'Regra geral do art. 186 do Código Civil.', area: ['civil'], exemplo: 'A responsabilidade civil subjetiva exige prova de conduta, dano, nexo e culpa.' },
    { termo: 'dano moral', significado: 'Lesão a direitos da personalidade.', uso: 'Violação à honra, imagem, intimidade, dignidade.', area: ['civil', 'consumidor', 'trabalhista'], exemplo: 'O fato narrado configura dano moral indenizável.' },
    { termo: 'dano material', significado: 'Prejuízo patrimonial efetivo.', uso: 'Danos emergentes (perda efetiva) e lucros cessantes (ganho frustrado).', area: ['civil'], sinonimos: ['dano patrimonial'], exemplo: 'Os danos materiais compreendem danos emergentes e lucros cessantes.' },
    { termo: 'evicção', significado: 'Perda da coisa por decisão judicial em favor de terceiro.', uso: 'Quando o comprador perde a coisa por vício no título.', area: ['civil'], exemplo: 'O adquirente tem direito à restituição integral por evicção.' },
    { termo: 'vícios redibitórios', significado: 'Defeitos ocultos na coisa que a tornam imprópria para o uso.', uso: 'Defeito não aparente existente ao tempo da aquisição.', area: ['civil', 'consumidor'], exemplo: 'O defeito constitui vício redibitório (art. 441, CC).' },
    { termo: 'caso fortuito', significado: 'Evento imprevisível e inevitável que exclui responsabilidade.', uso: 'Excludente de responsabilidade civil.', area: ['civil'], sinonimos: ['força maior'], exemplo: 'O evento constitui caso fortuito, excludente de responsabilidade.' },
    { termo: 'prescrição', significado: 'Perda do direito de ação pelo decurso do tempo.', uso: 'Prazo para exercer pretensão em juízo.', area: ['civil', 'processual'], exemplo: 'O prazo prescricional é de 5 anos, nos termos do art. 27 do CDC.' },
    { termo: 'decadência', significado: 'Perda do direito potestativo pelo decurso do tempo.', uso: 'Distinta da prescrição — atinge o direito em si, não apenas a ação.', area: ['civil'], exemplo: 'O prazo decadencial para vício do produto é de 90 dias (art. 26, II, CDC).' },
    { termo: 'obrigação de fazer', significado: 'Dever de realizar determinada prestação.', uso: 'Tutela específica para cumprimento de obrigação positiva.', area: ['civil', 'processual'], exemplo: 'Requer-se a condenação em obrigação de fazer (art. 497, CPC).' },
    { termo: 'solidariedade', significado: 'Pluralidade de devedores ou credores com responsabilidade integral.', uso: 'Cada devedor responde pela dívida toda (solidariedade passiva).', area: ['civil', 'trabalhista'], exemplo: 'As rés respondem solidariamente, nos termos do art. 942 do CC.' },
    { termo: 'boa-fé objetiva', significado: 'Padrão de conduta leal e honesta nas relações jurídicas.', uso: 'Princípio que rege a interpretação e execução dos contratos.', area: ['civil', 'consumidor'], exemplo: 'A conduta da ré viola o princípio da boa-fé objetiva (art. 422, CC).' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'resolução contratual', significado: 'Extinção do contrato por inadimplemento.', uso: 'Desconstituição do vínculo contratual com efeitos retroativos.', area: ['civil'], exemplo: 'Requer-se a resolução contratual por culpa exclusiva da ré (art. 475, CC).' },
    { termo: 'resilição', significado: 'Extinção do contrato por vontade de uma ou ambas as partes.', uso: 'Pode ser unilateral (denúncia) ou bilateral (distrato).', area: ['civil'], exemplo: 'A resilição unilateral opera mediante denúncia notificada (art. 473, CC).' },
    { termo: 'novação', significado: 'Substituição de obrigação anterior por nova.', uso: 'Extingue a obrigação originária e cria uma nova (arts. 360-367, CC).', area: ['civil'], exemplo: 'Houve novação objetiva pela substituição da prestação originária.' },
    { termo: 'sub-rogação', significado: 'Substituição do credor originário por terceiro que satisfez a obrigação.', uso: 'O terceiro assume os direitos do credor pago.', area: ['civil'], exemplo: 'A seguradora sub-rogou-se nos direitos do segurado (art. 786, CC).' },
    { termo: 'compensação', significado: 'Extinção recíproca de obrigações entre credor e devedor.', uso: 'Quando duas pessoas são simultaneamente credoras e devedoras entre si.', area: ['civil'], exemplo: 'Os débitos foram extintos por compensação (art. 368, CC).' },
    { termo: 'cessão de crédito', significado: 'Transferência do direito creditório a terceiro.', uso: 'O cedente transfere ao cessionário o crédito que detém contra o devedor.', area: ['civil'], exemplo: 'A cessão de crédito foi notificada ao devedor (art. 290, CC).' },
    { termo: 'cláusula penal', significado: 'Estipulação de multa ou penalidade por descumprimento contratual.', uso: 'Pode ser compensatória ou moratória (arts. 408-416, CC).', area: ['civil'], exemplo: 'A cláusula penal é devida no percentual de 10% sobre o valor do contrato.' },
    { termo: 'arras', significado: 'Sinal dado em garantia de cumprimento do contrato.', uso: 'Confirmatórias (antecipação do pagamento) ou penitenciais (direito de arrependimento).', area: ['civil'], sinonimos: ['sinal'], exemplo: 'As arras penitenciais autorizam o arrependimento mediante perda do sinal (art. 420, CC).' },
    { termo: 'dano estético', significado: 'Lesão à aparência física que causa constrangimento.', uso: 'Modalidade autônoma de dano, cumulável com dano moral.', area: ['civil'], exemplo: 'A cicatriz permanente configura dano estético indenizável.' },
    { termo: 'lucros cessantes', significado: 'Ganho que a vítima razoavelmente deixou de auferir.', uso: 'Componente do dano material — lucro frustrado.', area: ['civil'], exemplo: 'Os lucros cessantes correspondem ao faturamento médio do período de paralisação.' },
    { termo: 'danos emergentes', significado: 'Prejuízo efetivamente sofrido pela vítima.', uso: 'Componente do dano material — perda concreta.', area: ['civil'], exemplo: 'Os danos emergentes incluem despesas médicas e reparo do veículo.' },
    { termo: 'função social do contrato', significado: 'Princípio que limita a liberdade contratual em prol do interesse coletivo.', uso: 'O contrato deve atender não só aos contratantes mas à coletividade (art. 421, CC).', area: ['civil'], exemplo: 'A cláusula viola a função social do contrato ao prejudicar terceiros.' },
    { termo: 'venire contra factum proprium', significado: 'Proibição de comportamento contraditório.', uso: 'Vedação a quem age em contradição com conduta anterior legítima.', area: ['civil'], origem: 'latim', exemplo: 'A postura da ré configura venire contra factum proprium, violando a boa-fé.' },
    { termo: 'supressio', significado: 'Perda de direito pelo não-exercício prolongado.', uso: 'Quando a parte cria legítima expectativa de que não exercerá o direito.', area: ['civil'], origem: 'latim', exemplo: 'Configurada a supressio, o credor perdeu o direito de cobrar as parcelas antigas.' },
    { termo: 'surrectio', significado: 'Surgimento de direito pelo exercício continuado.', uso: 'Contraparte da supressio — direito nasce de prática reiterada.', area: ['civil'], origem: 'latim', exemplo: 'A surrectio conferiu ao empregado o direito à gratificação paga habitualmente.' },
    { termo: 'tu quoque', significado: 'Vedação a exigir conduta que o próprio demandante violou.', uso: 'Ninguém pode invocar norma que ele mesmo descumpriu.', area: ['civil'], origem: 'latim', exemplo: 'A alegação da ré configura tu quoque, pois ela própria descumpriu o contrato.' },
    { termo: 'exceptio non adimpleti contractus', significado: 'Exceção de contrato não cumprido.', uso: 'Uma parte não pode exigir cumprimento se não cumpriu sua obrigação.', area: ['civil'], origem: 'latim', exemplo: 'Opõe-se a exceptio non adimpleti contractus (art. 476, CC).' },
    { termo: 'negócio jurídico', significado: 'Declaração de vontade destinada a produzir efeitos jurídicos.', uso: 'Categoria geral que engloba contratos, testamentos, procurações.', area: ['civil'], exemplo: 'O negócio jurídico é nulo por vício de consentimento (art. 171, CC).' },
    { termo: 'mora', significado: 'Atraso culposo no cumprimento da obrigação.', uso: 'Mora do devedor (solvendi) ou do credor (accipiendi).', area: ['civil'], exemplo: 'A constituição em mora ocorreu pela notificação extrajudicial.' },
    { termo: 'posse', significado: 'Exercício de fato de algum dos poderes inerentes à propriedade.', uso: 'Pode ser direta/indireta, justa/injusta, de boa-fé/má-fé.', area: ['civil', 'imobiliario'], exemplo: 'O autor comprovou posse mansa e pacífica por mais de 15 anos.' },
    { termo: 'servidão', significado: 'Direito real sobre coisa alheia que impõe restrição ao uso do imóvel serviente.', uso: 'Servidão de passagem, de aqueduto, de vista.', area: ['civil', 'imobiliario'], exemplo: 'A servidão de passagem foi constituída por escritura pública.' },
    { termo: 'usufruto', significado: 'Direito real de usar e fruir coisa alheia, sem alterar sua substância.', uso: 'O usufrutuário tem posse, uso e gozo do bem.', area: ['civil'], exemplo: 'Foi constituído usufruto vitalício em favor do cônjuge sobrevivente.' },
    { termo: 'hipoteca', significado: 'Direito real de garantia sobre bem imóvel.', uso: 'Bem continua na posse do devedor mas garante a dívida.', area: ['civil', 'imobiliario'], exemplo: 'O imóvel está gravado com hipoteca em favor do banco credor.' },
    { termo: 'fiança', significado: 'Garantia pessoal em que terceiro assume obrigação subsidiária.', uso: 'O fiador garante o cumprimento da obrigação do devedor principal.', area: ['civil'], exemplo: 'A fiança locatícia abrange as obrigações do locatário.' },
    { termo: 'dolo', significado: 'Artifício ou manobra empregada para enganar outrem.', uso: 'Vício de consentimento que torna anulável o negócio jurídico (art. 145, CC).', area: ['civil'], exemplo: 'O dolo do vendedor induziu o comprador em erro essencial.' },
    { termo: 'coação', significado: 'Pressão física ou moral que vicia a vontade.', uso: 'Violência ou ameaça grave que torna o ato anulável (art. 151, CC).', area: ['civil'], exemplo: 'O contrato foi celebrado sob coação moral irresistível.' },
];
