import type { LegalTerm } from './types';

/**
 * Glossário — Direito do Consumidor.
 */
export const CONSUMIDOR: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'vício do produto', significado: 'Defeito que torna o produto impróprio ou inadequado ao consumo.', uso: 'Art. 18 do CDC — prazo de 30 dias para sanar o vício.', area: ['consumidor'], exemplo: 'O produto apresentou vício no prazo de garantia legal.' },
    { termo: 'fato do serviço', significado: 'Defeito no serviço que causa dano ao consumidor.', uso: 'Responsabilidade objetiva do fornecedor (art. 14, CDC).', area: ['consumidor'], exemplo: 'O fato do serviço causou danos materiais e morais ao consumidor.' },
    { termo: 'inversão do ônus da prova', significado: 'Transferência do encargo probatório ao fornecedor.', uso: 'Faculdade do juiz quando verossímil a alegação (art. 6º, VIII, CDC).', area: ['consumidor'], exemplo: 'Requer-se a inversão do ônus da prova nos termos do art. 6º, VIII, do CDC.' },
    { termo: 'práticas abusivas', significado: 'Condutas vedadas ao fornecedor pelo CDC.', uso: 'Venda casada, publicidade enganosa, cláusulas abusivas.', area: ['consumidor'], exemplo: 'A venda casada constitui prática abusiva (art. 39, I, CDC).' },
    { termo: 'direito de arrependimento', significado: 'Direito de desistir da compra em 7 dias nas compras fora do estabelecimento.', uso: 'Art. 49 do CDC — compras pela internet, telefone ou domicílio.', area: ['consumidor'], exemplo: 'O consumidor exerceu o direito de arrependimento no prazo legal.' },
    { termo: 'teoria menor da desconsideração', significado: 'Desconsideração da PJ por simples inadimplemento.', uso: 'Aplicável ao Direito do Consumidor e Ambiental (art. 28, §5º, CDC).', area: ['consumidor'], exemplo: 'Aplica-se a teoria menor da desconsideração da personalidade jurídica.' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'fato do produto', significado: 'Defeito do produto que causa acidente de consumo.', uso: 'Responsabilidade objetiva do fabricante/importador (art. 12, CDC).', area: ['consumidor'], exemplo: 'A explosão do aparelho configura fato do produto (art. 12, CDC).' },
    { termo: 'recall', significado: 'Chamamento público para reparo ou substituição de produto defeituoso.', uso: 'Obrigação do fornecedor ao constatar defeito após comercialização.', area: ['consumidor'], exemplo: 'A montadora realizou recall para substituição do airbag defeituoso.' },
    { termo: 'publicidade enganosa', significado: 'Informação falsa ou capaz de induzir o consumidor em erro.', uso: 'Vedada pelo art. 37, §1º, do CDC, mesmo por omissão.', area: ['consumidor'], exemplo: 'O anúncio com informações falsas configura publicidade enganosa.' },
    { termo: 'publicidade abusiva', significado: 'Publicidade discriminatória, violenta ou que explore medo do consumidor.', uso: 'Vedada pelo art. 37, §2º, do CDC.', area: ['consumidor'], exemplo: 'A propaganda que explora a criança é considerada publicidade abusiva.' },
    { termo: 'venda casada', significado: 'Condicionamento da venda de produto à aquisição de outro.', uso: 'Prática abusiva vedada pelo art. 39, I, do CDC.', area: ['consumidor'], exemplo: 'A exigência de contratação de seguro configura venda casada.' },
    { termo: 'cláusula abusiva', significado: 'Disposição contratual que prejudica excessivamente o consumidor.', uso: 'Nula de pleno direito (art. 51, CDC).', area: ['consumidor'], exemplo: 'A cláusula que impede ressarcimento é abusiva e nula (art. 51, I, CDC).' },
    { termo: 'garantia legal', significado: 'Prazo de reclamação por vício fixado em lei.', uso: '30 dias para produtos não duráveis e 90 dias para duráveis (art. 26, CDC).', area: ['consumidor'], exemplo: 'O vício foi constatado dentro da garantia legal de 90 dias.' },
    { termo: 'garantia contratual', significado: 'Garantia adicional oferecida pelo fornecedor além da legal.', uso: 'Complementar à garantia legal (art. 50, CDC).', area: ['consumidor'], exemplo: 'A garantia contratual de 1 ano inicia após o término da garantia legal.' },
    { termo: 'vulnerabilidade', significado: 'Condição intrínseca do consumidor que justifica sua proteção.', uso: 'Reconhecida como princípio fundamental do CDC (art. 4º, I).', area: ['consumidor'], exemplo: 'A vulnerabilidade do consumidor é presumida pela legislação consumerista.' },
    { termo: 'hipervulnerabilidade', significado: 'Grau acentuado de vulnerabilidade de determinados consumidores.', uso: 'Idosos, crianças, portadores de deficiência e analfabetos.', area: ['consumidor'], exemplo: 'O consumidor idoso merece proteção especial por hipervulnerabilidade.' },
    { termo: 'consumidor por equiparação', significado: 'Pessoa que, embora não tenha adquirido o produto, sofre seus efeitos.', uso: 'Bystander — vítima de acidente de consumo (arts. 2º, §único e 17, CDC).', area: ['consumidor'], sinonimos: ['bystander'], exemplo: 'O pedestre atingido é consumidor por equiparação (art. 17, CDC).' },
    { termo: 'dano moral coletivo', significado: 'Lesão a direitos transindividuais que causa ofensa à coletividade.', uso: 'Tutela de interesses difusos e coletivos em ação civil pública.', area: ['consumidor', 'civil'], exemplo: 'A prática abusiva reiterada configura dano moral coletivo.' },
    { termo: 'superendividamento', significado: 'Comprometimento excessivo da renda do consumidor com dívidas.', uso: 'Tratamento previsto na Lei 14.181/2021 que alterou o CDC.', area: ['consumidor'], exemplo: 'O consumidor em situação de superendividamento tem direito à repactuação.' },
    { termo: 'direito à informação', significado: 'Direito do consumidor a informações claras e adequadas sobre produtos e serviços.', uso: 'Princípio fundamental do CDC (art. 6º, III).', area: ['consumidor'], exemplo: 'A omissão de informação essencial viola o direito à informação do consumidor.' },
    { termo: 'banco de dados de consumo', significado: 'Cadastros de proteção ao crédito (SPC, Serasa).', uso: 'Devem conter informações corretas e atualizadas (art. 43, CDC).', area: ['consumidor'], exemplo: 'A inscrição indevida no banco de dados gera dever de indenizar.' },
    { termo: 'ação civil pública', significado: 'Ação para tutela de interesses difusos, coletivos e individuais homogêneos.', uso: 'Legitimados: MP, Defensoria, associações, entes públicos.', area: ['consumidor', 'processual'], exemplo: 'O MP ajuizou ação civil pública em defesa dos consumidores lesados.' },
    { termo: 'desconsideração da personalidade jurídica', significado: 'Responsabilização dos sócios por obrigações da empresa.', uso: 'Teoria maior (art. 50, CC) e teoria menor (art. 28, §5º, CDC).', area: ['consumidor', 'civil'], exemplo: 'Requer-se a desconsideração da personalidade jurídica para atingir o patrimônio dos sócios.' },
    { termo: 'taxa de juros abusiva', significado: 'Cobrança de juros em percentual manifestamente excessivo.', uso: 'Contratos bancários com taxas muito acima da média de mercado.', area: ['consumidor', 'civil'], exemplo: 'A taxa de juros de 15% a.m. é manifestamente abusiva.' },
];
