import type { LegalTerm } from './types';

/**
 * Glossário — Direito Constitucional.
 */
export const CONSTITUCIONAL: LegalTerm[] = [
    { termo: 'controle de constitucionalidade', significado: 'Verificação da compatibilidade de normas com a Constituição.', uso: 'Pode ser difuso (caso concreto) ou concentrado (ADI, ADC, ADPF).', area: ['constitucional'], exemplo: 'O STF exerce o controle concentrado de constitucionalidade.' },
    { termo: 'ADI', significado: 'Ação Direta de Inconstitucionalidade.', uso: 'Visa declarar norma inconstitucional com efeito erga omnes (art. 102, I, "a", CF).', area: ['constitucional'], sinonimos: ['ação direta de inconstitucionalidade'], exemplo: 'A ADI foi julgada procedente para declarar a lei estadual inconstitucional.' },
    { termo: 'ADPF', significado: 'Arguição de Descumprimento de Preceito Fundamental.', uso: 'Ação subsidiária para proteger preceitos fundamentais (art. 102, §1º, CF).', area: ['constitucional'], exemplo: 'A ADPF foi ajuizada para questionar ato do Poder Executivo.' },
    { termo: 'súmula vinculante', significado: 'Enunciado do STF com força obrigatória para todo o Judiciário e Administração.', uso: 'Aprovada por 2/3 dos ministros (art. 103-A, CF).', area: ['constitucional'], exemplo: 'A Súmula Vinculante 37 veda aumento de remuneração por isonomia.' },
    { termo: 'cláusula pétrea', significado: 'Norma constitucional insuscetível de abolição por emenda.', uso: 'Art. 60, §4º, CF — forma federativa, voto, separação de poderes, direitos individuais.', area: ['constitucional'], exemplo: 'A proposta de emenda viola cláusula pétrea ao restringir direito fundamental.' },
    { termo: 'princípio da proporcionalidade', significado: 'Exigência de adequação, necessidade e proporcionalidade em sentido estrito.', uso: 'Limite ao poder estatal na restrição de direitos fundamentais.', area: ['constitucional'], exemplo: 'A medida restritiva viola o princípio da proporcionalidade por excesso.' },
    { termo: 'princípio da razoabilidade', significado: 'Exigência de que os atos estatais sejam racionais e adequados.', uso: 'Proíbe atos absurdos, arbitrários ou desproporcionais.', area: ['constitucional'], exemplo: 'A multa de R$ 1 milhão por infração leve viola a razoabilidade.' },
    { termo: 'devido processo legal', significado: 'Garantia de processo justo com contraditório e ampla defesa.', uso: 'Art. 5º, LIV, CF — ninguém será privado de bens sem due process.', area: ['constitucional'], exemplo: 'A decisão administrativa violou o devido processo legal.' },
    { termo: 'contraditório', significado: 'Direito de ser ouvido e de impugnar as alegações da parte contrária.', uso: 'Art. 5º, LV, CF — aplicável a processos judiciais e administrativos.', area: ['constitucional', 'processual'], exemplo: 'O contraditório foi assegurado com a intimação para manifestação.' },
    { termo: 'ampla defesa', significado: 'Direito de utilizar todos os meios legítimos de prova e argumentação.', uso: 'Art. 5º, LV, CF — complementar ao contraditório.', area: ['constitucional', 'processual'], exemplo: 'A cassação sem oportunidade de defesa viola a ampla defesa.' },
    { termo: 'repercussão geral', significado: 'Requisito de admissibilidade do recurso extraordinário.', uso: 'Questão deve transcender os interesses das partes (art. 1.035, CPC).', area: ['constitucional', 'processual'], exemplo: 'O STF reconheceu repercussão geral no tema 1234.' },
    { termo: 'modulação de efeitos', significado: 'Restrição temporal dos efeitos da decisão de inconstitucionalidade.', uso: 'STF pode fixar data a partir da qual a decisão produz efeitos (art. 27, Lei 9.868/99).', area: ['constitucional'], exemplo: 'O STF modulou os efeitos da decisão para preservar relações jurídicas consolidadas.' },
    { termo: 'ação popular', significado: 'Ação constitucional para anular ato lesivo ao patrimônio público.', uso: 'Legitimidade: qualquer cidadão (art. 5º, LXXIII, CF).', area: ['constitucional'], exemplo: 'A ação popular visa anular contrato lesivo ao erário municipal.' },
    { termo: 'mandado de injunção', significado: 'Remédio constitucional contra omissão legislativa que impede exercício de direito.', uso: 'Art. 5º, LXXI, CF — quando falta norma regulamentadora.', area: ['constitucional'], exemplo: 'O mandado de injunção supriu a omissão legislativa quanto ao direito de greve.' },
    { termo: 'dignidade da pessoa humana', significado: 'Fundamento da República que assegura tratamento digno a todo ser humano.', uso: 'Art. 1º, III, CF — princípio-matriz dos direitos fundamentais.', area: ['constitucional'], exemplo: 'A condição degradante viola o princípio da dignidade da pessoa humana.' },
    { termo: 'separação dos poderes', significado: 'Divisão das funções estatais entre Legislativo, Executivo e Judiciário.', uso: 'Cláusula pétrea (art. 2º c/c art. 60, §4º, III, CF).', area: ['constitucional'], exemplo: 'O decreto invade competência legislativa, violando a separação dos poderes.' },
    { termo: 'federalismo', significado: 'Forma de Estado com autonomia dos entes federativos.', uso: 'União, Estados, DF e Municípios com competências próprias.', area: ['constitucional'], exemplo: 'A lei federal invade competência legislativa estadual em matéria ambiental.' },
    { termo: 'isonomia', significado: 'Princípio de igualdade perante a lei.', uso: 'Art. 5º, caput, CF — tratar igualmente os iguais e desigualmente os desiguais.', area: ['constitucional'], exemplo: 'A distinção sem critério razoável viola o princípio da isonomia.' },
    { termo: 'segurança jurídica', significado: 'Princípio que garante previsibilidade e estabilidade das relações jurídicas.', uso: 'Impede retroatividade prejudicial e protege a confiança legítima.', area: ['constitucional'], exemplo: 'A mudança abrupta de entendimento viola a segurança jurídica.' },
    { termo: 'efeito vinculante', significado: 'Obrigatoriedade de decisão do STF para todos os órgãos judiciários e administrativos.', uso: 'Decisões em ADI, ADC, ADPF e súmulas vinculantes.', area: ['constitucional'], exemplo: 'A decisão do STF tem efeito vinculante e deve ser observada por todos os tribunais.' },
];
