import type { LegalTerm } from './types';

/**
 * Glossário — Direito Digital e LGPD.
 */
export const DIGITAL: LegalTerm[] = [
    { termo: 'dado pessoal', significado: 'Informação relacionada a pessoa natural identificada ou identificável.', uso: 'Conceito central da LGPD (art. 5º, I, Lei 13.709/2018).', area: ['digital'], exemplo: 'O CPF e o e-mail são dados pessoais protegidos pela LGPD.' },
    { termo: 'dado pessoal sensível', significado: 'Dado sobre origem racial, convicção religiosa, saúde, biometria etc.', uso: 'Tratamento exige consentimento específico ou hipótese legal (art. 11, LGPD).', area: ['digital'], exemplo: 'O prontuário médico contém dados pessoais sensíveis.' },
    { termo: 'controlador', significado: 'Pessoa que decide sobre o tratamento de dados pessoais.', uso: 'Responsável pelas decisões sobre finalidade e meios do tratamento (art. 5º, VI, LGPD).', area: ['digital'], exemplo: 'O controlador deve garantir a segurança dos dados tratados.' },
    { termo: 'operador', significado: 'Pessoa que realiza tratamento de dados em nome do controlador.', uso: 'Atua sob instruções do controlador (art. 5º, VII, LGPD).', area: ['digital'], exemplo: 'A empresa de TI atua como operador no tratamento dos dados.' },
    { termo: 'encarregado', significado: 'Pessoa indicada pelo controlador para atuar como canal de comunicação com titulares e ANPD.', uso: 'Também chamado DPO — Data Protection Officer (art. 5º, VIII, LGPD).', area: ['digital'], sinonimos: ['DPO', 'data protection officer'], exemplo: 'O encarregado deve ter seus dados de contato divulgados publicamente.' },
    { termo: 'ANPD', significado: 'Autoridade Nacional de Proteção de Dados.', uso: 'Órgão federal responsável por fiscalizar e regulamentar a LGPD.', area: ['digital'], exemplo: 'A ANPD aplicou sanção administrativa por descumprimento da LGPD.' },
    { termo: 'consentimento', significado: 'Manifestação livre, informada e inequívoca do titular autorizando o tratamento.', uso: 'Uma das bases legais para tratamento de dados (art. 7º, I, LGPD).', area: ['digital'], exemplo: 'O consentimento do titular deve ser específico para cada finalidade.' },
    { termo: 'base legal', significado: 'Fundamento jurídico que autoriza o tratamento de dados pessoais.', uso: 'Art. 7º da LGPD — 10 hipóteses (consentimento, contrato, legítimo interesse etc.).', area: ['digital'], exemplo: 'O tratamento está amparado na base legal do legítimo interesse (art. 7º, IX, LGPD).' },
    { termo: 'RIPD', significado: 'Relatório de Impacto à Proteção de Dados Pessoais.', uso: 'Documento que avalia riscos de operação de tratamento (art. 5º, XVII, LGPD).', area: ['digital'], sinonimos: ['relatório de impacto', 'DPIA'], exemplo: 'A ANPD pode solicitar RIPD para operações de alto risco.' },
    { termo: 'Marco Civil da Internet', significado: 'Lei 12.965/2014 que estabelece princípios, garantias, direitos e deveres para uso da internet.', uso: 'Trata de neutralidade, privacidade, responsabilidade de provedores.', area: ['digital'], exemplo: 'A remoção de conteúdo exige ordem judicial, salvo exceções (art. 19, Marco Civil).' },
    { termo: 'direito ao esquecimento', significado: 'Direito de ter informações pessoais desindexadas ou removidas.', uso: 'Controverso — STF julgou incompatível com CF em caso específico (RE 1.010.606).', area: ['digital', 'civil'], exemplo: 'O pedido de direito ao esquecimento foi fundamentado na proteção da dignidade.' },
    { termo: 'incidente de segurança', significado: 'Evento que compromete a confidencialidade, integridade ou disponibilidade de dados.', uso: 'Controlador deve comunicar à ANPD e ao titular em prazo razoável (art. 48, LGPD).', area: ['digital'], sinonimos: ['vazamento de dados', 'data breach'], exemplo: 'O incidente de segurança expôs dados de 500 mil clientes.' },
    { termo: 'portabilidade de dados', significado: 'Direito do titular de transferir seus dados a outro fornecedor.', uso: 'Garantido pelo art. 18, V, da LGPD.', area: ['digital'], exemplo: 'O titular requereu a portabilidade dos dados para outra operadora.' },
    { termo: 'anonimização', significado: 'Processo pelo qual o dado perde a possibilidade de associação a um titular.', uso: 'Dados anonimizados não são considerados dados pessoais (art. 12, LGPD).', area: ['digital'], exemplo: 'Os dados foram anonimizados para fins estatísticos.' },
    { termo: 'legítimo interesse', significado: 'Base legal que permite tratamento sem consentimento quando há interesse legítimo do controlador.', uso: 'Exige teste de proporcionalidade e RIPD (art. 10, LGPD).', area: ['digital'], exemplo: 'O tratamento para prevenção de fraudes se ampara no legítimo interesse.' },
];
