import type { LegalTerm } from './types';

/**
 * Glossário — Direito Empresarial.
 */
export const EMPRESARIAL: LegalTerm[] = [
    { termo: 'contrato social', significado: 'Instrumento constitutivo da sociedade empresária.', uso: 'Define objeto, capital, sócios, administração e participações.', area: ['empresarial'], exemplo: 'O contrato social foi registrado na Junta Comercial.' },
    { termo: 'sociedade limitada', significado: 'Tipo societário em que a responsabilidade dos sócios é limitada às quotas.', uso: 'Tipo mais comum no Brasil (arts. 1.052-1.087, CC).', area: ['empresarial'], sinonimos: ['LTDA'], exemplo: 'A sociedade limitada responde pelas obrigações sociais com seu patrimônio.' },
    { termo: 'sociedade anônima', significado: 'Tipo societário cujo capital é dividido em ações.', uso: 'Pode ser aberta (mercado de valores) ou fechada (Lei 6.404/76).', area: ['empresarial'], sinonimos: ['S.A.', 'companhia'], exemplo: 'A sociedade anônima de capital aberto deve registrar-se na CVM.' },
    { termo: 'recuperação judicial', significado: 'Procedimento para reestruturação de empresa em crise econômico-financeira.', uso: 'Visa preservar a empresa, emprego e interesse dos credores (Lei 11.101/05).', area: ['empresarial'], exemplo: 'A empresa apresentou plano de recuperação judicial no prazo legal.' },
    { termo: 'falência', significado: 'Processo de liquidação dos bens do devedor insolvente.', uso: 'Último recurso — apuração e venda do ativo para pagar credores.', area: ['empresarial'], exemplo: 'Decretada a falência, os bens serão arrecadados e vendidos.' },
    { termo: 'desconsideração da personalidade jurídica', significado: 'Responsabilização dos sócios por obrigações da empresa.', uso: 'Teoria maior exige abuso (art. 50, CC); teoria menor não (art. 28, §5º, CDC).', area: ['empresarial', 'civil'], exemplo: 'Requer-se a desconsideração da personalidade jurídica para atingir o patrimônio dos sócios.' },
    { termo: 'estabelecimento empresarial', significado: 'Conjunto de bens organizados para exercício da atividade empresarial.', uso: 'Bens corpóreos (máquinas, estoques) e incorpóreos (marca, ponto).', area: ['empresarial'], sinonimos: ['fundo de comércio'], exemplo: 'O trespasse do estabelecimento empresarial foi realizado por escritura pública.' },
    { termo: 'trespasse', significado: 'Alienação do estabelecimento empresarial.', uso: 'Transferência do fundo de comércio como universalidade de bens.', area: ['empresarial'], exemplo: 'O trespasse foi efetivado mediante pagamento de aviamento.' },
    { termo: 'marca registrada', significado: 'Sinal distintivo de produto ou serviço registrado no INPI.', uso: 'Confere exclusividade de uso por 10 anos, renovável (Lei 9.279/96).', area: ['empresarial'], exemplo: 'A marca registrada confere direito de uso exclusivo em todo o território nacional.' },
    { termo: 'patente', significado: 'Título que confere direito de exploração exclusiva de invenção.', uso: 'Vigência de 20 anos para invenção e 15 para modelo de utilidade.', area: ['empresarial'], exemplo: 'O pedido de patente foi depositado no INPI.' },
    { termo: 'nota promissória', significado: 'Título de crédito pelo qual o emitente se obriga a pagar quantia determinada.', uso: 'Promessa de pagamento — título executivo extrajudicial.', area: ['empresarial'], exemplo: 'A nota promissória vencida constitui título executivo extrajudicial.' },
    { termo: 'duplicata', significado: 'Título de crédito vinculado a compra e venda mercantil ou prestação de serviço.', uso: 'Pode ser protestada e executada (Lei 5.474/68).', area: ['empresarial'], exemplo: 'A duplicata mercantil foi protestada por falta de aceite.' },
    { termo: 'cheque', significado: 'Ordem de pagamento à vista contra banco.', uso: 'Prescreve em 6 meses contados do fim do prazo de apresentação (Lei 7.357/85).', area: ['empresarial'], exemplo: 'O cheque devolvido por insuficiência de fundos pode ser executado.' },
    { termo: 'aval', significado: 'Garantia cambial dada por terceiro em título de crédito.', uso: 'O avalista responde como devedor principal.', area: ['empresarial'], exemplo: 'O aval é garantia autônoma e independente da obrigação principal.' },
    { termo: 'endosso', significado: 'Transferência de título de crédito pelo beneficiário.', uso: 'Assinatura no verso do título que transfere sua titularidade.', area: ['empresarial'], exemplo: 'O título foi transferido por endosso em preto ao cessionário.' },
    { termo: 'assembleia geral', significado: 'Reunião dos sócios ou acionistas para deliberações sociais.', uso: 'Ordinária (anual) ou extraordinária (outros assuntos).', area: ['empresarial'], exemplo: 'A assembleia geral extraordinária aprovou o aumento de capital.' },
    { termo: 'dissolução societária', significado: 'Encerramento da sociedade empresária.', uso: 'Pode ser de pleno direito, judicial ou por deliberação dos sócios.', area: ['empresarial'], exemplo: 'A dissolução parcial da sociedade foi requerida pelo sócio minoritário.' },
    { termo: 'holding', significado: 'Sociedade que detém participação em outras empresas.', uso: 'Instrumento de planejamento patrimonial e sucessório.', area: ['empresarial'], exemplo: 'A holding patrimonial foi constituída para gestão dos bens imóveis da família.' },
    { termo: 'MEI', significado: 'Microempreendedor Individual — regime simplificado para pequenos negócios.', uso: 'Faturamento anual até R$ 81.000 e no máximo 1 empregado.', area: ['empresarial'], sinonimos: ['microempreendedor individual'], exemplo: 'O profissional formalizou-se como MEI para emissão de nota fiscal.' },
    { termo: 'EIRELI', significado: 'Empresa Individual de Responsabilidade Limitada.', uso: 'Tipo societário unipessoal com responsabilidade limitada ao capital.', area: ['empresarial'], exemplo: 'A EIRELI foi constituída com capital social de 100 salários mínimos.' },
    { termo: 'cláusula de não competição', significado: 'Restrição contratual que impede concorrência pelo sócio retirante.', uso: 'Deve ter prazo determinado e abrangência geográfica definida.', area: ['empresarial'], exemplo: 'A cláusula de não competição proíbe atuação no mesmo ramo por 2 anos.' },
    { termo: 'due diligence', significado: 'Auditoria jurídica prévia a operações societárias.', uso: 'Análise de riscos jurídicos, fiscais e trabalhistas da empresa-alvo.', area: ['empresarial'], exemplo: 'A due diligence revelou passivo trabalhista significativo.' },
    { termo: 'acordo de sócios', significado: 'Pacto entre sócios que regula direitos e obrigações adicionais.', uso: 'Trata de compra e venda de quotas, voto, administração e saída.', area: ['empresarial'], sinonimos: ['acordo de acionistas'], exemplo: 'O acordo de sócios prevê direito de preferência na cessão de quotas.' },
    { termo: 'responsabilidade dos administradores', significado: 'Dever de diligência, lealdade e boa-fé dos gestores da sociedade.', uso: 'Administrador responde por atos com excesso de poder ou contra a lei.', area: ['empresarial'], exemplo: 'O administrador responde pessoalmente pelos atos praticados com culpa.' },
    { termo: 'livre iniciativa', significado: 'Princípio constitucional que garante o direito de empreender.', uso: 'Fundamento da ordem econômica (art. 170, caput, CF).', area: ['empresarial', 'constitucional'], exemplo: 'A restrição viola o princípio da livre iniciativa.' },
];
