import type { LegalTerm } from './types';

/**
 * Glossário — Direito de Família e Sucessões.
 */
export const FAMILIA: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'guarda compartilhada', significado: 'Exercício conjunto do poder familiar por ambos os pais.', uso: 'Regra geral após Lei 13.058/2014.', area: ['familia'], exemplo: 'Requer-se a fixação da guarda compartilhada (art. 1.584, §2º, CC).' },
    { termo: 'alienação parental', significado: 'Interferência na formação psicológica da criança contra genitor.', uso: 'Conduta prevista na Lei 12.318/2010.', area: ['familia'], exemplo: 'A conduta do genitor configura alienação parental (art. 2º, Lei 12.318/2010).' },
    { termo: 'alimentos avoengos', significado: 'Alimentos devidos pelos avós.', uso: 'Subsidiários — apenas na falta ou insuficiência dos pais.', area: ['familia'], exemplo: 'Demonstrada a impossibilidade do genitor, cabem alimentos avoengos.' },
    { termo: 'partilha de bens', significado: 'Divisão do patrimônio comum na dissolução da sociedade conjugal.', uso: 'Pode ser amigável ou judicial, conforme regime de bens.', area: ['familia'], exemplo: 'Na partilha, os bens adquiridos na constância do casamento devem ser divididos igualmente.' },
    { termo: 'pensão alimentícia', significado: 'Prestação periódica para sustento de dependente.', uso: 'Fixada conforme binômio necessidade-possibilidade.', area: ['familia'], sinonimos: ['alimentos'], exemplo: 'Requer-se a fixação de alimentos em 30% dos rendimentos líquidos.' },
    { termo: 'dissolução da união estável', significado: 'Encerramento da entidade familiar entre companheiros.', uso: 'Equiparada ao casamento para fins patrimoniais.', area: ['familia'], exemplo: 'A dissolução da união estável rege-se pelo regime da comunhão parcial.' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'poder familiar', significado: 'Conjunto de direitos e deveres dos pais em relação aos filhos menores.', uso: 'Exercício no melhor interesse da criança (art. 1.634, CC).', area: ['familia'], sinonimos: ['pátrio poder'], exemplo: 'A destituição do poder familiar é medida extrema (art. 1.638, CC).' },
    { termo: 'guarda unilateral', significado: 'Atribuição da guarda a apenas um dos genitores.', uso: 'Exceção — quando guarda compartilhada for inviável.', area: ['familia'], exemplo: 'A guarda unilateral foi deferida à mãe por melhor atender o interesse do menor.' },
    { termo: 'direito de visita', significado: 'Direito do genitor não guardião de conviver com o filho.', uso: 'Regulamentado em acordo ou decisão judicial.', area: ['familia'], sinonimos: ['direito de convivência'], exemplo: 'O direito de visita quinzenal foi fixado em audiência.' },
    { termo: 'binômio necessidade-possibilidade', significado: 'Critério para fixação de alimentos: necessidade do alimentando e possibilidade do alimentante.', uso: 'Art. 1.694, §1º, CC — equilíbrio entre o que se precisa e o que se pode pagar.', area: ['familia'], exemplo: 'Os alimentos devem ser fixados à luz do binômio necessidade-possibilidade.' },
    { termo: 'alimentos gravídicos', significado: 'Alimentos devidos à gestante desde a concepção.', uso: 'Previstos na Lei 11.804/2008.', area: ['familia'], exemplo: 'Requer-se a fixação de alimentos gravídicos para custeio da gestação.' },
    { termo: 'alimentos provisórios', significado: 'Alimentos fixados liminarmente no início da ação.', uso: 'Decisão provisória baseada em indícios de paternidade e necessidade.', area: ['familia'], exemplo: 'Foram fixados alimentos provisórios em 25% dos rendimentos líquidos.' },
    { termo: 'execução de alimentos', significado: 'Procedimento para cobrar pensão alimentícia em atraso.', uso: 'Pode resultar em prisão civil do devedor (art. 528, §3º, CPC).', area: ['familia'], exemplo: 'Iniciada a execução de alimentos pelo rito da prisão.' },
    { termo: 'prisão civil por alimentos', significado: 'Medida coercitiva contra devedor de alimentos.', uso: 'Única hipótese de prisão por dívida admitida (art. 5º, LXVII, CF).', area: ['familia'], exemplo: 'Decretada a prisão civil do devedor de alimentos por 30 dias.' },
    { termo: 'inventário', significado: 'Procedimento para apuração e partilha dos bens do falecido.', uso: 'Pode ser judicial ou extrajudicial (escritura pública).', area: ['familia'], exemplo: 'O inventário foi aberto no prazo de 60 dias do óbito.' },
    { termo: 'testamento', significado: 'Ato pelo qual a pessoa dispõe de seus bens para após a morte.', uso: 'Modalidades: público, cerrado e particular.', area: ['familia'], exemplo: 'O de cujus deixou testamento público lavrado em cartório.' },
    { termo: 'legítima', significado: 'Parte da herança reservada aos herdeiros necessários.', uso: 'Corresponde a 50% do patrimônio — indisponível por testamento.', area: ['familia'], exemplo: 'A disposição testamentária não pode ultrapassar a parte disponível, preservando a legítima.' },
    { termo: 'herdeiro necessário', significado: 'Descendente, ascendente ou cônjuge com direito à legítima.', uso: 'Não pode ser afastado da herança salvo por deserdação.', area: ['familia'], exemplo: 'Os filhos são herdeiros necessários e não podem ser preteridos.' },
    { termo: 'colação', significado: 'Dever do herdeiro de declarar doações recebidas em vida do de cujus.', uso: 'Iguala as legítimas entre os herdeiros.', area: ['familia'], exemplo: 'O herdeiro foi intimado a trazer à colação o imóvel doado em vida.' },
    { termo: 'regime de comunhão parcial', significado: 'Regime de bens que comunica os adquiridos na constância do casamento.', uso: 'Regime legal supletivo (art. 1.640, CC).', area: ['familia'], exemplo: 'No regime de comunhão parcial, os bens anteriores ao casamento são particulares.' },
    { termo: 'regime de separação total', significado: 'Regime de bens em que não há comunicação patrimonial.', uso: 'Cada cônjuge mantém a propriedade exclusiva de seus bens.', area: ['familia'], exemplo: 'Os nubentes optaram pelo regime de separação total de bens.' },
    { termo: 'divórcio', significado: 'Dissolução do vínculo matrimonial.', uso: 'Pode ser consensual ou litigioso, judicial ou extrajudicial.', area: ['familia'], exemplo: 'O divórcio consensual foi homologado em cartório.' },
    { termo: 'reconhecimento de paternidade', significado: 'Estabelecimento jurídico do vínculo de filiação.', uso: 'Pode ser voluntário ou judicial (investigação de paternidade).', area: ['familia'], exemplo: 'O exame de DNA confirmou a paternidade biológica.' },
    { termo: 'adoção', significado: 'Constituição de vínculo de filiação por decisão judicial.', uso: 'Irrevogável — confere ao adotado a condição de filho (art. 41, ECA).', area: ['familia'], exemplo: 'A sentença de adoção atribuiu ao adotando a condição de filho.' },
    { termo: 'mediação familiar', significado: 'Método consensual de resolução de conflitos familiares.', uso: 'Facilita o diálogo entre as partes com auxílio de mediador imparcial.', area: ['familia'], exemplo: 'As partes foram encaminhadas à mediação familiar para composição do litígio.' },
];
