import type { LegalTerm } from './types';

/**
 * Glossário — Termos de origem francesa no Direito brasileiro.
 */
export const FRANCES: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    {
        termo: 'parquet',
        significado: 'Ministério Público',
        uso: 'Designação tradicional do MP, referência ao assoalho do tribunal francês.',
        area: ['processual', 'penal'],
        origem: 'frances',
        sinonimos: ['Ministério Público', 'MP'],
        exemplo: 'O Parquet manifestou-se pela improcedência do pedido.',
    },
    {
        termo: 'rapport',
        significado: 'Relatório, parecer.',
        uso: 'Relatório elaborado por perito ou relator.',
        area: ['processual'],
        origem: 'frances',
    },
    {
        termo: 'mise en demeure',
        significado: 'Notificação, constituição em mora.',
        uso: 'Ato de constituir o devedor em mora por notificação formal.',
        area: ['civil'],
        origem: 'frances',
        exemplo: 'A mise en demeure foi realizada por carta registrada.',
    },
    {
        termo: 'force majeure',
        significado: 'Força maior.',
        uso: 'Evento imprevisível e irresistível que exclui responsabilidade.',
        area: ['civil'],
        origem: 'frances',
        sinonimos: ['força maior', 'caso fortuito'],
        exemplo: 'A pandemia configurou force majeure para fins contratuais.',
    },
    {
        termo: 'greffier',
        significado: 'Escrivão, secretário do tribunal.',
        uso: 'Servidor responsável pela documentação processual.',
        area: ['processual'],
        origem: 'frances',
        sinonimos: ['escrivão'],
    },
    {
        termo: 'arrêt',
        significado: 'Acórdão, decisão de tribunal superior.',
        uso: 'Decisão colegiada de tribunal.',
        area: ['processual'],
        origem: 'frances',
        sinonimos: ['acórdão'],
    },

    // ── Novos ───────────────────────────────────────────────────────────
    {
        termo: 'détournement de pouvoir',
        significado: 'Desvio de poder.',
        uso: 'Uso de competência administrativa para finalidade diversa da prevista em lei.',
        area: ['administrativo'],
        origem: 'frances',
        sinonimos: ['desvio de finalidade'],
        exemplo: 'O ato administrativo padece de détournement de pouvoir.',
    },
    {
        termo: 'droit acquis',
        significado: 'Direito adquirido.',
        uso: 'Direito já incorporado ao patrimônio jurídico do titular.',
        area: ['constitucional', 'civil'],
        origem: 'frances',
        sinonimos: ['direito adquirido'],
        exemplo: 'A norma superveniente não pode violar o droit acquis.',
    },
    {
        termo: 'en bloc',
        significado: 'Em bloco, em conjunto.',
        uso: 'Votação ou deliberação conjunta de vários itens.',
        area: ['processual', 'administrativo'],
        origem: 'frances',
        exemplo: 'Os artigos foram votados en bloc pela assembleia.',
    },
    {
        termo: 'cassation',
        significado: 'Cassação, anulação de decisão judicial.',
        uso: 'Recurso para tribunal superior visando anulação por vício de direito.',
        area: ['processual'],
        origem: 'frances',
        exemplo: 'O recurso de cassation visa anular o acórdão por violação de lei.',
    },
    {
        termo: 'contrat d\'adhésion',
        significado: 'Contrato de adesão.',
        uso: 'Contrato cujas cláusulas são fixadas unilateralmente por uma das partes.',
        area: ['civil', 'consumidor'],
        origem: 'frances',
        sinonimos: ['contrato de adesão'],
        exemplo: 'Trata-se de contrat d\'adhésion, aplicando-se o art. 54 do CDC.',
    },
    {
        termo: 'mise en cause',
        significado: 'Chamamento à causa, responsabilização.',
        uso: 'Ato de incluir alguém como parte ou responsável no processo.',
        area: ['processual'],
        origem: 'frances',
        exemplo: 'A mise en cause do garantidor é indispensável à composição da lide.',
    },
    {
        termo: 'réquisitoire',
        significado: 'Requisitório, promoção do Ministério Público.',
        uso: 'Peça processual em que o MP requer providências ao juízo.',
        area: ['penal', 'processual'],
        origem: 'frances',
        exemplo: 'O réquisitoire do Parquet opinou pela pronúncia do acusado.',
    },
    {
        termo: 'chose jugée',
        significado: 'Coisa julgada.',
        uso: 'Autoridade da decisão judicial irrecorrível.',
        area: ['processual'],
        origem: 'frances',
        sinonimos: ['coisa julgada', 'res judicata'],
        exemplo: 'A matéria está coberta pela chose jugée.',
    },
    {
        termo: 'droit d\'auteur',
        significado: 'Direito de autor.',
        uso: 'Proteção jurídica da criação intelectual de obras literárias, artísticas e científicas.',
        area: ['civil', 'digital'],
        origem: 'frances',
        sinonimos: ['direito autoral', 'copyright'],
        exemplo: 'A reprodução não autorizada viola o droit d\'auteur do criador.',
    },
];
