import type { LegalTerm } from './types';

/**
 * Glossário — Direito Imobiliário.
 */
export const IMOBILIARIO: LegalTerm[] = [
    { termo: 'escritura pública', significado: 'Instrumento lavrado em cartório para formalizar negócios jurídicos.', uso: 'Obrigatória para imóveis acima de 30 salários mínimos (art. 108, CC).', area: ['imobiliario'], exemplo: 'A escritura pública de compra e venda foi lavrada no 1º Tabelionato.' },
    { termo: 'registro de imóvel', significado: 'Ato que transfere a propriedade imobiliária perante o cartório de registro.', uso: 'A propriedade só se transmite com o registro (art. 1.245, CC).', area: ['imobiliario'], exemplo: 'O registro da escritura no cartório de imóveis efetivou a transferência.' },
    { termo: 'matrícula do imóvel', significado: 'Registro individualizado do imóvel no cartório de registro.', uso: 'Cada imóvel tem uma matrícula — histórico de propriedade e ônus.', area: ['imobiliario'], exemplo: 'A matrícula nº 12.345 do CRI revela a cadeia dominial do imóvel.' },
    { termo: 'contrato de locação', significado: 'Acordo pelo qual o locador cede o uso do imóvel ao locatário.', uso: 'Regido pela Lei 8.245/91 (Lei do Inquilinato).', area: ['imobiliario'], exemplo: 'O contrato de locação tem prazo de 30 meses.' },
    { termo: 'despejo', significado: 'Ação para retomada do imóvel locado.', uso: 'Hipóteses previstas na Lei 8.245/91 — inadimplência, uso próprio etc.', area: ['imobiliario'], exemplo: 'A ação de despejo foi ajuizada por falta de pagamento.' },
    { termo: 'ação renovatória', significado: 'Ação do locatário comercial para renovar compulsoriamente o contrato.', uso: 'Protege o fundo de comércio — exige 5 anos de contrato e 3 de estabelecimento.', area: ['imobiliario', 'empresarial'], exemplo: 'A ação renovatória garante a permanência do lojista no ponto comercial.' },
    { termo: 'retomada para uso próprio', significado: 'Direito do locador de retomar o imóvel para uso pessoal ou familiar.', uso: 'Hipótese de denúncia motivada na Lei do Inquilinato.', area: ['imobiliario'], exemplo: 'O locador notificou a retomada para uso próprio com 30 dias de antecedência.' },
    { termo: 'compromisso de compra e venda', significado: 'Contrato preliminar que obriga as partes à celebração do contrato definitivo.', uso: 'Gera direito real do promitente comprador se registrado (art. 1.417, CC).', area: ['imobiliario'], exemplo: 'O compromisso de compra e venda foi registrado na matrícula do imóvel.' },
    { termo: 'incorporação imobiliária', significado: 'Atividade de construção e venda de unidades autônomas em condomínio.', uso: 'Regida pela Lei 4.591/64 — exige registro do memorial de incorporação.', area: ['imobiliario'], exemplo: 'A incorporação imobiliária foi registrada com todos os documentos exigidos.' },
    { termo: 'condomínio edilício', significado: 'Regime jurídico de propriedade por unidades autônomas em edificação.', uso: 'Áreas comuns e privativas — regido por convenção e regimento interno.', area: ['imobiliario'], exemplo: 'A convenção do condomínio edilício proíbe animais de grande porte.' },
    { termo: 'direito de preferência', significado: 'Direito do locatário de adquirir o imóvel locado em igualdade de condições.', uso: 'Art. 27 da Lei 8.245/91 — prazo de 30 dias para manifestação.', area: ['imobiliario'], exemplo: 'O locatário exerceu o direito de preferência na aquisição do imóvel.' },
    { termo: 'alienação fiduciária de imóvel', significado: 'Garantia em que o devedor transfere a propriedade resolúvel ao credor.', uso: 'Principal garantia no financiamento imobiliário (Lei 9.514/97).', area: ['imobiliario'], exemplo: 'O imóvel está em alienação fiduciária junto ao banco financiador.' },
    { termo: 'consolidação da propriedade', significado: 'Transferência definitiva do imóvel ao credor fiduciário por inadimplência.', uso: 'Após purgação da mora não realizada — art. 26, §7º, Lei 9.514/97.', area: ['imobiliario'], exemplo: 'O credor fiduciário consolidou a propriedade após notificação do devedor.' },
    { termo: 'direito de superfície', significado: 'Direito real de construir ou plantar em terreno alheio por prazo determinado.', uso: 'O superficiário não adquire a propriedade do terreno (art. 1.369, CC).', area: ['imobiliario'], exemplo: 'O direito de superfície foi concedido pelo prazo de 20 anos.' },
    { termo: 'usucapião extrajudicial', significado: 'Reconhecimento da usucapião diretamente no cartório de registro.', uso: 'Procedimento administrativo perante o oficial de registro (art. 216-A, LRP).', area: ['imobiliario', 'civil'], exemplo: 'O requerimento de usucapião extrajudicial foi apresentado ao cartório.' },
];
