import type { LegalTerm } from './types';

/**
 * Glossário de termos jurídicos de origem latina.
 */
export const LATIM: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    {
        termo: 'ab initio',
        significado: 'Desde o início; desde a origem.',
        uso: 'Indica que algo é considerado a partir do seu começo, como a nulidade de um ato.',
        area: ['civil', 'processual'],
        origem: 'latim',
        sinonimos: ['desde o princípio'],
        exemplo: 'O contrato foi declarado nulo ab initio, ou seja, nunca produziu efeitos jurídicos.',
    },
    {
        termo: 'ad cautelam',
        significado: 'Por cautela; por precaução.',
        uso: 'Indica ato praticado por cautela, mesmo sem obrigação estrita.',
        area: ['processual', 'civil'],
        origem: 'latim',
        sinonimos: ['por precaução', 'cautelarmente'],
        exemplo: 'O advogado interpôs recurso ad cautelam, para evitar preclusão caso a decisão fosse desfavorável.',
    },
    {
        termo: 'ad judicia',
        significado: 'Para o juízo; para fins judiciais.',
        uso: 'Refere-se a procuração com poderes para representar em juízo.',
        area: ['processual'],
        origem: 'latim',
        exemplo: 'A procuração ad judicia habilita o advogado a praticar todos os atos processuais ordinários.',
    },
    {
        termo: 'ad argumentandum tantum',
        significado: 'Apenas para efeito de argumentação.',
        uso: 'Usado para desenvolver raciocínio hipotético, sem conceder a premissa.',
        area: ['processual', 'penal'],
        origem: 'latim',
        sinonimos: ['a título de argumento'],
        exemplo: 'Ad argumentandum tantum, ainda que se admitisse a culpa do réu, a pena seria desproporcional.',
    },
    {
        termo: 'amicus curiae',
        significado: 'Amigo da corte.',
        uso: 'Terceiro admitido no processo para oferecer subsídios técnicos ou jurídicos ao tribunal.',
        area: ['processual', 'constitucional'],
        origem: 'latim',
        exemplo: 'O Conselho Federal da OAB foi admitido como amicus curiae na ADI sobre prerrogativas da advocacia.',
    },
    {
        termo: 'animus necandi',
        significado: 'Intenção de matar.',
        uso: 'Elemento subjetivo que diferencia homicídio de lesão corporal seguida de morte.',
        area: ['penal'],
        origem: 'latim',
        sinonimos: ['dolo de matar'],
        exemplo: 'A perícia indicou que os golpes foram desferidos com animus necandi, configurando tentativa de homicídio.',
    },
    {
        termo: 'bis in idem',
        significado: 'Duas vezes sobre o mesmo.',
        uso: 'Proibição de punir ou processar alguém duas vezes pelo mesmo fato.',
        area: ['penal', 'tributário', 'processual'],
        origem: 'latim',
        sinonimos: ['dupla penalização'],
        exemplo: 'A aplicação simultânea de multa administrativa e penal pelo mesmo fato configurou bis in idem.',
    },
    {
        termo: 'caput',
        significado: 'Cabeça; parte principal do artigo de lei.',
        uso: 'Refere-se ao enunciado principal de um artigo, antes dos parágrafos e incisos.',
        area: ['legislação', 'constitucional'],
        origem: 'latim',
        exemplo: 'O caput do art. 5º da Constituição garante a igualdade de todos perante a lei.',
    },
    {
        termo: 'corpus delicti',
        significado: 'Corpo de delito; prova material do crime.',
        uso: 'Conjunto de vestígios materiais que comprovam a existência de uma infração penal.',
        area: ['penal', 'processual penal'],
        origem: 'latim',
        sinonimos: ['corpo de delito'],
        exemplo: 'O exame de corpus delicti confirmou a causa da morte como asfixia mecânica.',
    },
    {
        termo: 'data venia',
        significado: 'Com a devida permissão; com o devido respeito.',
        uso: 'Expressão de cortesia usada antes de discordar de posição superior.',
        area: ['processual', 'forense'],
        origem: 'latim',
        sinonimos: ['com a devida vênia', 'com todo respeito'],
        exemplo: 'Data venia, o entendimento do i. magistrado não se coaduna com a jurisprudência consolidada do STJ.',
    },
    {
        termo: 'de cujus',
        significado: 'Aquele de quem (se trata a herança); o falecido.',
        uso: 'Referência à pessoa falecida em processos de inventário e sucessão.',
        area: ['civil', 'sucessões'],
        origem: 'latim',
        sinonimos: ['falecido', 'autor da herança'],
        exemplo: 'Os bens do de cujus foram partilhados igualmente entre os três herdeiros necessários.',
    },
    {
        termo: 'erga omnes',
        significado: 'Contra todos; perante todos.',
        uso: 'Indica efeito jurídico oponível a terceiros, não apenas às partes do processo.',
        area: ['constitucional', 'civil', 'processual'],
        origem: 'latim',
        sinonimos: ['efeito geral', 'oponível a todos'],
        exemplo: 'A decisão em ADI tem efeito erga omnes, vinculando todos os órgãos do Judiciário e da Administração.',
    },
    {
        termo: 'ex officio',
        significado: 'De ofício; por dever do cargo.',
        uso: 'Ato praticado pelo juiz sem provocação das partes, por iniciativa própria.',
        area: ['processual', 'administrativo'],
        origem: 'latim',
        sinonimos: ['de ofício', 'oficiosamente'],
        exemplo: 'O juiz declarou ex officio a incompetência absoluta do juízo e remeteu os autos à vara competente.',
    },
    {
        termo: 'ex nunc',
        significado: 'A partir de agora; sem retroatividade.',
        uso: 'Efeitos que se produzem apenas para o futuro, sem atingir situações passadas.',
        area: ['processual', 'constitucional', 'civil'],
        origem: 'latim',
        sinonimos: ['sem efeito retroativo', 'prospectivo'],
        exemplo: 'A modulação dos efeitos da decisão foi fixada ex nunc, preservando as relações jurídicas já constituídas.',
    },
    {
        termo: 'ex tunc',
        significado: 'Desde então; com retroatividade.',
        uso: 'Efeitos que retroagem à data do ato declarado nulo ou inconstitucional.',
        area: ['processual', 'constitucional', 'civil'],
        origem: 'latim',
        sinonimos: ['retroativamente', 'desde a origem'],
        exemplo: 'A nulidade do ato administrativo opera efeitos ex tunc, devolvendo as partes ao estado anterior.',
    },
    {
        termo: 'fumus boni juris',
        significado: 'Fumaça do bom direito; aparência de razão.',
        uso: 'Requisito para concessão de tutela provisória: probabilidade de existência do direito invocado.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['aparência do bom direito', 'plausibilidade jurídica'],
        exemplo: 'Presentes o fumus boni juris e o periculum in mora, concede-se a tutela de urgência requerida.',
    },
    {
        termo: 'habeas corpus',
        significado: 'Que tenhas o corpo.',
        uso: 'Remédio constitucional para proteger a liberdade de locomoção contra ilegalidade ou abuso de poder.',
        area: ['penal', 'constitucional', 'processual penal'],
        origem: 'latim',
        exemplo: 'Foi impetrado habeas corpus perante o STJ em favor do paciente preso preventivamente há mais de 180 dias.',
    },
    {
        termo: 'habeas data',
        significado: 'Que tenhas os dados.',
        uso: 'Ação constitucional para garantir acesso ou retificação de dados pessoais em registros públicos.',
        area: ['constitucional', 'administrativo'],
        origem: 'latim',
        exemplo: 'O habeas data foi utilizado para retificar informações incorretas constantes no cadastro do SPC.',
    },
    {
        termo: 'in casu',
        significado: 'No caso presente; neste caso.',
        uso: 'Referência ao caso concreto em análise, diferenciando de hipóteses abstratas.',
        area: ['processual', 'forense'],
        origem: 'latim',
        sinonimos: ['no caso em tela', 'no caso concreto'],
        exemplo: 'In casu, a conduta do réu não se subsume ao tipo penal descrito na denúncia.',
    },
    {
        termo: 'in dubio pro reo',
        significado: 'Na dúvida, em favor do réu.',
        uso: 'Princípio penal: havendo dúvida sobre a culpabilidade, decide-se a favor do acusado.',
        area: ['penal', 'processual penal'],
        origem: 'latim',
        sinonimos: ['favor rei'],
        exemplo: 'Aplicando o princípio in dubio pro reo, o juiz absolveu o réu por insuficiência de provas.',
    },
    {
        termo: 'in dubio pro operario',
        significado: 'Na dúvida, em favor do trabalhador.',
        uso: 'Princípio trabalhista: havendo dúvida na interpretação, prevalece a mais favorável ao empregado.',
        area: ['trabalhista'],
        origem: 'latim',
        sinonimos: ['in dubio pro misero'],
        exemplo: 'Diante da ambiguidade da cláusula contratual, aplicou-se o in dubio pro operario para reconhecer o adicional.',
    },
    {
        termo: 'in limine',
        significado: 'No limiar; desde logo.',
        uso: 'Decisão tomada de plano, sem ouvir a parte contrária, normalmente em tutelas de urgência.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['liminarmente', 'de plano'],
        exemplo: 'O pedido de tutela de urgência foi deferido in limine, antes da citação do réu.',
    },
    {
        termo: 'inter partes',
        significado: 'Entre as partes.',
        uso: 'Efeito limitado às partes do processo, sem vincular terceiros.',
        area: ['processual', 'civil'],
        origem: 'latim',
        exemplo: 'A sentença em ação individual produz efeitos apenas inter partes, não beneficiando outros consumidores.',
    },
    {
        termo: 'juris tantum',
        significado: 'Apenas de direito; presunção relativa.',
        uso: 'Presunção legal que admite prova em contrário.',
        area: ['processual', 'civil'],
        origem: 'latim',
        sinonimos: ['presunção relativa'],
        exemplo: 'A presunção de veracidade dos atos administrativos é juris tantum, podendo ser elidida por prova robusta.',
    },
    {
        termo: 'jus postulandi',
        significado: 'Direito de postular em juízo.',
        uso: 'Capacidade de peticionar diretamente, sem advogado, em certos ritos (ex.: Justiça do Trabalho).',
        area: ['processual', 'trabalhista'],
        origem: 'latim',
        exemplo: 'Na Justiça do Trabalho, a parte pode exercer o jus postulandi e ajuizar reclamação sem advogado.',
    },
    {
        termo: 'lato sensu',
        significado: 'Em sentido amplo.',
        uso: 'Interpretação extensiva de conceito ou norma.',
        area: ['civil', 'constitucional', 'hermenêutica'],
        origem: 'latim',
        sinonimos: ['em sentido amplo'],
        exemplo: 'Propriedade, em sentido lato sensu, abrange não só bens imóveis mas todo o patrimônio do indivíduo.',
    },
    {
        termo: 'lex specialis derogat legi generali',
        significado: 'A lei especial derroga a lei geral.',
        uso: 'Princípio de solução de antinomias: norma específica prevalece sobre genérica.',
        area: ['hermenêutica', 'constitucional'],
        origem: 'latim',
        exemplo: 'O CDC, como lex specialis, prevalece sobre o Código Civil nas relações de consumo, conforme o princípio lex specialis derogat legi generali.',
    },
    {
        termo: 'litis consórcio',
        significado: 'Comunhão na lide; pluralidade de partes.',
        uso: 'Situação em que duas ou mais pessoas figuram no mesmo polo processual.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['litisconsórcio'],
        exemplo: 'Formou-se litisconsórcio passivo necessário entre os três réus solidariamente responsáveis pelo dano.',
    },
    {
        termo: 'mandamus',
        significado: 'Nós ordenamos; mandado.',
        uso: 'Referência ao mandado de segurança, remédio constitucional contra ato ilegal de autoridade.',
        area: ['constitucional', 'administrativo'],
        origem: 'latim',
        sinonimos: ['mandado de segurança'],
        exemplo: 'O mandamus foi concedido para garantir a matrícula do impetrante na universidade pública.',
    },
    {
        termo: 'modus operandi',
        significado: 'Modo de operar; maneira de agir.',
        uso: 'Padrão de conduta ou método utilizado na prática de atos, especialmente criminosos.',
        area: ['penal', 'criminologia'],
        origem: 'latim',
        exemplo: 'O modus operandi das fraudes era sempre o mesmo: falsificação de assinaturas em contratos bancários.',
    },
    {
        termo: 'nulla poena sine lege',
        significado: 'Não há pena sem lei.',
        uso: 'Princípio da legalidade penal: só se pode punir conduta previamente tipificada em lei.',
        area: ['penal', 'constitucional'],
        origem: 'latim',
        sinonimos: ['princípio da legalidade'],
        exemplo: 'Em razão do princípio nulla poena sine lege, a conduta atípica não pode ser objeto de sanção penal.',
    },
    {
        termo: 'onus probandi',
        significado: 'Ônus da prova.',
        uso: 'Encargo de provar determinado fato alegado no processo.',
        area: ['processual', 'civil'],
        origem: 'latim',
        sinonimos: ['ônus da prova', 'encargo probatório'],
        exemplo: 'O onus probandi incumbe ao autor quanto ao fato constitutivo e ao réu quanto ao fato extintivo do direito.',
    },
    {
        termo: 'pacta sunt servanda',
        significado: 'Os pactos devem ser cumpridos.',
        uso: 'Princípio da força obrigatória dos contratos.',
        area: ['civil', 'contratos', 'internacional'],
        origem: 'latim',
        sinonimos: ['força obrigatória dos contratos'],
        exemplo: 'Pelo princípio pacta sunt servanda, as cláusulas contratuais devem ser cumpridas como se lei fossem entre as partes.',
    },
    {
        termo: 'periculum in mora',
        significado: 'Perigo na demora.',
        uso: 'Risco de dano irreparável caso a tutela jurisdicional não seja concedida com urgência.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['risco de dano', 'perigo de demora'],
        exemplo: 'O periculum in mora restou demonstrado pelo risco de alienação dos bens antes do julgamento definitivo.',
    },
    {
        termo: 'per fas et nefas',
        significado: 'Por meios lícitos ou ilícitos; a qualquer custo.',
        uso: 'Expressão usada para indicar que alguém busca resultado sem respeitar limites legais ou morais.',
        area: ['penal', 'forense'],
        origem: 'latim',
        exemplo: 'O réu tentou per fas et nefas obter a absolvição, inclusive intimidando testemunhas.',
    },
    {
        termo: 'prima facie',
        significado: 'À primeira vista.',
        uso: 'Avaliação preliminar antes de análise aprofundada; aparência de verossimilhança.',
        area: ['processual', 'civil'],
        origem: 'latim',
        sinonimos: ['à primeira vista', 'aparentemente'],
        exemplo: 'Prima facie, a documentação apresentada demonstra o direito alegado pelo autor.',
    },
    {
        termo: 'quantum debeatur',
        significado: 'Quanto é devido.',
        uso: 'Apuração do valor exato da condenação, normalmente em fase de liquidação.',
        area: ['processual', 'civil'],
        origem: 'latim',
        sinonimos: ['valor devido'],
        exemplo: 'A sentença reconheceu o an debeatur; resta agora apurar o quantum debeatur em liquidação.',
    },
    {
        termo: 'rebus sic stantibus',
        significado: 'Estando assim as coisas; enquanto as coisas permanecerem como estão.',
        uso: 'Cláusula implícita que permite revisão contratual por onerosidade excessiva.',
        area: ['civil', 'contratos'],
        origem: 'latim',
        sinonimos: ['teoria da imprevisão'],
        exemplo: 'Com base na cláusula rebus sic stantibus, o contrato foi revisto após a desvalorização cambial abrupta.',
    },
    {
        termo: 'res judicata',
        significado: 'Coisa julgada.',
        uso: 'Decisão judicial definitiva, da qual não cabe mais recurso.',
        area: ['processual', 'constitucional'],
        origem: 'latim',
        sinonimos: ['coisa julgada'],
        exemplo: 'A matéria está coberta pela res judicata, sendo vedado rediscuti-la em novo processo.',
    },
    {
        termo: 'sine qua non',
        significado: 'Sem a qual não; condição indispensável.',
        uso: 'Requisito essencial para a existência ou validade de algo.',
        area: ['penal', 'civil', 'processual'],
        origem: 'latim',
        sinonimos: ['condição essencial', 'requisito indispensável'],
        exemplo: 'A citação válida é condição sine qua non para a formação da relação processual.',
    },
    {
        termo: 'stare decisis',
        significado: 'Manter o que foi decidido; respeitar os precedentes.',
        uso: 'Princípio de vinculação aos precedentes judiciais, especialmente em sistemas de common law.',
        area: ['processual', 'constitucional'],
        origem: 'latim',
        sinonimos: ['doutrina dos precedentes'],
        exemplo: 'O CPC/2015 fortaleceu o stare decisis ao criar um sistema de precedentes vinculantes no direito brasileiro.',
    },
    {
        termo: 'stricto sensu',
        significado: 'Em sentido estrito; em sentido restrito.',
        uso: 'Interpretação restritiva de termo ou norma.',
        area: ['hermenêutica', 'civil', 'constitucional'],
        origem: 'latim',
        sinonimos: ['em sentido estrito'],
        exemplo: 'Recurso stricto sensu é aquele com hipóteses de cabimento taxativamente previstas em lei.',
    },
    {
        termo: 'sub judice',
        significado: 'Sob julgamento; em análise pelo juiz.',
        uso: 'Indica que a matéria ainda está pendente de decisão judicial.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['em julgamento', 'pendente'],
        exemplo: 'A questão permanece sub judice, aguardando pronunciamento do tribunal sobre o recurso interposto.',
    },
    {
        termo: 'sui generis',
        significado: 'De seu próprio gênero; único.',
        uso: 'Indica algo que não se enquadra em categorias jurídicas tradicionais.',
        area: ['civil', 'administrativo', 'constitucional'],
        origem: 'latim',
        sinonimos: ['único', 'singular', 'peculiar'],
        exemplo: 'A natureza jurídica da fundação pública é sui generis, não se enquadrando perfeitamente como pessoa de direito público ou privado.',
    },
    {
        termo: 'ultra petita',
        significado: 'Além do pedido.',
        uso: 'Decisão que concede mais do que foi pedido pela parte, sendo nula nesse excesso.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['além do pedido'],
        exemplo: 'A sentença foi reformada por julgar ultra petita, concedendo indenização moral não requerida na inicial.',
    },

    // ── Novos termos ────────────────────────────────────────────────────
    {
        termo: 'actio nata',
        significado: 'Ação nascida; surgimento da pretensão.',
        uso: 'Teoria segundo a qual a prescrição só começa a correr quando nasce a pretensão (violação do direito).',
        area: ['civil', 'processual'],
        origem: 'latim',
        exemplo: 'Pela teoria da actio nata, o prazo prescricional para cobrar indenização iniciou-se na data do acidente.',
    },
    {
        termo: 'actio pauliana',
        significado: 'Ação pauliana; ação revocatória.',
        uso: 'Ação que visa anular atos praticados em fraude contra credores.',
        area: ['civil', 'empresarial'],
        origem: 'latim',
        sinonimos: ['ação revocatória', 'fraude contra credores'],
        exemplo: 'O credor ajuizou actio pauliana para anular a doação de imóvel feita pelo devedor insolvente.',
    },
    {
        termo: 'animus domini',
        significado: 'Intenção de dono; ânimo de proprietário.',
        uso: 'Elemento subjetivo da posse que a qualifica para fins de usucapião.',
        area: ['civil', 'reais'],
        origem: 'latim',
        sinonimos: ['ânimo de dono'],
        exemplo: 'Para a usucapião extraordinária, exige-se posse contínua com animus domini por 15 anos.',
    },
    {
        termo: 'audiatur et altera pars',
        significado: 'Ouça-se também a outra parte.',
        uso: 'Princípio do contraditório: ambas as partes devem ser ouvidas antes da decisão.',
        area: ['processual', 'constitucional'],
        origem: 'latim',
        sinonimos: ['contraditório', 'ampla defesa'],
        exemplo: 'O juiz determinou a intimação do réu, assegurando o audiatur et altera pars antes de decidir o pedido liminar.',
    },
    {
        termo: 'bona fides',
        significado: 'Boa-fé.',
        uso: 'Princípio que exige lealdade, honestidade e confiança nas relações jurídicas.',
        area: ['civil', 'contratos', 'consumidor'],
        origem: 'latim',
        sinonimos: ['boa-fé objetiva'],
        exemplo: 'A cláusula abusiva foi declarada nula por violação ao princípio da bona fides nas relações de consumo.',
    },
    {
        termo: 'conditio sine qua non',
        significado: 'Condição sem a qual não; causa necessária.',
        uso: 'Teoria da equivalência dos antecedentes causais no nexo de causalidade penal.',
        area: ['penal'],
        origem: 'latim',
        sinonimos: ['equivalência dos antecedentes'],
        exemplo: 'Pelo critério da conditio sine qua non, elimina-se mentalmente a conduta para verificar se o resultado teria ocorrido.',
    },
    {
        termo: 'damnum emergens',
        significado: 'Dano emergente; prejuízo efetivo.',
        uso: 'Parcela da indenização correspondente ao prejuízo concretamente sofrido.',
        area: ['civil', 'responsabilidade civil'],
        origem: 'latim',
        sinonimos: ['dano emergente', 'prejuízo efetivo'],
        exemplo: 'O damnum emergens foi calculado com base no valor de mercado do veículo destruído no acidente.',
    },
    {
        termo: 'de lege ferenda',
        significado: 'Da lei a ser feita; em termos de direito futuro.',
        uso: 'Análise de como o direito deveria ser, em perspectiva de reforma legislativa.',
        area: ['hermenêutica', 'constitucional'],
        origem: 'latim',
        exemplo: 'De lege ferenda, seria desejável a criação de varas especializadas em crimes cibernéticos.',
    },
    {
        termo: 'de lege lata',
        significado: 'Da lei posta; do direito vigente.',
        uso: 'Análise do direito como ele é atualmente, conforme a legislação em vigor.',
        area: ['hermenêutica', 'constitucional'],
        origem: 'latim',
        exemplo: 'De lege lata, não há previsão de responsabilidade penal da pessoa jurídica por crimes contra a honra.',
    },
    {
        termo: 'exceptio non adimpleti contractus',
        significado: 'Exceção do contrato não cumprido.',
        uso: 'Defesa pela qual uma parte se recusa a cumprir sua obrigação enquanto a outra não cumpre a sua.',
        area: ['civil', 'contratos'],
        origem: 'latim',
        sinonimos: ['exceção de contrato não cumprido'],
        exemplo: 'O locatário opôs exceptio non adimpleti contractus, recusando o pagamento enquanto o locador não realizasse os reparos devidos.',
    },
    {
        termo: 'favor rei',
        significado: 'Em favor do réu.',
        uso: 'Princípio de que, na dúvida, a interpretação deve favorecer o acusado.',
        area: ['penal', 'processual penal'],
        origem: 'latim',
        sinonimos: ['in dubio pro reo'],
        exemplo: 'Em caso de conflito entre normas penais, aplica-se o favor rei para adotar a mais benigna ao acusado.',
    },
    {
        termo: 'in dubio pro misero',
        significado: 'Na dúvida, em favor do mais fraco.',
        uso: 'Princípio de proteção ao hipossuficiente, especialmente em direito do trabalho e previdenciário.',
        area: ['trabalhista', 'previdenciário'],
        origem: 'latim',
        sinonimos: ['in dubio pro operario'],
        exemplo: 'O tribunal aplicou o in dubio pro misero para reconhecer o benefício previdenciário ao segurado.',
    },
    {
        termo: 'in personam',
        significado: 'Contra a pessoa; de caráter pessoal.',
        uso: 'Ação ou direito que se exerce contra pessoa determinada, não contra a coisa.',
        area: ['processual', 'civil'],
        origem: 'latim',
        exemplo: 'A obrigação de fazer é direito in personam, exigível apenas do devedor, não de terceiros.',
    },
    {
        termo: 'in rem',
        significado: 'Contra a coisa; de caráter real.',
        uso: 'Ação ou direito exercido sobre a coisa, oponível a todos.',
        area: ['civil', 'reais', 'processual'],
        origem: 'latim',
        sinonimos: ['direito real'],
        exemplo: 'O direito de propriedade é in rem, podendo ser exercido erga omnes contra qualquer violador.',
    },
    {
        termo: 'jura novit curia',
        significado: 'O tribunal conhece o direito.',
        uso: 'Princípio de que o juiz não está vinculado à fundamentação jurídica das partes, podendo aplicar o direito de ofício.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['iura novit curia', 'o juiz conhece o direito'],
        exemplo: 'Pelo princípio jura novit curia, o juiz requalificou o pedido e aplicou a norma correta, ainda que não invocada pela parte.',
    },
    {
        termo: 'lex loci',
        significado: 'Lei do lugar.',
        uso: 'Princípio de direito internacional privado que aplica a lei do local onde o fato ocorreu.',
        area: ['internacional privado', 'civil'],
        origem: 'latim',
        sinonimos: ['lei do local'],
        exemplo: 'Conforme a regra lex loci, aplica-se a legislação brasileira ao acidente ocorrido em território nacional.',
    },
    {
        termo: 'lucrum cessans',
        significado: 'Lucro cessante; ganho frustrado.',
        uso: 'Parcela da indenização referente ao lucro que a vítima razoavelmente deixou de auferir.',
        area: ['civil', 'responsabilidade civil'],
        origem: 'latim',
        sinonimos: ['lucro cessante', 'lucros cessantes'],
        exemplo: 'O lucrum cessans foi fixado com base na média de faturamento mensal da empresa nos seis meses anteriores ao sinistro.',
    },
    {
        termo: 'ne bis in idem',
        significado: 'Não duas vezes pelo mesmo; vedação da dupla persecução.',
        uso: 'Proibição de processar ou punir alguém duas vezes pelos mesmos fatos (variante de bis in idem).',
        area: ['penal', 'processual penal', 'internacional'],
        origem: 'latim',
        sinonimos: ['bis in idem', 'vedação de dupla punição'],
        exemplo: 'O STF reconheceu a aplicação do ne bis in idem para impedir novo julgamento do réu já absolvido pelo mesmo fato.',
    },
    {
        termo: 'nemo tenetur se detegere',
        significado: 'Ninguém é obrigado a se autoincriminar.',
        uso: 'Direito ao silêncio e à não autoincriminação do acusado em processo penal.',
        area: ['penal', 'constitucional', 'processual penal'],
        origem: 'latim',
        sinonimos: ['direito ao silêncio', 'não autoincriminação'],
        exemplo: 'Com base no nemo tenetur se detegere, o réu não pode ser compelido a produzir prova contra si mesmo, como soprar etilômetro.',
    },
    {
        termo: 'reformatio in pejus',
        significado: 'Reforma para pior.',
        uso: 'Proibição de o tribunal piorar a situação do recorrente em recurso exclusivo.',
        area: ['processual', 'penal', 'processual penal'],
        origem: 'latim',
        sinonimos: ['proibição de reforma em prejuízo'],
        exemplo: 'O tribunal não pode aumentar a pena em recurso exclusivo da defesa, em razão da vedação à reformatio in pejus.',
    },
    {
        termo: 'tantum devolutum quantum appellatum',
        significado: 'Tanto é devolvido quanto é apelado.',
        uso: 'O tribunal só pode julgar as matérias impugnadas no recurso, respeitando seus limites.',
        area: ['processual'],
        origem: 'latim',
        sinonimos: ['efeito devolutivo'],
        exemplo: 'Pelo princípio tantum devolutum quantum appellatum, o TJ analisou apenas os capítulos da sentença impugnados na apelação.',
    },
    {
        termo: 'venire contra factum proprium',
        significado: 'Ir contra o próprio fato; proibição de comportamento contraditório.',
        uso: 'Vedação de conduta que contradiz comportamento anterior da mesma parte, violando a boa-fé.',
        area: ['civil', 'contratos', 'processual'],
        origem: 'latim',
        sinonimos: ['proibição de comportamento contraditório', 'nemo potest venire contra factum proprium'],
        exemplo: 'O tribunal aplicou o venire contra factum proprium ao réu que, após aceitar o contrato por anos, alegou sua nulidade quando lhe tornou desfavorável.',
    },
    {
        termo: 'nullum crimen sine lege',
        significado: 'Não há crime sem lei anterior que o defina.',
        uso: 'Princípio da legalidade estrita em matéria penal, garantia fundamental do acusado.',
        area: ['penal', 'constitucional'],
        origem: 'latim',
        sinonimos: ['princípio da reserva legal', 'legalidade penal'],
        exemplo: 'A conduta não pode ser punida porque, à época dos fatos, não havia tipificação legal, em respeito ao nullum crimen sine lege.',
    },
    {
        termo: 'mens rea',
        significado: 'Mente culpada; elemento subjetivo do crime.',
        uso: 'Componente psicológico do delito: dolo ou culpa do agente.',
        area: ['penal'],
        origem: 'latim',
        sinonimos: ['elemento subjetivo', 'culpabilidade'],
        exemplo: 'A acusação não logrou provar a mens rea do agente, resultando em absolvição por ausência de dolo.',
    },
    {
        termo: 'actio libera in causa',
        significado: 'Ação livre na causa.',
        uso: 'Teoria que responsabiliza o agente que se coloca voluntariamente em estado de inimputabilidade antes de cometer o crime.',
        area: ['penal'],
        origem: 'latim',
        exemplo: 'Pela teoria da actio libera in causa, o réu que se embriagou propositalmente para cometer o crime responde como imputável.',
    },
];
