import type { LegalTerm } from './types';

/**
 * Glossário — Direito Penal.
 */
export const PENAL: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'tipicidade', significado: 'Adequação da conduta ao tipo penal descrito em lei.', uso: 'Elemento do fato típico — a conduta deve se encaixar na norma.', area: ['penal'], exemplo: 'A conduta do réu não se amolda ao tipo penal do art. 155 do CP.' },
    { termo: 'antijuridicidade', significado: 'Contrariedade da conduta ao ordenamento jurídico.', uso: 'Segundo elemento do crime — ausente em caso de excludentes.', area: ['penal'], sinonimos: ['ilicitude'], exemplo: 'A legítima defesa exclui a antijuridicidade da conduta.' },
    { termo: 'culpabilidade', significado: 'Reprovabilidade da conduta do agente.', uso: 'Terceiro elemento do crime — imputabilidade, potencial consciência, exigibilidade.', area: ['penal'], exemplo: 'A inimputabilidade do réu afasta a culpabilidade.' },
    { termo: 'dolo eventual', significado: 'Quando o agente assume o risco de produzir o resultado.', uso: 'Distinto do dolo direto — não quer, mas aceita o resultado.', area: ['penal'], exemplo: 'O condutor embriagado agiu com dolo eventual.' },
    { termo: 'culpa consciente', significado: 'Quando o agente prevê o resultado mas confia que não ocorrerá.', uso: 'Diferencia-se do dolo eventual pela confiança sincera na não-ocorrência.', area: ['penal'], exemplo: 'Trata-se de culpa consciente, não de dolo eventual.' },
    { termo: 'legítima defesa', significado: 'Repulsa a agressão injusta, atual ou iminente, a direito próprio ou alheio.', uso: 'Excludente de ilicitude (art. 25, CP).', area: ['penal'], exemplo: 'O réu agiu em legítima defesa, nos termos do art. 25 do CP.' },
    { termo: 'estado de necessidade', significado: 'Sacrifício de bem jurídico para salvar outro em perigo atual.', uso: 'Excludente de ilicitude (art. 24, CP).', area: ['penal'], exemplo: 'Configurado o estado de necessidade, a conduta é lícita.' },
    { termo: 'dosimetria da pena', significado: 'Cálculo da pena aplicável ao condenado.', uso: 'Sistema trifásico: pena-base, atenuantes/agravantes, causas de aumento/diminuição.', area: ['penal'], exemplo: 'Na dosimetria, a pena-base foi fixada acima do mínimo legal.' },
    { termo: 'materialidade', significado: 'Comprovação da existência do crime.', uso: 'Elemento objetivo — o crime efetivamente ocorreu.', area: ['penal'], exemplo: 'A materialidade está comprovada pelo auto de corpo de delito.' },
    { termo: 'autoria', significado: 'Identificação de quem praticou o crime.', uso: 'Provas de que o acusado é o responsável pelo delito.', area: ['penal'], exemplo: 'A autoria foi confirmada por reconhecimento fotográfico e testemunhal.' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'tentativa', significado: 'Crime iniciado mas não consumado por circunstâncias alheias à vontade do agente.', uso: 'Reduz a pena de 1/3 a 2/3 (art. 14, II, CP).', area: ['penal'], exemplo: 'O homicídio restou na forma tentada, aplicando-se a redução do art. 14, II, CP.' },
    { termo: 'concurso de crimes', significado: 'Prática de mais de um crime pelo mesmo agente.', uso: 'Material (ações distintas), formal (ação única, vários resultados) ou continuado.', area: ['penal'], exemplo: 'Configurado o concurso material de crimes, as penas devem ser somadas.' },
    { termo: 'crime continuado', significado: 'Pluralidade de crimes da mesma espécie como se fossem um único crime.', uso: 'Aplica-se a pena mais grave aumentada de 1/6 a 2/3 (art. 71, CP).', area: ['penal'], exemplo: 'Os furtos reiterados configuram crime continuado.' },
    { termo: 'coautoria', significado: 'Participação conjunta de duas ou mais pessoas na execução do crime.', uso: 'Todos os coautores respondem pelo crime na medida de sua culpabilidade.', area: ['penal'], exemplo: 'Restou comprovada a coautoria entre os réus na prática do roubo.' },
    { termo: 'partícipe', significado: 'Quem concorre para o crime sem executar diretamente a conduta típica.', uso: 'Contribui por induzimento, instigação ou auxílio.', area: ['penal'], exemplo: 'O partícipe responde na medida de sua culpabilidade (art. 29, §1º, CP).' },
    { termo: 'prescrição penal', significado: 'Perda do direito de punir ou executar a pena pelo decurso do tempo.', uso: 'Pode ser da pretensão punitiva ou executória.', area: ['penal'], exemplo: 'Reconhece-se a prescrição da pretensão punitiva retroativa.' },
    { termo: 'sursis', significado: 'Suspensão condicional da pena.', uso: 'Pena privativa de liberdade substituída por condições (art. 77, CP).', area: ['penal'], exemplo: 'Concedido o sursis pelo período de 2 anos.' },
    { termo: 'livramento condicional', significado: 'Liberação antecipada do condenado mediante condições.', uso: 'Exige cumprimento de fração da pena e bom comportamento.', area: ['penal'], exemplo: 'O apenado faz jus ao livramento condicional após cumprir 1/3 da pena.' },
    { termo: 'regime semiaberto', significado: 'Regime de cumprimento de pena intermediário.', uso: 'Permite trabalho externo e frequência a cursos.', area: ['penal'], exemplo: 'O condenado iniciou o cumprimento da pena em regime semiaberto.' },
    { termo: 'progressão de regime', significado: 'Passagem de regime mais rigoroso para menos rigoroso.', uso: 'Exige cumprimento de fração da pena e bom comportamento.', area: ['penal'], exemplo: 'Requer-se a progressão do regime fechado para o semiaberto.' },
    { termo: 'inquérito policial', significado: 'Procedimento investigativo conduzido pela autoridade policial.', uso: 'Apura infração penal e sua autoria para subsidiar a ação penal.', area: ['penal'], sinonimos: ['IP'], exemplo: 'O inquérito policial foi instaurado para apurar o crime de estelionato.' },
    { termo: 'denúncia', significado: 'Peça inicial da ação penal pública oferecida pelo MP.', uso: 'Narra o fato criminoso e requer a condenação do acusado.', area: ['penal'], exemplo: 'O Ministério Público ofereceu denúncia em face do investigado.' },
    { termo: 'queixa-crime', significado: 'Peça inicial da ação penal privada oferecida pelo ofendido.', uso: 'Crimes de ação penal privada exigem iniciativa da vítima.', area: ['penal'], exemplo: 'A queixa-crime foi oferecida no prazo decadencial de 6 meses.' },
    { termo: 'absolvição sumária', significado: 'Absolvição antecipada antes da instrução processual.', uso: 'Quando evidente causa de exclusão de ilicitude ou culpabilidade (art. 397, CPP).', area: ['penal'], exemplo: 'O réu foi absolvido sumariamente por manifesta atipicidade da conduta.' },
    { termo: 'pronúncia', significado: 'Decisão que submete o acusado a julgamento pelo Tribunal do Júri.', uso: 'Exige indícios suficientes de autoria e prova da materialidade.', area: ['penal'], exemplo: 'O juiz pronunciou o réu pelo crime de homicídio qualificado.' },
    { termo: 'impronúncia', significado: 'Decisão que encerra o processo por insuficiência de provas.', uso: 'Não impede nova ação se surgirem novas provas.', area: ['penal'], exemplo: 'Decretada a impronúncia por insuficiência de provas da autoria.' },
    { termo: 'excludente de ilicitude', significado: 'Circunstância que torna lícita conduta tipicamente criminosa.', uso: 'Legítima defesa, estado de necessidade, estrito cumprimento do dever legal, exercício regular do direito.', area: ['penal'], exemplo: 'A conduta do réu está amparada por excludente de ilicitude.' },
    { termo: 'medida de segurança', significado: 'Sanção penal aplicada ao inimputável.', uso: 'Internação ou tratamento ambulatorial por prazo indeterminado.', area: ['penal'], exemplo: 'Aplicou-se medida de segurança de internação ao réu inimputável.' },
    { termo: 'prisão preventiva', significado: 'Prisão cautelar decretada antes da sentença condenatória.', uso: 'Exige pressupostos de garantia da ordem pública, aplicação da lei penal etc.', area: ['penal'], exemplo: 'A prisão preventiva foi decretada para garantia da ordem pública.' },
    { termo: 'fiança criminal', significado: 'Caução em dinheiro para liberdade provisória.', uso: 'Concedida pela autoridade policial ou pelo juiz (arts. 322-350, CPP).', area: ['penal'], exemplo: 'A fiança foi fixada em 50 salários mínimos.' },
    { termo: 'acordo de não persecução penal', significado: 'Acordo entre MP e investigado para não oferecer denúncia.', uso: 'Exige confissão e cumprimento de condições (art. 28-A, CPP).', area: ['penal'], sinonimos: ['ANPP'], exemplo: 'Foi celebrado acordo de não persecução penal com prestação de serviços.' },
    { termo: 'colaboração premiada', significado: 'Acordo em que o investigado coopera com a investigação em troca de benefícios penais.', uso: 'Prevista na Lei 12.850/2013 para organizações criminosas.', area: ['penal'], sinonimos: ['delação premiada'], exemplo: 'A colaboração premiada revelou o esquema de corrupção.' },
    { termo: 'transação penal', significado: 'Acordo entre MP e autor do fato em infrações de menor potencial ofensivo.', uso: 'Aplicação imediata de pena restritiva de direitos ou multa (art. 76, Lei 9.099).', area: ['penal'], exemplo: 'Proposta a transação penal consistente em prestação pecuniária.' },
    { termo: 'tipo penal', significado: 'Descrição abstrata da conduta criminosa na lei.', uso: 'Modelo legal ao qual a conduta concreta deve se adequar.', area: ['penal'], exemplo: 'A conduta não se subsume ao tipo penal do art. 171 do CP (estelionato).' },
    { termo: 'qualificadora', significado: 'Circunstância que agrava o crime e estabelece nova faixa de pena.', uso: 'Altera os limites mínimo e máximo da pena cominada.', area: ['penal'], exemplo: 'O homicídio foi qualificado pelo motivo fútil (art. 121, §2º, II, CP).' },
];
