import type { LegalTerm } from './types';

/**
 * Glossário — Direito Previdenciário.
 */
export const PREVIDENCIARIO: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'carência', significado: 'Número mínimo de contribuições para ter direito ao benefício.', uso: 'Ex: aposentadoria por idade exige 180 contribuições.', area: ['previdenciario'], exemplo: 'O segurado cumpriu a carência exigida de 180 contribuições.' },
    { termo: 'qualidade de segurado', significado: 'Vínculo jurídico com o INSS que garante proteção previdenciária.', uso: 'Mantida durante emprego e no período de graça.', area: ['previdenciario'], exemplo: 'O autor mantinha a qualidade de segurado na data do sinistro.' },
    { termo: 'aposentadoria especial', significado: 'Aposentadoria com tempo reduzido por exposição a agentes nocivos.', uso: 'Atividades com exposição a insalubridade/periculosidade.', area: ['previdenciario'], exemplo: 'Requer-se a concessão de aposentadoria especial (art. 57, Lei 8.213/91).' },
    { termo: 'auxílio-doença', significado: 'Benefício por incapacidade temporária para o trabalho.', uso: 'Exige carência de 12 contribuições (regra geral).', area: ['previdenciario'], sinonimos: ['benefício por incapacidade temporária'], exemplo: 'O auxílio-doença foi indevidamente cessado pelo INSS.' },
    { termo: 'período de graça', significado: 'Período em que a qualidade de segurado é mantida após cessação de contribuições.', uso: '12 meses (regra geral), extensível a 24 ou 36 meses.', area: ['previdenciario'], exemplo: 'O segurado encontrava-se no período de graça quando da ocorrência do evento.' },
    { termo: 'BPC/LOAS', significado: 'Benefício de Prestação Continuada da Lei Orgânica de Assistência Social.', uso: 'Benefício assistencial a idosos e deficientes em situação de miserabilidade.', area: ['previdenciario'], exemplo: 'Requer-se a concessão do BPC/LOAS (art. 20, Lei 8.742/93).' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'aposentadoria por idade', significado: 'Benefício concedido ao segurado que atinge a idade mínima e carência.', uso: 'Idade mínima: 65 anos (homem) e 62 anos (mulher) — EC 103/2019.', area: ['previdenciario'], exemplo: 'A segurada preencheu os requisitos para aposentadoria por idade.' },
    { termo: 'aposentadoria por tempo de contribuição', significado: 'Benefício concedido pelo tempo mínimo de contribuição.', uso: 'Regra de transição após a EC 103/2019 — pontos, pedágio.', area: ['previdenciario'], exemplo: 'O segurado se enquadra na regra de transição por pontos.' },
    { termo: 'aposentadoria por invalidez', significado: 'Benefício por incapacidade permanente e total para o trabalho.', uso: 'Convertida de auxílio-doença quando a incapacidade se torna definitiva.', area: ['previdenciario'], sinonimos: ['aposentadoria por incapacidade permanente'], exemplo: 'A perícia atestou incapacidade permanente para qualquer atividade laboral.' },
    { termo: 'pensão por morte', significado: 'Benefício aos dependentes do segurado falecido.', uso: 'Valor e duração variam conforme a condição do dependente (art. 74, Lei 8.213).', area: ['previdenciario'], exemplo: 'A viúva requer pensão por morte do segurado falecido.' },
    { termo: 'auxílio-acidente', significado: 'Indenização por sequela de acidente que reduz capacidade laboral.', uso: 'Natureza indenizatória, pago até a aposentadoria.', area: ['previdenciario'], exemplo: 'O auxílio-acidente é devido pela redução permanente da capacidade de trabalho.' },
    { termo: 'salário-maternidade', significado: 'Benefício pago durante o afastamento por parto, adoção ou aborto.', uso: 'Duração de 120 dias, pago pela empresa com compensação pelo INSS.', area: ['previdenciario', 'trabalhista'], exemplo: 'A segurada empregada tem direito a 120 dias de salário-maternidade.' },
    { termo: 'PPP', significado: 'Perfil Profissiográfico Previdenciário — documento com histórico laboral do trabalhador.', uso: 'Essencial para comprovação de atividade especial.', area: ['previdenciario'], exemplo: 'O PPP comprova a exposição a agentes nocivos durante todo o contrato.' },
    { termo: 'LTCAT', significado: 'Laudo Técnico de Condições Ambientais do Trabalho.', uso: 'Documento técnico que subsidia o PPP para aposentadoria especial.', area: ['previdenciario'], exemplo: 'O LTCAT atestou exposição a ruído acima do limite de tolerância.' },
    { termo: 'conversão de tempo especial', significado: 'Transformação de período de atividade especial em tempo comum.', uso: 'Fator multiplicador de 1,4 (homem) ou 1,2 (mulher) para 25 anos.', area: ['previdenciario'], exemplo: 'Requer-se a conversão de tempo especial em comum pelo fator 1,4.' },
    { termo: 'CNIS', significado: 'Cadastro Nacional de Informações Sociais — registro de vínculos e contribuições.', uso: 'Base de dados do INSS que registra o histórico contributivo.', area: ['previdenciario'], exemplo: 'O CNIS não registra as contribuições do período de 2015 a 2018.' },
    { termo: 'revisão de benefício', significado: 'Pedido para recalcular valor de benefício previdenciário.', uso: 'Prazo decadencial de 10 anos do primeiro pagamento (art. 103, Lei 8.213).', area: ['previdenciario'], exemplo: 'Requer-se a revisão do benefício com inclusão dos salários de contribuição omitidos.' },
    { termo: 'desaposentação', significado: 'Renúncia à aposentadoria para obter outra mais vantajosa.', uso: 'STF decidiu pela impossibilidade (RE 661.256/SC).', area: ['previdenciario'], exemplo: 'O STF julgou improcedente o pedido de desaposentação.' },
    { termo: 'atividade concomitante', significado: 'Exercício simultâneo de mais de uma atividade remunerada.', uso: 'Soma dos salários de contribuição para cálculo do benefício.', area: ['previdenciario'], exemplo: 'As atividades concomitantes devem ser consideradas no cálculo do benefício.' },
    { termo: 'segurado facultativo', significado: 'Pessoa sem atividade remunerada que contribui voluntariamente ao INSS.', uso: 'Estudantes, donas de casa, desempregados que optam por contribuir.', area: ['previdenciario'], exemplo: 'O segurado facultativo contribuiu com 20% sobre o salário mínimo.' },
    { termo: 'contribuinte individual', significado: 'Segurado obrigatório que trabalha por conta própria.', uso: 'Autônomos, profissionais liberais, sócios de empresa.', area: ['previdenciario'], exemplo: 'O contribuinte individual deve recolher mensalmente sua contribuição ao INSS.' },
    { termo: 'acidente de trabalho', significado: 'Evento que causa lesão corporal ou perturbação funcional durante o trabalho.', uso: 'Gera direito a benefícios acidentários sem exigência de carência.', area: ['previdenciario', 'trabalhista'], exemplo: 'O acidente de trabalho foi comunicado por CAT no prazo legal.' },
    { termo: 'CAT', significado: 'Comunicação de Acidente de Trabalho — documento obrigatório.', uso: 'Deve ser emitida pela empresa no primeiro dia útil após o acidente.', area: ['previdenciario', 'trabalhista'], sinonimos: ['comunicação de acidente de trabalho'], exemplo: 'A empresa não emitiu a CAT, devendo o sindicato fazê-lo.' },
    { termo: 'prova material', significado: 'Documento que comprova início de atividade (rural, especial etc.).', uso: 'Indispensável para reconhecimento de tempo de serviço (Súmula 149/STJ).', area: ['previdenciario'], exemplo: 'O segurado juntou certidão de casamento como início de prova material da atividade rural.' },
];
