import type { LegalTerm } from './types';

/**
 * Glossário — Direito Processual (jargão forense geral).
 */
export const PROCESSUAL: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'exordial', significado: 'Petição inicial.', uso: 'Designação formal da peça que inicia o processo.', area: ['processual'], sinonimos: ['peça vestibular', 'petição inaugural', 'peça de ingresso'], exemplo: 'Conforme narrado na exordial, o autor foi dispensado sem justa causa.' },
    { termo: 'decisum', significado: 'Parte dispositiva da sentença.', uso: 'Trecho da decisão que contém o comando judicial.', area: ['processual'], sinonimos: ['dispositivo'], exemplo: 'O decisum condenou a ré ao pagamento de R$ 50.000,00.' },
    { termo: 'r. sentença', significado: 'Respeitável sentença.', uso: 'Forma respeitosa de se referir à decisão de primeira instância.', area: ['processual'], exemplo: 'A r. sentença merece reforma pelos fundamentos a seguir.' },
    { termo: 'v. acórdão', significado: 'Venerável acórdão.', uso: 'Forma respeitosa de se referir à decisão colegiada.', area: ['processual'], exemplo: 'O v. acórdão divergiu da jurisprudência consolidada.' },
    { termo: 'preclusão', significado: 'Perda da faculdade processual por inércia, tempo ou consumação.', uso: 'Quando a parte perde o direito de praticar ato processual.', area: ['processual'], sinonimos: ['preclusão temporal', 'preclusão consumativa', 'preclusão lógica'], exemplo: 'Operou-se a preclusão temporal do direito de recorrer.' },
    { termo: 'coisa julgada', significado: 'Qualidade da decisão judicial da qual não cabe mais recurso.', uso: 'Imutabilidade e indiscutibilidade da decisão transitada em julgado.', area: ['processual'], exemplo: 'A matéria está acobertada pela coisa julgada material.' },
    { termo: 'trânsito em julgado', significado: 'Momento em que a decisão se torna irrecorrível.', uso: 'Quando não cabe mais nenhum recurso contra a decisão.', area: ['processual'], exemplo: 'A sentença transitou em julgado em 15/03/2026.' },
    { termo: 'tutela antecipada', significado: 'Decisão provisória que antecipa os efeitos da sentença.', uso: 'Concessão antecipada do pedido em situação de urgência.', area: ['processual'], sinonimos: ['tutela provisória', 'tutela de urgência'], exemplo: 'Requer-se a concessão de tutela antecipada nos termos do art. 300 do CPC.' },
    { termo: 'citação', significado: 'Ato pelo qual se dá ciência ao réu da existência do processo.', uso: 'Comunicação processual que constitui o réu em mora.', area: ['processual'], exemplo: 'Requer-se a citação do réu para contestar no prazo legal.' },
    { termo: 'intimação', significado: 'Ato pelo qual se dá ciência de atos processuais.', uso: 'Comunicação de despachos, decisões e sentenças.', area: ['processual'], exemplo: 'A intimação da sentença ocorreu em 10/03/2026.' },
    { termo: 'contestação', significado: 'Peça de defesa do réu em processo de conhecimento.', uso: 'Resposta do réu aos fatos e fundamentos da petição inicial.', area: ['processual'], exemplo: 'O réu apresentou contestação alegando prescrição.' },
    { termo: 'réplica', significado: 'Manifestação do autor sobre a contestação.', uso: 'Impugnação dos fatos e fundamentos novos trazidos pelo réu.', area: ['processual'], exemplo: 'Em réplica, o autor impugnou a alegação de prescrição.' },
    { termo: 'despacho saneador', significado: 'Decisão que organiza o processo para instrução.', uso: 'Resolve questões processuais pendentes e fixa pontos controvertidos.', area: ['processual'], sinonimos: ['decisão saneadora'], exemplo: 'No despacho saneador, o juiz fixou os pontos controvertidos.' },
    { termo: 'prova britânica', significado: 'Prova com registros invariáveis e inverossímeis.', uso: 'Cartões de ponto com horários idênticos todos os dias.', area: ['trabalhista', 'processual'], exemplo: 'Os controles de ponto constituem prova britânica, nos termos da Súmula 338 do TST.' },
    { termo: 'sucumbência', significado: 'Derrota na causa, total ou parcial.', uso: 'Parte vencida arca com custas e honorários.', area: ['processual'], exemplo: 'A ré arcará com honorários sucumbenciais de 15%.' },
    { termo: 'embargos', significado: 'Recurso ou ação que impugna decisão judicial.', uso: 'Podem ser de declaração, infringentes, de terceiro, à execução.', area: ['processual'], exemplo: 'Foram opostos embargos de declaração por omissão.' },
    { termo: 'agravo', significado: 'Recurso contra decisão interlocutória.', uso: 'Agravo de instrumento (art. 1.015 CPC) ou agravo interno.', area: ['processual'], exemplo: 'Interpôs agravo de instrumento contra a decisão que indeferiu a liminar.' },
    { termo: 'apelação', significado: 'Recurso contra sentença de primeira instância.', uso: 'Principal recurso ordinário no processo civil.', area: ['processual'], exemplo: 'A apelação foi interposta tempestivamente.' },
    { termo: 'liquidação de sentença', significado: 'Procedimento para apurar o valor exato da condenação.', uso: 'Quando a sentença é ilíquida e precisa de cálculos.', area: ['processual'], exemplo: 'A liquidação de sentença será feita por arbitramento.' },
    { termo: 'penhora', significado: 'Apreensão judicial de bens do devedor.', uso: 'Ato constritivo na fase de execução.', area: ['processual'], exemplo: 'Foi determinada a penhora de valores em conta bancária.' },
    { termo: 'arresto', significado: 'Apreensão cautelar de bens para garantir futura execução.', uso: 'Medida cautelar patrimonial preventiva.', area: ['processual'], exemplo: 'Requer-se o arresto cautelar dos bens do devedor.' },
    { termo: 'ação rescisória', significado: 'Ação para desconstituir decisão transitada em julgado.', uso: 'Cabível nas hipóteses do art. 966 do CPC.', area: ['processual'], exemplo: 'A ação rescisória fundamenta-se em erro de fato (art. 966, VIII, CPC).' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'conexão', significado: 'Vínculo entre ações com mesmo objeto ou causa de pedir.', uso: 'Determina reunião de processos para julgamento conjunto.', area: ['processual'], exemplo: 'Reconhecida a conexão, os processos foram reunidos perante o juízo prevento.' },
    { termo: 'continência', significado: 'Quando uma ação contém a outra por identidade de partes e causa.', uso: 'Espécie qualificada de conexão.', area: ['processual'], exemplo: 'Há continência entre as duas demandas, devendo ser reunidas.' },
    { termo: 'litispendência', significado: 'Existência de ação idêntica já em curso.', uso: 'Impede o processamento da segunda ação com mesmas partes, causa e pedido.', area: ['processual'], exemplo: 'A litispendência impõe a extinção do segundo processo (art. 337, §3º, CPC).' },
    { termo: 'revelia', significado: 'Ausência de contestação do réu no prazo legal.', uso: 'Gera presunção de veracidade dos fatos alegados pelo autor.', area: ['processual'], exemplo: 'Decretada a revelia, presumem-se verdadeiros os fatos da inicial.' },
    { termo: 'reconvenção', significado: 'Pedido do réu contra o autor dentro do mesmo processo.', uso: 'Contra-ataque processual apresentado na contestação (art. 343, CPC).', area: ['processual'], exemplo: 'O réu apresentou reconvenção pleiteando indenização por danos morais.' },
    { termo: 'denunciação da lide', significado: 'Intervenção de terceiro para exercer direito de regresso.', uso: 'Chamamento do garante ao processo (art. 125, CPC).', area: ['processual'], exemplo: 'Requer-se a denunciação da lide à seguradora (art. 125, II, CPC).' },
    { termo: 'chamamento ao processo', significado: 'Intervenção que traz ao processo os coobrigados do réu.', uso: 'Ampliação do polo passivo para incluir devedores solidários.', area: ['processual'], exemplo: 'O réu requereu o chamamento ao processo do devedor principal.' },
    { termo: 'assistência', significado: 'Intervenção de terceiro com interesse na vitória de uma das partes.', uso: 'Pode ser simples ou litisconsorcial.', area: ['processual'], exemplo: 'O sindicato ingressou como assistente litisconsorcial.' },
    { termo: 'competência absoluta', significado: 'Competência inderrogável por vontade das partes.', uso: 'Matéria, pessoa e função — reconhecível de ofício.', area: ['processual'], exemplo: 'A incompetência absoluta pode ser declarada a qualquer tempo.' },
    { termo: 'competência relativa', significado: 'Competência territorial ou de valor da causa, prorrogável.', uso: 'Deve ser arguida por exceção sob pena de prorrogação.', area: ['processual'], exemplo: 'A incompetência relativa deve ser arguida em preliminar de contestação.' },
    { termo: 'coisa julgada formal', significado: 'Imutabilidade da decisão dentro do mesmo processo.', uso: 'Impede rediscussão no mesmo feito, mas admite nova ação.', area: ['processual'], exemplo: 'A extinção sem mérito faz apenas coisa julgada formal.' },
    { termo: 'coisa julgada material', significado: 'Imutabilidade do mérito da decisão, impedindo nova ação idêntica.', uso: 'Decisão de mérito transitada em julgado não pode ser rediscutida.', area: ['processual'], exemplo: 'A sentença de mérito faz coisa julgada material (art. 502, CPC).' },
    { termo: 'honorários de sucumbência', significado: 'Remuneração do advogado da parte vencedora, paga pelo vencido.', uso: 'Fixados entre 10% e 20% do valor da condenação (art. 85, §2º, CPC).', area: ['processual'], exemplo: 'Os honorários sucumbenciais foram fixados em 15% sobre o valor da causa.' },
    { termo: 'produção antecipada de provas', significado: 'Ação autônoma para preservar ou produzir provas antes do processo principal.', uso: 'Evita perecimento de prova ou viabiliza composição (art. 381, CPC).', area: ['processual'], exemplo: 'Requer-se a produção antecipada de provas para preservação de documentos.' },
    { termo: 'tutela de evidência', significado: 'Tutela provisória independente de urgência.', uso: 'Concedida quando o direito é evidente (art. 311, CPC).', area: ['processual'], exemplo: 'Cabível a tutela de evidência quando há prova documental e tese firmada em repetitivos.' },
    { termo: 'cumprimento provisório', significado: 'Execução da sentença antes do trânsito em julgado.', uso: 'Exige caução e corre por conta e risco do exequente.', area: ['processual'], exemplo: 'Iniciou-se o cumprimento provisório da sentença condenatória.' },
    { termo: 'carta precatória', significado: 'Comunicação entre juízos de comarcas distintas para realização de ato processual.', uso: 'Expedida quando o ato deve ser praticado fora da jurisdição do juízo.', area: ['processual'], exemplo: 'Foi expedida carta precatória para oitiva da testemunha em São Paulo.' },
    { termo: 'distribuição por dependência', significado: 'Direcionamento de nova ação ao mesmo juízo de ação relacionada.', uso: 'Garante que processos conexos fiquem no mesmo juízo.', area: ['processual'], exemplo: 'A reconvenção foi distribuída por dependência ao juízo da ação principal.' },
];
