import type { LegalTerm } from './types';

/**
 * Glossário — Direito do Trabalho
 * ~50 termos jurídicos trabalhistas brasileiros.
 */
export const TRABALHISTA: LegalTerm[] = [
    // ── Termos existentes ──────────────────────────────────────────────
    {
        termo: 'obreiro',
        significado: 'Sinônimo formal de trabalhador ou empregado, usado em decisões judiciais e doutrina trabalhista.',
        uso: 'Referir-se ao empregado em petições e sentenças.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['trabalhador', 'empregado', 'laborista'],
        exemplo: 'O obreiro comprovou vínculo empregatício com a reclamada no período de 2019 a 2022.',
    },
    {
        termo: 'reclamada',
        significado: 'Parte demandada (geralmente o empregador) em uma reclamação trabalhista.',
        uso: 'Identificar o polo passivo na ação trabalhista.',
        area: ['trabalhista', 'processual'],
        origem: 'portugues',
        sinonimos: ['ré', 'demandada', 'empregadora'],
        exemplo: 'A reclamada não apresentou os controles de ponto, gerando presunção de veracidade da jornada alegada.',
    },
    {
        termo: 'reclamante',
        significado: 'Parte autora (geralmente o empregado) que propõe a reclamação trabalhista.',
        uso: 'Identificar o polo ativo na ação trabalhista.',
        area: ['trabalhista', 'processual'],
        origem: 'portugues',
        sinonimos: ['autor', 'demandante', 'empregado'],
        exemplo: 'O reclamante postulou o pagamento de horas extras e reflexos sobre as demais verbas.',
    },
    {
        termo: 'verbas rescisórias',
        significado: 'Conjunto de valores devidos ao empregado quando do término do contrato de trabalho, variando conforme a modalidade de rescisão.',
        uso: 'Descrever os haveres devidos na rescisão contratual.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['haveres rescisórios', 'direitos rescisórios'],
        exemplo: 'A empresa foi condenada ao pagamento das verbas rescisórias, incluindo saldo de salário, férias proporcionais +1/3 e 13º proporcional.',
    },
    {
        termo: 'aviso prévio',
        significado: 'Comunicação antecipada e obrigatória da intenção de rescindir o contrato de trabalho, podendo ser trabalhado ou indenizado.',
        uso: 'Referir-se ao período ou à indenização devida na rescisão sem justa causa.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['pré-aviso'],
        exemplo: 'O aviso prévio proporcional ao tempo de serviço totalizou 42 dias, nos termos da Lei 12.506/2011.',
    },
    {
        termo: 'justa causa',
        significado: 'Falta grave cometida pelo empregado que autoriza a rescisão do contrato de trabalho sem pagamento de determinadas verbas rescisórias, conforme art. 482 da CLT.',
        uso: 'Fundamentar a dispensa motivada do empregado.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['despedida motivada', 'rescisão por falta grave'],
        exemplo: 'A dispensa por justa causa foi revertida em juízo por ausência de proporcionalidade e gradação punitiva.',
    },
    {
        termo: 'equiparação salarial',
        significado: 'Direito do empregado de receber salário igual ao de outro empregado que exerça função idêntica, de igual valor, ao mesmo empregador e no mesmo estabelecimento, conforme art. 461 da CLT.',
        uso: 'Fundamentar pedido de isonomia salarial.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['isonomia salarial', 'paridade salarial'],
        exemplo: 'Deferida a equiparação salarial, pois demonstrado que reclamante e paradigma exerciam idêntica função com mesma produtividade.',
    },
    {
        termo: 'adicional de insalubridade',
        significado: 'Parcela remuneratória devida ao empregado exposto a agentes nocivos à saúde acima dos limites de tolerância, nos graus mínimo (10%), médio (20%) ou máximo (40%).',
        uso: 'Requerer pagamento por trabalho em condições insalubres.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['insalubridade'],
        exemplo: 'A perícia constatou exposição a ruído acima de 85 dB, fixando o adicional de insalubridade em grau médio (20%).',
    },
    {
        termo: 'horas extras',
        significado: 'Tempo de trabalho que excede a jornada legal ou contratual, remunerado com adicional mínimo de 50% sobre a hora normal.',
        uso: 'Requerer pagamento de jornada excedente.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['sobrejornada', 'horas suplementares', 'horas extraordinárias'],
        exemplo: 'O autor laborava das 8h às 20h, sendo devidas 2 horas extras diárias com adicional de 50%.',
    },
    {
        termo: 'intervalo intrajornada',
        significado: 'Período de descanso obrigatório concedido durante a jornada de trabalho para repouso e alimentação, com duração mínima de 1 hora para jornadas superiores a 6 horas.',
        uso: 'Discutir a concessão ou supressão do intervalo para refeição.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['intervalo para refeição', 'horário de almoço'],
        exemplo: 'A supressão parcial do intervalo intrajornada implica pagamento do período integral como hora extra, conforme Súmula 437 do TST.',
    },
    {
        termo: 'CTPS',
        significado: 'Carteira de Trabalho e Previdência Social — documento que registra a vida funcional do trabalhador, incluindo contratos, salários e anotações.',
        uso: 'Referir-se ao documento de registro do vínculo empregatício.',
        area: ['trabalhista', 'previdenciário'],
        origem: 'portugues',
        sinonimos: ['carteira de trabalho', 'carteira profissional'],
        exemplo: 'Determinada a retificação da CTPS para constar a data de admissão correta e a remuneração real.',
    },
    {
        termo: 'FGTS',
        significado: 'Fundo de Garantia do Tempo de Serviço — depósito mensal de 8% do salário em conta vinculada do empregado, como forma de proteção ao trabalhador dispensado sem justa causa.',
        uso: 'Referir-se aos depósitos fundiários e à multa de 40% na rescisão imotivada.',
        area: ['trabalhista', 'previdenciário'],
        origem: 'portugues',
        sinonimos: ['fundo de garantia'],
        exemplo: 'A reclamada foi condenada a recolher os depósitos de FGTS de todo o período contratual, acrescidos da multa de 40%.',
    },
    {
        termo: 'acordo coletivo',
        significado: 'Instrumento normativo negociado entre sindicato dos trabalhadores e uma ou mais empresas, com eficácia restrita aos empregados dessas empresas.',
        uso: 'Referir-se a negociação coletiva de âmbito empresarial.',
        area: ['trabalhista', 'coletivo'],
        origem: 'portugues',
        sinonimos: ['ACT', 'acordo coletivo de trabalho'],
        exemplo: 'O acordo coletivo firmado entre o sindicato e a empresa previu banco de horas com compensação semestral.',
    },
    {
        termo: 'convenção coletiva',
        significado: 'Instrumento normativo negociado entre sindicato dos trabalhadores e sindicato patronal, com eficácia para toda a categoria.',
        uso: 'Referir-se a negociação coletiva de âmbito categorial.',
        area: ['trabalhista', 'coletivo'],
        origem: 'portugues',
        sinonimos: ['CCT', 'convenção coletiva de trabalho'],
        exemplo: 'A convenção coletiva da categoria fixou piso salarial de R$ 2.800,00 para o biênio 2025/2026.',
    },
    {
        termo: 'dissídio coletivo',
        significado: 'Ação judicial proposta perante o tribunal trabalhista quando frustrada a negociação coletiva, cabendo ao tribunal fixar normas e condições de trabalho (poder normativo).',
        uso: 'Referir-se ao processo judicial de solução de conflito coletivo.',
        area: ['trabalhista', 'coletivo', 'processual'],
        origem: 'portugues',
        sinonimos: ['dissídio', 'conflito coletivo'],
        exemplo: 'O TRT julgou o dissídio coletivo e fixou reajuste salarial de 5% acima da inflação para a categoria.',
    },
    {
        termo: 'vínculo empregatício',
        significado: 'Relação jurídica entre empregado e empregador caracterizada pela presença simultânea de pessoalidade, não eventualidade, onerosidade e subordinação (art. 3º da CLT).',
        uso: 'Fundamentar o reconhecimento de relação de emprego.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['relação de emprego', 'vínculo de emprego'],
        exemplo: 'Restou configurado o vínculo empregatício, haja vista a presença de subordinação, habitualidade e onerosidade.',
    },
    {
        termo: 'dano existencial',
        significado: 'Lesão ao projeto de vida e às relações sociais do trabalhador decorrente de condições abusivas de trabalho, como jornadas excessivas reiteradas.',
        uso: 'Fundamentar pedido de indenização por privação do convívio social e lazer.',
        area: ['trabalhista', 'civil'],
        origem: 'portugues',
        sinonimos: ['dano ao projeto de vida'],
        exemplo: 'A jornada habitual de 16 horas diárias durante 5 anos configurou dano existencial, sendo fixada indenização de R$ 50.000,00.',
    },

    // ── Novos termos ───────────────────────────────────────────────────
    {
        termo: 'adicional de periculosidade',
        significado: 'Parcela de 30% sobre o salário-base devida ao empregado que trabalha em condições de perigo, como exposição a inflamáveis, explosivos, energia elétrica ou segurança pessoal/patrimonial.',
        uso: 'Requerer pagamento por trabalho em condições perigosas.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['periculosidade'],
        exemplo: 'O eletricista faz jus ao adicional de periculosidade de 30%, conforme laudo pericial que atestou contato com sistema elétrico de potência.',
    },
    {
        termo: 'adicional noturno',
        significado: 'Acréscimo de pelo menos 20% sobre a hora diurna devido ao trabalho realizado entre 22h e 5h (urbano) ou em horários específicos para rurais, com hora noturna reduzida de 52 minutos e 30 segundos.',
        uso: 'Requerer pagamento de adicional pelo trabalho noturno.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['noturno'],
        exemplo: 'O reclamante que laborava das 22h às 6h recebia adicional noturno apenas até as 5h, sendo devida a extensão do adicional à hora prorrogada.',
    },
    {
        termo: 'assédio moral',
        significado: 'Conduta abusiva, reiterada e sistemática que atenta contra a dignidade ou integridade psíquica do trabalhador, criando ambiente de trabalho hostil e degradante.',
        uso: 'Fundamentar pedido de indenização por dano moral decorrente de perseguição ou humilhação no trabalho.',
        area: ['trabalhista', 'civil'],
        origem: 'portugues',
        sinonimos: ['mobbing', 'bullying organizacional'],
        exemplo: 'Caracterizado o assédio moral pela exposição reiterada do empregado a situações humilhantes perante colegas, sendo fixada indenização de R$ 30.000,00.',
    },
    {
        termo: 'assédio sexual',
        significado: 'Conduta de natureza sexual indesejada praticada no ambiente de trabalho, especialmente quando envolve relação de hierarquia, constituindo crime tipificado no art. 216-A do Código Penal.',
        uso: 'Fundamentar rescisão indireta e indenização, além de eventual responsabilização penal.',
        area: ['trabalhista', 'penal'],
        origem: 'portugues',
        exemplo: 'A empregada comprovou o assédio sexual praticado pelo superior hierárquico, sendo deferida a rescisão indireta com pagamento integral das verbas rescisórias.',
    },
    {
        termo: 'banco de horas',
        significado: 'Sistema de compensação de jornada em que as horas excedentes são acumuladas para posterior compensação com folgas, dispensando o pagamento de adicional de horas extras.',
        uso: 'Referir-se ao regime de compensação de jornada por acordo individual ou coletivo.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['compensação de jornada'],
        exemplo: 'O banco de horas foi considerado inválido por ausência de previsão em acordo coletivo, sendo devidas as horas extras com adicional de 50%.',
    },
    {
        termo: 'comissão',
        significado: 'Modalidade de remuneração variável calculada com base em percentual sobre vendas ou negócios realizados pelo empregado, integrando o salário para todos os efeitos legais.',
        uso: 'Discutir a natureza salarial e os reflexos da parcela variável.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['comissões', 'percentagem'],
        exemplo: 'As comissões habituais integram a remuneração do vendedor para cálculo de férias, 13º salário e FGTS.',
    },
    {
        termo: 'contrato por prazo determinado',
        significado: 'Modalidade contratual com termo final prefixado, admitida em serviços cuja natureza justifique a predeterminação do prazo, atividades transitórias ou contrato de experiência (art. 443 da CLT).',
        uso: 'Referir-se a contratos temporários e suas particularidades rescisórias.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['contrato a termo', 'contrato temporário'],
        exemplo: 'O contrato por prazo determinado de 90 dias foi prorrogado por mais 90, atingindo o limite máximo de 2 anos previsto na CLT.',
    },
    {
        termo: 'contribuição sindical',
        significado: 'Contribuição devida pelos integrantes de uma categoria profissional ou econômica ao respectivo sindicato, que após a Reforma Trabalhista (Lei 13.467/2017) passou a ser facultativa.',
        uso: 'Discutir obrigatoriedade e desconto em folha de pagamento.',
        area: ['trabalhista', 'coletivo'],
        origem: 'portugues',
        sinonimos: ['imposto sindical', 'contribuição confederativa'],
        exemplo: 'Após a Reforma Trabalhista, a contribuição sindical somente pode ser descontada mediante autorização prévia e expressa do trabalhador.',
    },
    {
        termo: 'desvio de função',
        significado: 'Situação em que o empregado exerce atribuições distintas e superiores às de seu cargo contratual, sem a correspondente alteração salarial.',
        uso: 'Fundamentar pedido de diferenças salariais por exercício de função diversa da contratada.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['acúmulo de função'],
        exemplo: 'Comprovado o desvio de função, o reclamante foi condenado a receber diferenças salariais correspondentes ao cargo efetivamente exercido.',
    },
    {
        termo: 'empregado doméstico',
        significado: 'Pessoa física que presta serviços de forma contínua, subordinada, onerosa e pessoal, de finalidade não lucrativa, à pessoa ou família no âmbito residencial, conforme LC 150/2015.',
        uso: 'Referir-se ao trabalhador doméstico e seus direitos específicos.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['trabalhador doméstico', 'doméstico'],
        exemplo: 'A empregada doméstica que trabalhava 3 dias por semana teve reconhecido o vínculo empregatício, afastando a condição de diarista.',
    },
    {
        termo: 'estabilidade provisória',
        significado: 'Garantia temporária de emprego que impede a dispensa arbitrária do empregado em situações específicas previstas em lei ou norma coletiva, como gestante, cipeiro e acidentado.',
        uso: 'Fundamentar a impossibilidade de dispensa ou pedido de reintegração.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['garantia de emprego', 'estabilidade temporária'],
        exemplo: 'O empregado acidentado goza de estabilidade provisória de 12 meses após a cessação do auxílio-doença acidentário, nos termos do art. 118 da Lei 8.213/91.',
    },
    {
        termo: 'férias',
        significado: 'Período de descanso anual remunerado de 30 dias a que tem direito o empregado após cada período de 12 meses de vigência do contrato, acrescido do terço constitucional.',
        uso: 'Discutir concessão, pagamento e prazos relativos ao descanso anual.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['descanso anual', 'férias remuneradas'],
        exemplo: 'As férias vencidas e não concedidas no prazo legal devem ser pagas em dobro, conforme art. 137 da CLT.',
    },
    {
        termo: 'gestante estabilidade',
        significado: 'Garantia de emprego da empregada gestante desde a confirmação da gravidez até 5 meses após o parto, conforme art. 10, II, "b", do ADCT.',
        uso: 'Fundamentar a impossibilidade de dispensa da empregada gestante.',
        area: ['trabalhista', 'constitucional'],
        origem: 'portugues',
        sinonimos: ['estabilidade gestante', 'garantia de emprego da gestante'],
        exemplo: 'A dispensa da empregada gestante, ainda que desconhecida a gravidez pelo empregador, é nula, sendo devida a reintegração ou indenização substitutiva.',
    },
    {
        termo: 'grupo econômico',
        significado: 'Conjunto de empresas que, embora com personalidade jurídica própria, estão sob direção, controle ou administração de outra, sendo solidariamente responsáveis pelas obrigações trabalhistas (art. 2º, §2º da CLT).',
        uso: 'Fundamentar a responsabilização solidária de empresas do mesmo grupo.',
        area: ['trabalhista', 'empresarial'],
        origem: 'portugues',
        sinonimos: ['conglomerado', 'grupo empresarial'],
        exemplo: 'Reconhecido o grupo econômico, todas as empresas integrantes respondem solidariamente pelas verbas trabalhistas deferidas.',
    },
    {
        termo: 'homologação',
        significado: 'Ato de validação oficial de rescisão contratual ou acordo, anteriormente obrigatória pelo sindicato para empregados com mais de 1 ano de contrato (regra alterada pela Reforma Trabalhista).',
        uso: 'Referir-se à formalização da rescisão ou validação de acordo judicial.',
        area: ['trabalhista', 'processual'],
        origem: 'portugues',
        sinonimos: ['ratificação', 'validação'],
        exemplo: 'O acordo celebrado entre as partes foi submetido à homologação judicial, com quitação restrita às parcelas expressamente consignadas.',
    },
    {
        termo: 'hora noturna reduzida',
        significado: 'Ficção jurídica pela qual a hora de trabalho noturno (entre 22h e 5h) corresponde a 52 minutos e 30 segundos, resultando em jornada noturna de 7 horas equivalente a 8 horas diurnas.',
        uso: 'Calcular corretamente a jornada noturna e as horas extras noturnas.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['hora ficta noturna'],
        exemplo: 'Considerando a hora noturna reduzida, o vigilante que trabalhava das 22h às 6h cumpria 9 horas e 8 minutos, sendo devidas horas extras.',
    },
    {
        termo: 'indenização substitutiva',
        significado: 'Pagamento em dinheiro equivalente aos salários e vantagens do período de estabilidade, quando a reintegração do empregado se torna desaconselhável.',
        uso: 'Converter a obrigação de reintegrar em pagamento pecuniário.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['indenização do período estabilitário'],
        exemplo: 'Ante a incompatibilidade para o retorno ao emprego, converteu-se a reintegração em indenização substitutiva do período de estabilidade.',
    },
    {
        termo: 'jornada 12x36',
        significado: 'Regime especial de trabalho em que o empregado labora 12 horas consecutivas e descansa nas 36 horas seguintes, permitido por acordo individual escrito, convenção ou acordo coletivo.',
        uso: 'Referir-se ao regime de jornada de 12 horas de trabalho por 36 de descanso.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['escala 12 por 36', 'regime 12x36'],
        exemplo: 'O enfermeiro contratado sob regime 12x36 não tem direito a horas extras habituais, salvo descumprimento da escala.',
    },
    {
        termo: 'multa do art. 477',
        significado: 'Penalidade equivalente a um salário do empregado devida pelo empregador que não efetuar o pagamento das verbas rescisórias no prazo de 10 dias contados do término do contrato (art. 477, §8º da CLT).',
        uso: 'Requerer a multa por atraso no pagamento das verbas rescisórias.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['multa rescisória', 'multa por atraso na rescisão'],
        exemplo: 'O pagamento das verbas rescisórias ocorreu 25 dias após a dispensa, sendo devida a multa do art. 477 da CLT.',
    },
    {
        termo: 'multa do art. 467',
        significado: 'Penalidade que obriga o empregador a pagar as verbas rescisórias incontroversas na primeira audiência, sob pena de acréscimo de 50% sobre o valor devido (art. 467 da CLT).',
        uso: 'Requerer o pagamento imediato das parcelas incontroversas em audiência.',
        area: ['trabalhista', 'processual'],
        origem: 'portugues',
        sinonimos: ['multa por incontroverso'],
        exemplo: 'A reclamada não pagou na primeira audiência as verbas incontroversas, incidindo a multa de 50% prevista no art. 467 da CLT.',
    },
    {
        termo: 'norma mais favorável',
        significado: 'Princípio do Direito do Trabalho segundo o qual, havendo conflito entre normas aplicáveis, prevalece aquela que for mais benéfica ao trabalhador.',
        uso: 'Fundamentar a aplicação de norma coletiva ou legal mais benéfica.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['princípio da norma mais favorável', 'favor laboratoris'],
        exemplo: 'Aplicando o princípio da norma mais favorável, prevaleceu a convenção coletiva que fixava adicional de horas extras de 70%.',
    },
    {
        termo: 'piso salarial',
        significado: 'Valor mínimo de remuneração fixado por lei estadual, convenção coletiva ou acordo coletivo para determinada categoria profissional ou função.',
        uso: 'Referir-se ao salário mínimo categorial.',
        area: ['trabalhista', 'coletivo'],
        origem: 'portugues',
        sinonimos: ['salário normativo', 'piso da categoria'],
        exemplo: 'O reclamante recebia salário inferior ao piso salarial da categoria, sendo devidas diferenças salariais e reflexos.',
    },
    {
        termo: 'poder diretivo',
        significado: 'Faculdade do empregador de organizar, regulamentar, fiscalizar e disciplinar a prestação de serviços, como decorrência do contrato de trabalho e da assunção dos riscos da atividade.',
        uso: 'Discutir os limites do poder do empregador na relação de trabalho.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['poder de direção', 'poder empregatício'],
        exemplo: 'O exercício abusivo do poder diretivo, com imposição de metas inatingíveis e punições desproporcionais, configura assédio moral.',
    },
    {
        termo: 'primazia da realidade',
        significado: 'Princípio trabalhista que confere prevalência à situação fática sobre a forma documental, de modo que os fatos prevalecem sobre os ajustes formais.',
        uso: 'Desconstituir documentos que não reflitam a realidade da relação de trabalho.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['contrato-realidade', 'princípio da realidade'],
        exemplo: 'Pelo princípio da primazia da realidade, o contrato de prestação de serviços foi descaracterizado, reconhecendo-se o vínculo empregatício.',
    },
    {
        termo: 'readaptação',
        significado: 'Transferência do empregado para função compatível com sua capacidade laborativa reduzida em razão de doença ou acidente, mediante orientação do INSS.',
        uso: 'Referir-se ao retorno ao trabalho em função diferente por limitação funcional.',
        area: ['trabalhista', 'previdenciário'],
        origem: 'portugues',
        sinonimos: ['reabilitação profissional'],
        exemplo: 'Após alta previdenciária, o empregado readaptado foi transferido para função administrativa compatível com suas limitações físicas.',
    },
    {
        termo: 'reintegração',
        significado: 'Retorno do empregado ao mesmo cargo e condições anteriores, determinado judicialmente quando reconhecida a nulidade da dispensa, como nos casos de estabilidade.',
        uso: 'Requerer o retorno ao emprego com todas as vantagens do período de afastamento.',
        area: ['trabalhista', 'processual'],
        origem: 'portugues',
        sinonimos: ['restauração do contrato'],
        exemplo: 'Deferida a reintegração do cipeiro dispensado imotivadamente durante o período de estabilidade, com pagamento dos salários do período de afastamento.',
    },
    {
        termo: 'rescisão indireta',
        significado: 'Forma de extinção do contrato de trabalho por iniciativa do empregado em razão de falta grave cometida pelo empregador, equiparando-se à dispensa sem justa causa para fins de verbas rescisórias (art. 483 da CLT).',
        uso: 'Fundamentar o pedido de rompimento do contrato por culpa do empregador.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['despedida indireta', 'justa causa do empregador'],
        exemplo: 'O atraso reiterado no pagamento dos salários por mais de 3 meses justificou o reconhecimento da rescisão indireta.',
    },
    {
        termo: 'salário in natura',
        significado: 'Utilidade fornecida habitualmente pelo empregador como contraprestação pelo trabalho, integrando o salário para todos os efeitos legais, salvo as exceções do art. 458, §2º da CLT.',
        uso: 'Discutir se determinada utilidade tem natureza salarial.',
        area: ['trabalhista'],
        origem: 'latim',
        sinonimos: ['salário-utilidade', 'salário em espécie'],
        exemplo: 'A moradia fornecida ao caseiro como contraprestação pelo trabalho configura salário in natura, integrando a remuneração para cálculo das verbas.',
    },
    {
        termo: 'terceirização',
        significado: 'Contratação de empresa interposta para execução de serviços, permitida para qualquer atividade após decisão do STF (ADPF 324 e RE 958.252), mantida a responsabilidade subsidiária da tomadora.',
        uso: 'Discutir a licitude da intermediação de mão de obra e a responsabilização da tomadora.',
        area: ['trabalhista', 'empresarial'],
        origem: 'portugues',
        sinonimos: ['subcontratação', 'outsourcing'],
        exemplo: 'Reconhecida a responsabilidade subsidiária da tomadora de serviços pelas verbas trabalhistas, nos termos da Súmula 331 do TST.',
    },
    {
        termo: 'trabalho intermitente',
        significado: 'Modalidade contratual introduzida pela Reforma Trabalhista (art. 443, §3º da CLT) em que a prestação de serviços ocorre de forma não contínua, com alternância de períodos de atividade e inatividade.',
        uso: 'Referir-se ao contrato com convocação esporádica e pagamento proporcional.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['contrato intermitente', 'trabalho sob demanda'],
        exemplo: 'No contrato de trabalho intermitente, o empregado foi convocado com 3 dias de antecedência e recebeu proporcionalmente pelas horas efetivamente trabalhadas.',
    },
    {
        termo: 'transferência',
        significado: 'Alteração do local de trabalho do empregado que implique mudança de domicílio, somente lícita com anuência do empregado ou em caso de real necessidade de serviço, com adicional de 25% (art. 469 da CLT).',
        uso: 'Discutir a licitude da alteração do local de trabalho e o adicional de transferência.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['remoção', 'transferência de localidade'],
        exemplo: 'O empregado transferido provisoriamente para filial em outro estado faz jus ao adicional de transferência de 25% sobre o salário.',
    },
    {
        termo: 'vale-transporte',
        significado: 'Benefício antecipado pelo empregador para cobertura das despesas de deslocamento residência-trabalho e vice-versa em transporte público, com desconto de até 6% do salário-base do empregado.',
        uso: 'Referir-se ao benefício de transporte e seu desconto em folha.',
        area: ['trabalhista'],
        origem: 'portugues',
        sinonimos: ['VT'],
        exemplo: 'A substituição do vale-transporte por pagamento em dinheiro é considerada irregular, salvo previsão em acordo ou convenção coletiva.',
    },
    {
        termo: 'acidente de trabalho',
        significado: 'Evento que ocorre pelo exercício do trabalho a serviço da empresa, provocando lesão corporal, perturbação funcional ou doença que cause morte, perda ou redução da capacidade para o trabalho (art. 19 da Lei 8.213/91).',
        uso: 'Fundamentar estabilidade acidentária, indenizações e benefícios previdenciários.',
        area: ['trabalhista', 'previdenciário'],
        origem: 'portugues',
        sinonimos: ['infortúnio laboral', 'sinistro laboral'],
        exemplo: 'O acidente de trabalho típico sofrido pelo operário resultou em estabilidade provisória de 12 meses após a alta do INSS e indenização por dano moral e material.',
    },
];
