import type { LegalTerm } from './types';

/**
 * Glossário — Direito Tributário.
 */
export const TRIBUTARIO: LegalTerm[] = [
    // ── Existentes ──────────────────────────────────────────────────────
    { termo: 'fato gerador', significado: 'Situação prevista em lei que faz nascer a obrigação tributária.', uso: 'Art. 114 do CTN — ocorrência concreta da hipótese de incidência.', area: ['tributario'], exemplo: 'O fato gerador do ICMS é a circulação de mercadorias.' },
    { termo: 'base de cálculo', significado: 'Valor sobre o qual se aplica a alíquota do tributo.', uso: 'Grandeza econômica que quantifica a obrigação tributária.', area: ['tributario'], exemplo: 'A base de cálculo do IRPJ é o lucro real.' },
    { termo: 'lançamento tributário', significado: 'Ato administrativo que constitui o crédito tributário.', uso: 'Modalidades: de ofício, por declaração, por homologação.', area: ['tributario'], exemplo: 'O lançamento tributário é nulo por vício de competência.' },
    { termo: 'crédito tributário', significado: 'Direito do Fisco de exigir o tributo do contribuinte.', uso: 'Constituído pelo lançamento (art. 142, CTN).', area: ['tributario'], exemplo: 'O crédito tributário foi extinto pelo pagamento.' },
    { termo: 'elisão fiscal', significado: 'Planejamento tributário lícito para reduzir carga fiscal.', uso: 'Uso de meios legais para pagar menos tributos.', area: ['tributario'], exemplo: 'A reorganização societária constitui elisão fiscal legítima.' },
    { termo: 'execução fiscal', significado: 'Ação de cobrança de dívida ativa pela Fazenda Pública.', uso: 'Procedimento especial da Lei 6.830/80.', area: ['tributario'], exemplo: 'A execução fiscal foi ajuizada para cobrança de ICMS.' },

    // ── Novos ───────────────────────────────────────────────────────────
    { termo: 'hipótese de incidência', significado: 'Descrição abstrata do fato que enseja a obrigação tributária.', uso: 'Previsão legal genérica — quando ocorre no mundo real, torna-se fato gerador.', area: ['tributario'], exemplo: 'A hipótese de incidência do ISS é a prestação de serviços.' },
    { termo: 'alíquota', significado: 'Percentual ou valor fixo aplicado sobre a base de cálculo.', uso: 'Define o quantum do tributo devido.', area: ['tributario'], exemplo: 'A alíquota do ICMS interestadual é de 12%.' },
    { termo: 'contribuinte', significado: 'Sujeito passivo que tem relação pessoal e direta com o fato gerador.', uso: 'Pessoa obrigada ao pagamento do tributo (art. 121, I, CTN).', area: ['tributario'], exemplo: 'O contribuinte do IPTU é o proprietário do imóvel.' },
    { termo: 'responsável tributário', significado: 'Terceiro obrigado ao pagamento do tributo por disposição legal.', uso: 'Não é o contribuinte, mas a lei lhe atribui responsabilidade (art. 121, II, CTN).', area: ['tributario'], exemplo: 'O empregador é responsável tributário pelo recolhimento do IR na fonte.' },
    { termo: 'substituição tributária', significado: 'Regime em que terceiro recolhe o tributo no lugar do contribuinte.', uso: 'Comum no ICMS — fabricante recolhe por toda a cadeia.', area: ['tributario'], sinonimos: ['ST'], exemplo: 'O ICMS-ST foi retido na fonte pelo fabricante.' },
    { termo: 'dívida ativa', significado: 'Crédito tributário inscrito para cobrança judicial.', uso: 'Inscrição pela Procuradoria gera certidão executável.', area: ['tributario'], exemplo: 'O débito foi inscrito em dívida ativa e ajuizada a execução fiscal.' },
    { termo: 'CDA', significado: 'Certidão de Dívida Ativa — título executivo na execução fiscal.', uso: 'Documento que instrui a execução fiscal (art. 2º, §5º, Lei 6.830).', area: ['tributario'], sinonimos: ['certidão de dívida ativa'], exemplo: 'A CDA é nula por ausência do fundamento legal da cobrança.' },
    { termo: 'decadência tributária', significado: 'Perda do direito de constituir o crédito tributário pelo lançamento.', uso: 'Prazo de 5 anos (art. 173, CTN).', area: ['tributario'], exemplo: 'O lançamento está fulminado pela decadência tributária.' },
    { termo: 'prescrição tributária', significado: 'Perda do direito de cobrar judicialmente o crédito tributário.', uso: 'Prazo de 5 anos da constituição definitiva (art. 174, CTN).', area: ['tributario'], exemplo: 'O crédito está prescrito, devendo ser cancelada a inscrição em dívida ativa.' },
    { termo: 'imunidade tributária', significado: 'Limitação constitucional ao poder de tributar.', uso: 'Vedação constitucional à instituição de tributo sobre determinadas situações.', area: ['tributario', 'constitucional'], exemplo: 'Os templos religiosos gozam de imunidade tributária (art. 150, VI, "b", CF).' },
    { termo: 'isenção', significado: 'Dispensa legal do pagamento de tributo.', uso: 'Exclusão do crédito tributário por lei específica (art. 176, CTN).', area: ['tributario'], exemplo: 'A isenção de ICMS foi concedida por convênio do CONFAZ.' },
    { termo: 'anistia fiscal', significado: 'Perdão de penalidades tributárias.', uso: 'Exclui infrações cometidas antes da lei concessiva (art. 180, CTN).', area: ['tributario'], exemplo: 'O programa de anistia fiscal perdoou as multas por atraso.' },
    { termo: 'repetição de indébito', significado: 'Restituição de tributo pago indevidamente.', uso: 'Ação para recuperar valores tributários pagos a maior ou sem causa.', area: ['tributario'], exemplo: 'Requer-se a repetição do indébito tributário dos últimos 5 anos.' },
    { termo: 'compensação tributária', significado: 'Utilização de crédito do contribuinte para quitar débito tributário.', uso: 'Art. 170 do CTN — créditos e débitos recíprocos entre Fisco e contribuinte.', area: ['tributario'], exemplo: 'O contribuinte requereu compensação dos valores pagos a maior.' },
    { termo: 'denúncia espontânea', significado: 'Confissão de infração tributária antes de procedimento fiscal.', uso: 'Exclui a multa se acompanhada do pagamento integral (art. 138, CTN).', area: ['tributario'], exemplo: 'A denúncia espontânea afasta a aplicação da multa punitiva.' },
    { termo: 'evasão fiscal', significado: 'Prática ilícita para evitar o pagamento de tributos.', uso: 'Diferente da elisão — envolve fraude, simulação ou sonegação.', area: ['tributario'], exemplo: 'A omissão de receitas configura evasão fiscal passível de sanção penal.' },
    { termo: 'ITBI', significado: 'Imposto sobre Transmissão de Bens Imóveis.', uso: 'Competência municipal — incide sobre a transferência onerosa de imóveis.', area: ['tributario', 'imobiliario'], exemplo: 'O ITBI é devido na escritura de compra e venda do imóvel.' },
    { termo: 'ITCMD', significado: 'Imposto sobre Transmissão Causa Mortis e Doação.', uso: 'Competência estadual — incide sobre herança e doações.', area: ['tributario', 'familia'], exemplo: 'O ITCMD incide sobre os bens transmitidos por herança.' },
    { termo: 'Simples Nacional', significado: 'Regime tributário simplificado para micro e pequenas empresas.', uso: 'Unifica tributos federais, estaduais e municipais em guia única.', area: ['tributario', 'empresarial'], exemplo: 'A empresa foi excluída do Simples Nacional por exceder o limite de receita.' },
    { termo: 'obrigação acessória', significado: 'Dever instrumental do contribuinte (declarações, livros, registros).', uso: 'Distinta da obrigação principal (pagar tributo) — art. 113, §2º, CTN.', area: ['tributario'], exemplo: 'A falta de entrega da DCTF configura descumprimento de obrigação acessória.' },
    { termo: 'mandado de segurança em matéria tributária', significado: 'Remédio constitucional contra ato ilegal da autoridade fiscal.', uso: 'Exige direito líquido e certo — não comporta dilação probatória.', area: ['tributario', 'constitucional'], exemplo: 'Impetra-se mandado de segurança contra a exigência inconstitucional do tributo.' },
    { termo: 'embargos à execução fiscal', significado: 'Defesa do executado na execução fiscal.', uso: 'Exige garantia do juízo — matéria ampla de defesa (art. 16, Lei 6.830).', area: ['tributario'], exemplo: 'Foram opostos embargos à execução fiscal alegando prescrição intercorrente.' },
];
