export const THINK_LABELS = [
    'um segundo…',
    'deixa eu ver…',
    'boa pergunta…',
    'hmm…',
    'processando…',
    'inventando jurisprudência…',
    'citando fonte que não existe…',
    'culpando o estagiário…',
    'consultando o achômetro…',
    'fabricando precedente…',
    'vendo se tem jeito…',
    'improvisando com confiança…',
    'fingindo que leu tudo…',
    'adiando o inevitável…',
    'fazendo parecer mais difícil…',
    'perguntando pro Lenza…',
    'esperando o Tartuce responder…',
    'checando no Vade Mecum…',
    'ligando pro Didier…',
    'aguardando o STF mudar de ideia…',
    'vendo se tem súmula pra isso…',
    'rezando pro TJ aceitar…',
];
